### ISSUE TITLE
hexo g error

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#106]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

**Platform:**
Windows

**Browser:**

## Expected behavior 

hexo g success

## Actual behavior 

some problem when the command hexo g running

![snipaste_2018-06-21_23-15-01](https://user-images.githubusercontent.com/16351105/41728281-04cd5a98-75a9-11e8-8df7-d17cc1a5aa55.png)
![snipaste_2018-06-21_23-15-11](https://user-images.githubusercontent.com/16351105/41728286-0888f9c6-75a9-11e8-8d1c-6f61c148cc5d.png)

## Feature Request

---

**Comment by Molunerfinn** [comment]
Node version?

**Comment by jerryc127** [comment]
v8.11.2

**Comment by Molunerfinn** [comment]
Show your `package.json` which is in your hexo blog folder.

**Comment by jerryc127** [comment]
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.1"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-admin": "^2.3.0",
    "hexo-asset-image": "0.0.3",
    "hexo-autonofollow": "^1.0.1",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-baidu-sitemap": "^0.1.2",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-search": "^2.2.5",
    "hexo-generator-searchdb": "^1.0.8",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-live2d": "^3.0.3",
    "hexo-leancloud-counter-security": "^1.3.2",
    "hexo-neat": "^1.0.4",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^0.3.2",
    "hexo-renderer-pug": "0.0.5",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.2",
    "hexo-symbols-count-time": "^0.4.2",
    "hexo-tag-cloud": "^2.0.10",
    "live2d-widget-model-haruto": "^1.0.5"
  },
  "main": "index.js",
  "devDependencies": {},
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": ""
}

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/41728816-494462c4-75aa-11e8-81f9-2fb1a21d5a8e.png)
I found you have two pug renderer. The `hexo-renderer-jade` is also a pug renderer and is provided by official. You need to remove the `hexo-renderer-pug`.

Try this: 

```bash
npm remove hexo-renderer-pug
```

And remove your `node_modules` folder and then `npm install` again.

Then

```bash
hexo clean
hexo g
```

Try it.

**Comment by Molunerfinn** [comment]
Any feedback? Or I will close this issue~

**Comment by jerryc127** [comment]
it still show the error

**Comment by upupming** [comment]
How about using [this `package.json`](https://raw.githubusercontent.com/upupming/upupming.github.io/source/package.json)?

**Comment by jerryc127** [comment]
it solved, thanks.
change the hexo config "keyword"
