### ISSUE TITLE
mathjax long line incompletely display

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#108]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.6

**Platform:** ubuntu 18.04

**Browser:** Chrome

## Expected behavior 

I write a long mathjax:

```tex
$p = 101, q = 113, n = pq = 11413, \phi(n) = (p-1)(q-1) = 11200, e = 3533, d = (e^{-1}\ mod\ 11200 \equiv 11200) = 6597$
```

It's expected to show properly like the mathjax.org's demo.

<img src=https://user-images.githubusercontent.com/24741764/41917335-b820a08c-798c-11e8-83fd-baaeeee45fb6.png height=300>

## Actual behavior 

But I found that the parts that exceed row length cannot be displayed.

![screenshot from 2018-06-26 21-51-31](https://user-images.githubusercontent.com/24741764/41916797-62440cea-798b-11e8-9490-0ece5e777aeb.png)

I think you can make the mathjax better by making some adjustments. Other issue #93 needs a good solution, too. What do you think?

**Comment by Molunerfinn** [comment]
Mathjax is a problem for me too. It's difficult for the theme to adjust it while it should be both rendered by hexo & mathjax.js.

By the way, I found if you put a long line into mathjax.org's text-area, it will get a `multiline.js` for display:
![image](https://user-images.githubusercontent.com/12621342/41918640-5734ffd6-798f-11e8-9cdc-bc45c02c1ddc.png)
I think may be I can add this js to see what we get.

**Comment by Molunerfinn** [comment]
OK, I have fixed this.
While I don't use Mathjax, I don't understand all of it's settings. :sweat_smile:

**Comment by Molunerfinn** [comment]
Screentshot:
![image](https://user-images.githubusercontent.com/12621342/41919590-768b5a2c-7991-11e8-9979-b5a5557105d9.png)
