### ISSUE TITLE
tags 页面为空 

### ISSUE THREAD

**Issue by chnwentao** [Molunerfinn/hexo-theme-melody#11]
设置后 tags点进去是个空的页面

**Comment by Molunerfinn** [comment]
在你hexo的根目录下输入` hexo new page tags`,然后hexo会创建一个`source/tags/index.md`，修改一下默认生成的`index.md`，增加一个`type`字段：
```
---
title: tags
date: 2017-11-23 22:18:18
type: "tags"
---
```

**Comment by Molunerfinn** [comment]
然后再`hexo clean && hexo g`重新生成页面即可。`categories`的页面同理

**Comment by chnwentao** [comment]
问题已解决！ 谢谢！！

**Comment by Molunerfinn** [comment]
👍 : )

**Comment by binbin1808** [comment]
兄弟头像不错，`---
title: tags
date: 2017-11-23 22:18:18
type: "tags"
---`
我如何配置想要增加的标签呢
