### ISSUE TITLE
design a 404 Page

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#110]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.6

**Platform:** ubuntu 18.04

**Browser:** Chrome

## Expected behavior 

404 page doesn't need comments, like below:

![screenshot from 2018-06-27 18-57-34](https://user-images.githubusercontent.com/24741764/41970050-fbdf50d4-7a3b-11e8-8192-f4d17ab17b37.png)

## Actual behavior 

But now it has comments:

![screenshot from 2018-06-27 18-42-13](https://user-images.githubusercontent.com/24741764/41970089-1b4a93de-7a3c-11e8-99f3-8adbffa794e1.png)

The corresponding code is in `/layout/page.pug`:

```pug
else
    article#page
      h1= page.title
      .article-container!= page.content
    include includes/pagination.pug
    if page.comments !== false
      include includes/comments/index.pug
```

I originally intended to change `else` to  `else if page.type !== 'error'` to disable comments on 404 page, but I think we can go further. 

How about **design a brilliant 404 error pages**?

**Comment by Molunerfinn** [comment]
It's one of the v1.6 plans: https://github.com/Molunerfinn/hexo-theme-melody/projects/1

**Comment by upupming** [comment]
By the way, it seems that the license image is down, doesn't it?
<img src=https://user-images.githubusercontent.com/24741764/41981185-e58e00cc-7a5a-11e8-9e86-40824d431b44.png height=300>

**Comment by Molunerfinn** [comment]
Nope...may be it's your network problem.
![image](https://user-images.githubusercontent.com/12621342/41981466-92a00472-7a5b-11e8-9a9f-4cc072a00894.png)

**Comment by upupming** [comment]
Sorry, it is my problem！

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/66727870-5cad7780-ee74-11e9-9353-526446bef76c.png)

Full Sreen Background Image 404 Page

**Comment by upupming** [comment]
Cool, is this the final version or just an idea?

**Comment by Molunerfinn** [comment]
Final version & the text can be configured

**Comment by upupming** [comment]
It's very simple but prominent, and I'm totally in favor of this stylish design.

**Comment by Molunerfinn** [comment]
v1.7 is coming soon after I finished the docs

**Comment by Kiyo5hi** [comment]
@Molunerfinn I know this might be stupid, but why my hexo is not generating the 404 page? I've already updated the theme and also updated my config file.

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/66811544-df613000-ef63-11e9-919b-fbede34cf302.png)
![image](https://user-images.githubusercontent.com/12621342/66811568-ea1bc500-ef63-11e9-8e72-8e54f56a967d.png)
http://yoursite.com/404.html

**Comment by upupming** [comment]
@Kiyo5hi Did you forget to delete the `404.md` file under the `source` folder? It will overwrite the melody's default 404 page.

**Comment by Kiyo5hi** [comment]
@upupming @Molunerfinn Got it now. I've tried doing some similar stuff but did not know that I need to add permalink loll
