### ISSUE TITLE
添加head.pug内容出錯，求解答

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#112]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
1.5.6

**Platform:**
windows

**Browser:**

## Expected behavior 
一切運行順利

## Feature Request

想在head裏添加 幾個網站站長平臺的認證和百度推動，但是直接寫上出現了報錯，我該已怎樣的格式書寫？?

想添加的内容

```
//- 百度推送 

<script>
(function(){
    var bp = document.createElement('script');
    var curProtocol = window.location.protocol.split(':')[0];
    if (curProtocol === 'https') {
        bp.src = 'https://zz.bdstatic.com/linksubmit/push.js';
    }
    else {
        bp.src = 'http://push.zhanzhang.baidu.com/push.js';
    }
    var s = document.getElementsByTagName("script")[0];
    s.parentNode.insertBefore(bp, s);
})();
</script>

<meta name="baidu-site-verification" content="xx" />
<meta name="google-site-verification" content="xx" />
<meta name="msvalidate.01" content="xx" />
<meta name="360-site-verification" content="xx"/>
```
---

**Comment by Molunerfinn** [comment]
你既然都知道在`head.pug`里引入相应的代码了也可以看看`head.pug`里的代码是怎么写的啊。

script引入可以参考：
https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/layout/includes/head.pug#L42-L61

meta的写法是这样：

`meta(name="xxxx" content="xxx")`

如果需要更多相关的修改请自行学习pug的语法：https://pugjs.org/zh-cn/api/getting-started.html
