### ISSUE TITLE
请问什么时候会出1.6，届时会有什么新功能

### ISSUE THREAD

**Issue by Philchieh** [Molunerfinn/hexo-theme-melody#113]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 
请问什么时候会出1.6，届时会有什么新功能
## Actual behavior 
请问什么时候会出1.6，届时会有什么新功能

## Feature Request

---

**Comment by Molunerfinn** [comment]
时间未定，还在规划功能阶段。
目前的一些规划可以查看project面板：https://github.com/Molunerfinn/hexo-theme-melody/projects/1

**Comment by Molunerfinn** [comment]
目前v1.6版本的基础功能已经基本完成。
@upupming 有没有兴趣提供一份你的KaTeX相关的英文文档 -> https://github.com/Molunerfinn/hexo-theme-melody-doc ?

**Comment by upupming** [comment]
当然，我会尽快加上！

**Comment by Molunerfinn** [comment]
v1.6已经发布，文档也已经更新。
