### ISSUE TITLE
nav background-image undefined 404

### ISSUE THREAD

**Issue by mfkitty** [Molunerfinn/hexo-theme-melody#115]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.5.6

**Platform:** macOS

**Browser:** Chrome

## Expected behavior 

If I set the `top_img: false`, it will not show background image when I go to any page.

## Actual behavior 

It seems that there is no background image displayed, actually load an **undefined** background image.

```
- var top_img = theme.top_img || config.top_img
- var flag = top_img === true ? 'no-bg' : top_img
nav#nav(style=`background-image: url(${top_img})` class=flag)
```

If the top_img is set to false in melody.yml, and there is no value in _config.yml, the `top_img` will be `undefined`. Then it will load this image, but it is not found (404), you can check this error in debug window.

## Steps to reproduce the behavior 

```
# source/_data/melody.yml

top_img: false
```

## Feature Request
I had fixed it, and create a pull request #114.

---

**Comment by Molunerfinn** [comment]
Thank you! You can check my comments on [this](https://github.com/Molunerfinn/hexo-theme-melody/pull/114). 😃

**Comment by Molunerfinn** [comment]
Thank you for your contribution!

**Comment by mfkitty** [comment]
@Molunerfinn 

Wow, merge so fast :smirk:
