### ISSUE TITLE
Local Search Failed

### ISSUE THREAD

**Issue by yondar** [Molunerfinn/hexo-theme-melody#116]
- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.5.6

**Platform:** Windows

**Browser:** Chrome

## Expected behavior
![](https://user-images.githubusercontent.com/12621342/34635853-8404ead0-f2d0-11e7-8feb-936dec267523.png)

## Actual behavior
![](https://s1.ax1x.com/2018/07/12/PKFyp6.png)

I have set config.yml and melody.yml
![](https://s1.ax1x.com/2018/07/12/PKkluD.png)
![](https://s1.ax1x.com/2018/07/12/PKkMjO.png)
but it doesn't work

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/42636132-8bcb4a24-861a-11e8-986b-4a8620eb4e93.png)
Yes, change your settings in site `_config.yml`. Change the search path from `search.xml` to `blog/search.xml`

**Comment by yondar** [comment]
when i change the path, it created another folder and the search still doesn't work
![](https://s1.ax1x.com/2018/07/12/PKAnaj.png)

**Comment by Molunerfinn** [comment]
OK, I will fix this bug.

**Comment by Molunerfinn** [comment]
By the way, what's your root option in your `_config.yml`?
![image](https://user-images.githubusercontent.com/12621342/42637573-247abc7a-861e-11e8-8380-f9b79d9e14b9.png)

**Comment by yondar** [comment]
I set it as /blog/
![](https://s1.ax1x.com/2018/07/12/PKEPw4.png)

**Comment by Molunerfinn** [comment]
If you want to use this feature now, you can switch melody's branch from `master` to `dev`~
Because the next version of melody will not be released so fast.

**Comment by yondar** [comment]
there's a problem that the url is not generated correctly
![](https://s1.ax1x.com/2018/07/13/PKQi7V.png)
there's an extra /blog and escaped %2F
it would jump into 404

**Comment by Molunerfinn** [comment]
@yondar Maybe this is a [bug](https://github.com/wzpan/hexo-generator-search/issues/45) of  `hexo-generator-search`.
