### ISSUE TITLE
关于归档

### ISSUE THREAD

**Issue by Philchieh** [Molunerfinn/hexo-theme-melody#117]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 

我认为归档是用来快速查询某个日期的文章。但是往往需要翻页，这造成了小小的麻烦，能否在新版本中考虑采纳一下我的方案》？

## Feature Request

---

**Comment by Molunerfinn** [comment]
这个是hexo默认生成的页面。
