### ISSUE TITLE
关于标签页与相册

### ISSUE THREAD

**Issue by Philchieh** [Molunerfinn/hexo-theme-melody#119]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 

就是标签页我希望能看到一条完整的标签呈现在同一行

相册页我明明弄了，但是找不到

## Actual behavior 

图片上传不成功，可以点开philchieh.github.io中标签页查看"树状数组&线段树"

## Feature Request

---

**Comment by Molunerfinn** [comment]
在你配置文件里的菜单项里加入相册的地址就行了。文档：https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/theme-config?id=%E5%AF%BC%E8%88%AA%E8%8F%9C%E5%8D%95
相册地址是：https://philchieh.github.io/gallery

标签文本被隔断的问题将会被修复。

**Comment by Philchieh** [comment]
这个主题越来越帅了！！
