### ISSUE TITLE
Why use target="_blank" on archives, categories, and tags pages?

### ISSUE THREAD

**Issue by mfkitty** [Molunerfinn/hexo-theme-melody#120]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.5.6

**Platform:** macOS

**Browser:** Chrome

## Feature Request

Usually we want to open a post in current tab, it's the default behavior and most websites keep this. If really need a new tab, we can press the key: `Ctrl (macOS: CMD)`, then click the link. I think that's a good design because the user has the right to choose, but now it is gone. And I always need to close many new tabs after reading, maybe others also have this confusion.

Here is an article, [When to use target=”_blank”](https://css-tricks.com/use-target_blank/).

If you agree to this, I can send a pull request. :heartbeat:

---

**Comment by mfkitty** [comment]
Done, #121

**Comment by Molunerfinn** [comment]
Thanks a lot!
