### ISSUE TITLE
相册能否实现分类？？

### ISSUE THREAD

**Issue by Philchieh** [Molunerfinn/hexo-theme-melody#123]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 

例如上面是Gallery，下面有次小标题显示风景，动漫之类的。。

感觉作者不厌其烦的答复我的问题

## Feature Request

---

**Comment by Molunerfinn** [comment]
可以啊。你就正常写markdwon再插入相册的标签就行了。。。

```md
## Title 1
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
## Title2
{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
```

**Comment by Philchieh** [comment]
但是体验不是非常好啊？？是我弄错了吗

https://philchieh.github.io/gallery/

`---
title: Gallery
date: 2018-01-05 00:00:00
type: "gallery"
---

## <font color="#06a">$Scenery$</font>

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}

---

## <font color="#06a">$Animation$</font>

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}`

**Comment by upupming** [comment]
`$$` 是 mathjax 的标签，标题应该用 `#`

**Comment by Philchieh** [comment]
Oh,no，不是这个代码，应该是

`
---
title: Gallery
date: 2018-01-05 00:00:00
type: "gallery"
---

## <font color="#06a">$Scenery$</font>

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}

---

## <font color="#06a">$Animation$</font>

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
`

**Comment by Philchieh** [comment]
显示不出来我的代码完整

**Comment by Philchieh** [comment]
```
---
title: Gallery
date: 2018-01-05 00:00:00
type: "gallery"
---

## <font color="#06a">$Scenery$</font>

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}

---

## <font color="#06a">$Animation$</font>

{% gallery https://ws1.sinaimg.cn/large/8700af19gy1fp5i6o2vghj20ea0eajse melody %}
{% gallery https://user-images.githubusercontent.com/12621342/37325500-23e8f77c-26c9-11e8-8e24-eb4346f1fff5.png background %}
```

**Comment by Philchieh** [comment]
应该是上述这个代码@upupming

**Comment by upupming** [comment]
为什么要给 Scenery 加上 `$$` 呢，这样的话 mathjax 对这段字符进行渲染

**Comment by Philchieh** [comment]
但是它是没有换行啊

**Comment by upupming** [comment]
这块样式是有点问题，我会修改一下，请稍等。

**Comment by Philchieh** [comment]
哦哦，好，谢谢您

**Comment by upupming** [comment]
还有一个问题，屏幕宽度缩小之后侧边栏消失，图片被挤压
![screenshot from 2018-07-22 21-28-55](https://user-images.githubusercontent.com/24741764/43046076-75451ee0-8df6-11e8-8860-e1f3fdce1fb3.png)

**Comment by Philchieh** [comment]
嗯嗯

**Comment by Philchieh** [comment]
还有就是能否保留照片原本相对尺寸而非节选成正方形

**Comment by Molunerfinn** [comment]
请尽量使用相册的基本功能。因为本来就不是为了复杂情况设计。
