### ISSUE TITLE
The homepage and some post pages doesn't show because of opacity property

### ISSUE THREAD

**Issue by fxbabys** [Molunerfinn/hexo-theme-melody#125]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.5.6

**Platform:** Windows10

**Browser:** Chrome 67.0.3396.62

## Expected behavior 
Show the pages normally

## Actual behavior 
The home and some post pages doesn't show because of the opacity property

![image](https://user-images.githubusercontent.com/24556921/43566978-dea5e06c-9662-11e8-8740-8eb3a4d96663.png)
![image](https://user-images.githubusercontent.com/24556921/43567087-37b07122-9663-11e8-9be3-16c629daa1d0.png)

## Feature Request

---

**Comment by Molunerfinn** [comment]
Because some js are loading, the animation of the melody will wait for it.

**Comment by fxbabys** [comment]
So is it there anything wrong? I don't know why some posts can load completely but some not.

**Comment by Molunerfinn** [comment]
I don't know so. Could you provide the `console` & `network` panel screenshots of Chrome in the wrong page ?

**Comment by fxbabys** [comment]
Sure, but the console panel shows nothing, here is the network panel:
![image](https://user-images.githubusercontent.com/24556921/43568289-c937f072-9666-11e8-84b2-0d9ab2893f47.png)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/43568438-2774f658-9667-11e8-8749-1ed0527eb4be.png)
It seems that the page don't load the js files. It's strange.

**Comment by fxbabys** [comment]
Could it be a post configuration conflict? I used the next theme previously.

**Comment by Molunerfinn** [comment]
What's your config file for melody? And do you create a `melody.yml` as the docs saying?

**Comment by fxbabys** [comment]
Yes, here is my hexo directorys：
![image](https://user-images.githubusercontent.com/24556921/43569028-e40ebbc2-9668-11e8-89e3-b9b8cd86b73f.png)

**Comment by Molunerfinn** [comment]
I can't reproduce your behavior, and it's normally for other users.
And what's content in your hexo folder's package.json? Take a screenshot.

**Comment by fxbabys** [comment]
![image](https://user-images.githubusercontent.com/24556921/43569326-b34bc84e-9669-11e8-80af-1c645c7d8e57.png)

**Comment by Molunerfinn** [comment]
Please remove `npm remove hexo-render-pug` and then `hexo clean` and then `hexo s` to see.

**Comment by fxbabys** [comment]
The reason is not hexo-render-pug, and I noticed another difference is the whether browsersync message shows, so I aslo tried to remove the hexo-browsersync and it works!

**Comment by fxbabys** [comment]
Maybe the way of its UI render has some conflicts with your theme, you can reproduce as this. And thanks for your solutions!
