### ISSUE TITLE
pug问题

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#127]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**
 window 

**Browser:**

## Feature Request

---

自己自定义了友情链接界面

ejs代码是这样的
```
<div class="post-cards">
<ul class="md-links">
    <% if (site.data.links) { %>
        <% for (var i in site.data.links) { %>
            <li class="md-links-item">
                <a href="<%= site.data.links[i].link %>" title="<%= i %>" target="_blank">
                    <img src="<%= site.data.links[i].avatar %>" alt="<%= i %>" height="72px"/>
                    <span class="md-links-title"><%= i %></span><br />
                    <span class="md-links-des"><%= site.data.links[i].descr %></span>
                </a>
            </li>
        <% } %>
    <% } %>
</ul>
</div>
```

我把其转为PUG
```
div(class="post-cards")
   ul(class="md-links")
      if site.data.links 
         for i in site.data.links
            li(class="md-links-item")
                a(href="!{ site.data.links[i].link }" title="!{ i }" target="_blank")
                    img(src="!{ site.data.links[i].avatar }" alt="!{ i }" height="72px")
                    span(class="md-links-title") !{ i }
                    <br/>
                    span(class="md-links-des") !{ site.data.links[i].descr }
```
会报错
![image](https://user-images.githubusercontent.com/16351105/43763920-9e972d8c-9a5e-11e8-9522-370fb0b0d4f7.png)

我把span(class="md-links-des") !{ site.data.links[i].descr } 注释掉
不会报错
但是生成的界面 
不会去\source\ _data\links 读取资料
![image](https://user-images.githubusercontent.com/16351105/43764036-e98e4276-9a5e-11e8-80d0-17b47efcc936.png)

请问如何解决？
第一次接触pug 看了pug档案 自己还是解决不了

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/43764144-3811b1a8-9a5f-11e8-9136-b91dab8e81be.png)

依葫芦画瓢你可以看看我其他的pug文件是怎么读变量的。在pug里直接用`=`读取变量，只有在pug的script里才用`!{}`来标记变量。

**Comment by jerryc127** [comment]
@Molunerfinn 
谢谢解答
我修改成 直接用 
依旧是唔法读取
```
div(class="post-cards")
   ul(class="md-links")
      if site.data.links 
         for i in site.data.links
            li(class="md-links-item")
                a(href="site.data.links[i].link" title="i" target="_blank")
                    img(src="site.data.links[i].avatar" alt="i" height="72px")
                    span(class="md-links-title") i
                    <br/>
                    span(class="md-links-des") site.data.links[i].descr
```
![image](https://user-images.githubusercontent.com/16351105/43764686-b2d97d98-9a60-11e8-83bf-f5e7fbc1e06f.png)

**Comment by Molunerfinn** [comment]
请仔细阅读pug文档：https://pugjs.org/zh-cn/language/iteration.html
