### ISSUE TITLE
手机浏览器的bug？

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#129]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**
iOS 

**Browser:**
Safari
## Expected behavior 
点击item直接进入界面

## Actual behavior 
需要点击2次item直接进入界面

## Feature Request

---

![img_0428](https://user-images.githubusercontent.com/16351105/43849852-f6fa74c4-9b68-11e8-9984-bbbcfd34bcbb.PNG)

在ios Safari上浏览网站
点击目录
需要点击2次才会进入对应网页
第一次点击 底部会出现横条
![img_0429_cr](https://user-images.githubusercontent.com/16351105/43849901-1dbadb62-9b69-11e8-9dfa-5996f5675292.png)

估计是动画效果导致的

还有几个小问题
1. 生成的public 多了一个 images/jdenticon 是什么东西/什么东西导致？
2. 主题已经自带了文件压缩？

**Comment by Molunerfinn** [comment]
这是hover的效果。不是bug，而是一个feature。你在电脑端拿鼠标摸上去也会有蓝线。



这两个问题的回答是：

1. 不知道，应该是你自己装的插件生成的。
2. 没有，文件压缩是你自己装的插件实现的。主题不带文件压缩。

**Comment by jerryc127** [comment]
感谢回答

没想到是一个feature
电脑端拿鼠标摸上去是会有蓝线
但是这个问题导致手机端原本点击一次itme就能进入对应界面的
现在竟然要点击2次才能进入
看来只能自己去css修改了

**Comment by jerryc127** [comment]
果然是一个bugs
iphone safari hover 问题
已解决
可参考
[iPhone Safari IOS系统不兼容 :hover 的解决方法](https://www.ylefu.com/post/133.html)
