### ISSUE TITLE
gitalk提示Error Not Found

### ISSUE THREAD

**Issue by GreedyPirate** [Molunerfinn/hexo-theme-melody#130]
@Molunerfinn 你好，我在添加gitalk评论系统时遇到一个问题，显示Error Not Found
![image](https://user-images.githubusercontent.com/14834990/43936394-d3b9544e-9c8a-11e8-89df-07954288cf44.png)

打开浏览器控制台，出现js报错如下
![1533869107236](https://user-images.githubusercontent.com/14834990/43936281-77ec6f16-9c8a-11e8-881e-975902ab0aab.jpg)

我自己的github配置如下
![image](https://user-images.githubusercontent.com/14834990/43936307-932f2836-9c8a-11e8-9a9f-93fc69b9f6c5.png)

**Comment by Molunerfinn** [comment]
应该是你的gitalk配置错了。repo不是填你`git clone`的地址，而是填你的repo名称：
![image](https://user-images.githubusercontent.com/12621342/43937493-8d890e14-9c90-11e8-8691-276763495320.png)
另外这个问题你去gitalk的issue里可以看到很多类似的。把你的melody的gitalk的配置的repo改一下。

**Comment by GreedyPirate** [comment]
已解决，配置repo: xxx.github.io，然后部署到线上进行一次初始化，感谢作者

**Comment by appleyuchi** [comment]
@GreedyPirate  请问怎么解决啊，除了_config.yml中设置以外还需要注意什么吗？我的问题依旧，谢谢

**Comment by GreedyPirate** [comment]
> @GreedyPirate 请问怎么解决啊，除了_config.yml中设置以外还需要注意什么吗？我的问题依旧，谢谢

不是在_config.yml里配置，是在source/data/melody.yml里，给你一个参考配置
```
gitalk:
  enable: true
  client_id:xxx
  client_secret: xxx
  repo:tom.github.io
  owner: tom
  admin: tom
```
重新部署一次

**Comment by Biubiuto** [comment]
我没有source/data/melody.yml 这个文件啊

**Comment by GreedyPirate** [comment]
> 我没有source/data/melody.yml 这个文件啊

亲，推荐好好看下文档

推荐把主题默认的配置文件_config.yml复制到 hexo 工作目录下的source/_data/melody.yml，如果source/_data的目录不存在那就创建一个。

**Comment by lefengpiaoling** [comment]
123
