### ISSUE TITLE
feature request: upgrade to Font Awesome Version 5

### ISSUE THREAD

**Issue by Xeonacid** [Molunerfinn/hexo-theme-melody#131]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** v1.5.6

## Feature Request

Font Awesome has upgraded to Version 5. It adds some cool features. Could we upgrade it?
[Upgrading from Version 4](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4) should help.

---

I love hexo-theme-melody! Starred.

**Comment by Molunerfinn** [comment]
I'll check it in few days


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Xeonacid** [comment]
@Molunerfinn Thanks!

**Comment by upupming** [comment]
How about just using the latest version's CDN in your `melody.yml`? Like below:

```yml
# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css
```

The [docs](https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4) says:

> Version 4 just had one prefix — `fa`. Version 5 has four prefixes to let us set the style of any icon easily:

```html
<i class="fa fa-camera-retro"></i>  <!-- version 4's syntax -->

<i class="fas fa-camera-retro"></i> <!-- version 5's syntax -->
<i class="far fa-camera-retro"></i> <!-- example: regular style of camera-retro -->
<i class="fal fa-camera-retro"></i> <!-- example: light style of camera-retro -->
```

I have tested the Version 5, it seems compatible with the icons melody are using. Could I create a pull request for this minor change?

**Comment by Molunerfinn** [comment]
@upupming Sure!

**Comment by Xeonacid** [comment]
Great, thank you all!
