### ISSUE TITLE
不支持MARKDOWN TODO寫法？

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#133]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**
window

**Browser:**

## Feature Request

---

不支持MARKDOWN TODO寫法？
試了用- [x] 發現不起作用

**Comment by Molunerfinn** [comment]
这个不是主题的问题，是渲染器的问题


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jerryc127** [comment]
@Molunerfinn  這是哪個插件的渲染？

**Comment by Molunerfinn** [comment]
@jerryc127 不知道，你可以谷歌一下


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by jerryc127** [comment]
@Molunerfinn  我查了 hexo-renderer-marked 已經支持了
但是不知道這個主題是哪個插件去渲染markdown的

**Comment by Molunerfinn** [comment]
@jerryc127 主题不负责渲染markdown…只负责给渲染后的markdown加样式。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/44209692-ce1d6780-a196-11e8-9c9a-8ed1c13cb616.png)
我试了一下用`hexo-renderer-marked`是可以的。

写法：
```markdown
- [ ] 123
- [x] 123
```
注意空格。
