### ISSUE TITLE
添加密码页？添加音乐引用？

### ISSUE THREAD

**Issue by Philchieh** [Molunerfinn/hexo-theme-melody#141]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 

添加密码页？添加音乐引用？

## Feature Request

---

**Comment by Molunerfinn** [comment]
音乐引用自行添加。密码页不存在的，hexo是静态博客。

**Comment by Philchieh** [comment]
置顶功能呢？？

**Comment by Molunerfinn** [comment]
可以考虑实现。

**Comment by Philchieh** [comment]
谢谢您
