### ISSUE TITLE
置顶文章

### ISSUE THREAD

**Issue by trover-gaoyou** [Molunerfinn/hexo-theme-melody#143]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:*1.5.4*

**Platform:*Ubuntu 18.04*

**Browser:*Chrome*

## Feature Request

---使用`npm install hexo-generator-index-pin-top --save` 并且在文章头部添加了`top: true`，不过我无法在`recent-posts.pug`里面添加**置顶**标志。期待解决。

**Comment by Molunerfinn** [comment]
已解决。预览图：

![image](https://user-images.githubusercontent.com/12621342/44832447-77676180-ac5d-11e8-9145-c8880bfb44f9.png)

**Comment by stevenjoezhang** [comment]
Hexo 已实现文章置顶参数： https://github.com/hexojs/hexo-generator-index/pull/51
