### ISSUE TITLE
目录框，站点概述问题

### ISSUE THREAD

**Issue by Philchieh** [Molunerfinn/hexo-theme-melody#144]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Actual behavior 

希望可以支持目录框，站点概述的背景，不然觉得单调，谢谢

## Feature Request

---

**Comment by Molunerfinn** [comment]
不打算支持，谢谢。


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
