### ISSUE TITLE
如何设置正文字体大小

### ISSUE THREAD

**Issue by Philchieh** [Molunerfinn/hexo-theme-melody#145]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 

如何设置正文字体大小

## Feature Request

---

**Comment by Molunerfinn** [comment]
自行修改CSS


 :octocat: [From gitme iOS](http://flutterchina.club/app/gm.html)
