### ISSUE TITLE
文章底部版权文章链接适配问题

### ISSUE THREAD

**Issue by klauspeng** [Molunerfinn/hexo-theme-melody#146]
移动端如果文章链接长些的话，会出现页面可左右晃动的情况
![文章底部版权文章链接适配问题](http://otfiq2zfh.bkt.clouddn.com/static/images/post-copyright-link.png)

不知在哪里加个样式可以解决？多谢！

**Comment by Molunerfinn** [comment]
@klauspeng 收到，这是个bug，会尽快解决。另外你发issue的时候注意按照模板发。
