### ISSUE TITLE
Local search is missing in Chrome69.0.3497.81

### ISSUE THREAD

**Issue by klauspeng** [Molunerfinn/hexo-theme-melody#148]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:master**

**Platform:**

**Browser:Chrome69.0.3497.81**

## Expected behavior 
Local search
## Actual behavior 
Local search is missing in Chrome69.0.3497.81

## Feature Request

---

**Comment by Molunerfinn** [comment]
R U Kidding me?
![image](https://user-images.githubusercontent.com/12621342/45588169-cb06ca00-b942-11e8-9522-30ead13c34f6.png)
![image](https://user-images.githubusercontent.com/12621342/45588173-d5c15f00-b942-11e8-8d0e-6d32550b8650.png)

**Comment by klauspeng** [comment]
Sorry, it is Adblock Plus！
![](http://otfiq2zfh.bkt.clouddn.com/static/images/bug/1.png)
![](http://otfiq2zfh.bkt.clouddn.com/static/images/bug/2.png)
