### ISSUE TITLE
The display problem in Chrome for Linux

### ISSUE THREAD

**Issue by Floral** [Molunerfinn/hexo-theme-melody#149]
## The display problem in Chrome for Linux  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:Linux**

**Browser:Chrome**

## Expected behavior 
display normally just as we expect
## Actual behavior 
the search bar displays in the button of the whole page

![tim 20180915150100](https://user-images.githubusercontent.com/36479261/45587651-3d73ac00-b93b-11e8-85b2-69e8209e88d9.jpg)

## Feature Request

---

**Comment by Molunerfinn** [comment]
I don't have Linux browser. As my Mac Chrome & Windows Chrome is working well.

![image](https://user-images.githubusercontent.com/12621342/45588187-2e90f780-b943-11e8-9c62-fdd42593b9f2.png)

**Comment by Floral** [comment]
> I don't have Linux browser. As my Mac Chrome & Windows Chrome is working well.
> 
> ![image](https://user-images.githubusercontent.com/12621342/45588187-2e90f780-b943-11e8-9c62-fdd42593b9f2.png)

Okay...
