### ISSUE TITLE
Version 1.4 Features

### ISSUE THREAD

**Issue by Molunerfinn** [Molunerfinn/hexo-theme-melody#15]
Thanks for many developers' help, after version 1.3, theme-melody have fixed many bugs and have some new features.

For the version 1.4, I want to add some new features to it. The followings are my plans, maybe you have some ideas, welcome to discuss with me!

- the [laibili comment system](http://www.laibili.com.cn/)
- the [gitment comment system](https://github.com/imsun/gitment)
- the advertisement or poster place for users

Thank you for choosing the theme-melody, I will make it more beautiful & powerful

**Comment by Molunerfinn** [comment]
Pin: the [jiathis](http://www.jiathis.com/)share system

**Comment by WincerChan** [comment]
jiathis support https is not good,and look bad. you can try [share.js](https://github.com/overtrue/share.js/)

**Comment by Molunerfinn** [comment]
@WincerChan Nice, I will support it in the version 1.4

**Comment by Molunerfinn** [comment]
Done.
