### ISSUE TITLE
Cannot customize favicon in project pages 

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#151]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.5.6

**Platform:** Any

**Browser:** Any

## Expected behavior 

I have a [project page](https://upupming.site/Lab1-polynomial-curve-fitting/README.html). Usually, I want it to use my blog's `favicon.ico` located at my blog's sorce folder, i.e., [`/source/favicon.ico`](https://github.com/upupming/upupming.github.io/tree/source/source#8af3a74ede48e250ceb935c026242483-46d0eb10aa750de9ccc5de3cfce5377688ffc89c) even I didn't declare my favicon path in the html file.

## Actual behavior 

The project page will use the favicon from the theme's source folder.

![image](https://user-images.githubusercontent.com/24741764/46194810-0a66ea80-c335-11e8-8f46-decde13fb3ae.png)

Could we change the name of `favicon.ico` to something like`favicon.ico.example`, so the user has the right to choose their own favicon instead of being overwritten by this favicon?

## Steps to reproduce the behavior 

1. Create a simple project page in GitHub project settings.
2. Go to the page you created and the favicon will be the theme's favicon.

## Feature Request

---

**Comment by Molunerfinn** [comment]
Just put your `favicon.ico` to your blog's `source` folder will be OK. It won't change the code of melody and will overwrite the default `favicon.ico` which is supported by melody after you run `hexo g`.

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/46196234-0b018000-c339-11e8-9d77-93a593dc4210.png)
![image](https://user-images.githubusercontent.com/12621342/46196248-12288e00-c339-11e8-9212-fe125b515cb0.png)

**Comment by upupming** [comment]
Thanks for your advice, but after I add the favicon to my blog's root directory and run `hexo g`, the `favicon.ico` is still generated from the theme's `/source` folder:

![image](https://user-images.githubusercontent.com/24741764/46197153-86fcc780-c33b-11e8-9fe9-7957a448fea2.png)

![image](https://user-images.githubusercontent.com/24741764/46197192-a4319600-c33b-11e8-829e-f77331eac93c.png)

**Comment by Molunerfinn** [comment]
@upupming Delete the public folder before you run `hexo g` or it will not be generated correctly.

**Comment by upupming** [comment]
Tried:

```sh
$ hexo clean
$ rm -r public
$ hexo g
```

But still not working, it's strange.

**Comment by Molunerfinn** [comment]
@upupming That's strange... I have generated the default `favicon.ico` randomly. It seems the bug of the hexo generator. OK I will change the default `favicon.ico` to `melody-favicon.ico` so that your problem will be easy to solve.

**Comment by Molunerfinn** [comment]
And if you use the `dev` branch of melody, you need to checkout [this](https://github.com/Molunerfinn/hexo-theme-melody/issues/150).

**Comment by upupming** [comment]
Thanks, maybe we should update the Gitalk, too. I will have a test on the latest gitalk.

**Comment by Molunerfinn** [comment]
User can update the Gitalk by change the js in `melody.yml`.

**Comment by upupming** [comment]
Thanks for all these nice updates. 👍  

To use the latest gitalk is okay, too. Redirecting looks good to me now:
![gitalk](https://user-images.githubusercontent.com/24741764/46201109-f7104b00-c345-11e8-87fc-9d848f1f6fb5.gif)

**Comment by JiajunBao** [comment]
Guys, how did you solve the favicon issue? I am running into the same issue.
