### ISSUE TITLE
layout.pug config.email is not exists

### ISSUE THREAD

**Issue by iamwwc** [Molunerfinn/hexo-theme-melody#154]
## I want to create a new issue 

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
"version": "1.5.6",

**Platform:**
Windows10 Pro 1803

**Browser:**
Chrome

## Actual behavior 

`config.email is undefined`

I found same problem in `https://molunerfinn.com/` head area
There not config.email exists.

Same issue exists in `master` and dev `branch`

The problem maybe in [MasterBranch-Layout](https://github.com/Molunerfinn/hexo-theme-melody/blob/master/layout/includes/layout.pug#L13)

Did you decide to remove it or add email config?

![image](https://user-images.githubusercontent.com/24750337/46782883-90822880-cd5a-11e8-85d5-fdca1c62d5aa.png)

**Comment by Molunerfinn** [comment]
Oh, the email config is the hexo config not the melody config.
So I forgot to set the email in the hexo's `_config.yml`.  Thanks for reporting this. I have fix this problem.

After the fix, you won't see `undefined` if you don't set the email.
