### ISSUE TITLE
a typo in document

### ISSUE THREAD

**Issue by comwrg** [Molunerfinn/hexo-theme-melody#156]
https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/third-party-support?id=%E8%AF%84%E8%AE%BA%E7%B3%BB%E7%BB%9F

![image](https://user-images.githubusercontent.com/19854253/47722271-ffcda700-dc8c-11e8-9f07-d0f32803035e.png)

**Comment by Molunerfinn** [comment]
@comwrg Thanks a lot! I have fixed this error.
