### ISSUE TITLE
bug 反馈

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#158]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**
window

**Browser:**

## Expected behavior 
显示正常

## Feature Request

---

markdown上这样
![image](https://user-images.githubusercontent.com/16351105/48494674-53351d00-e869-11e8-86f6-0cb69ce7eea5.png)
但是渲染出来的效果是 --变成 -
![image](https://user-images.githubusercontent.com/16351105/48494711-6647ed00-e869-11e8-90d0-b6752ff3d999.png)
这bug怎么解决

**Comment by Molunerfinn** [comment]
主题不负责渲染具体的内容，只负责样式。这个你需要到你所用的hexo的markdown渲染器的github仓库去询问。
