### ISSUE TITLE
提示“extends includes/layout.pug block content include includes/recent-posts.pug include includes/pagination.pug”

### ISSUE THREAD

**Issue by andyvoice** [Molunerfinn/hexo-theme-melody#16]
按着说明文档装好了主题及依赖，hexo的主题配置改为melody，无论通过hexo clean,hexo g 或是 hexo clean,hexo s ，访问站点总显示“extends includes/layout.pug block content include includes/recent-posts.pug include includes/pagination.pug”，就显示这一句话，请问是什么问题

**Comment by Molunerfinn** [comment]
无法复现你的bug。请确保你的hexo目录下的package.json里的依赖是否完备。
这是我的hexo目录下的package.json。仅供参考：
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.8"
  },
  "scripts": {
    "dev": "hexo s -p 3600 -o"
  },
  "dependencies": {
    "hexo": "^3.3.8",
    "hexo-browsersync": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^2.1.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^3.0.2"
  }
}
```
请删除node_modules/文件夹，然后再重新`npm install`一遍。安装完依赖之后执行一下`npm run dev`，开启调试模式，看看是不是还有问题。如果没有问题，那么有可能是你全局的hexo出问题了。请卸载全局的hexo重新安装一遍

**Comment by andyvoice** [comment]
I have fixed the problem ，我没有严格按着说明指示操作造成的，谢谢

**Comment by iGoo** [comment]
我更换后也出现这个提示。

**Comment by Molunerfinn** [comment]
@iGoo 请仔细阅读文档，我发现这是你没有装pug和stylus编译器的结果
https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/quick-start
