### ISSUE TITLE
建议top_img能把footer区域也展示

### ISSUE THREAD

**Issue by itboyer** [Molunerfinn/hexo-theme-melody#160]
首先对该主题表示支持，很简洁，比next主题修改精简很多
建议：
1. top_img能把footer区域也同时展示
2. 鼠标点击动画，能丰富一下，支持自定义js
3. 自动摘录功能，不带换行，显示效果有点差，目前使用标签自定义控制
我自己简单修改了一下，效果见https://itboyer.github.io
也作者期望能把我的博客链接加入文档中的推荐Demo中

**Comment by Molunerfinn** [comment]
1. 后续考虑加入footer_img选项用于配置footer的图片。因为footer区域比header小，所以有可能需要不同的背景图。
2. 点击动画的js你可以通过配置文件里的`cdn->js`选项里加入所需js或者自己写的js即可。不想要主题自带的fireworks的点击效果把fireworks置成false就行。
3. 自动摘录你的实现感觉挺不错的，可以考虑提一个PR或者提供一下实现思路么？如果可以的话是最好了。后续会把DEMO Links统一到WIKI里，届时也会把你的博客加入其中。当然如果现有链接里的博客不再能访问或者不再用这个主题的我也会撤下换成你的。

PS: 下次发issue的时候还是请注意一下格式，否则会被直接关闭。

**Comment by itboyer** [comment]
原本想通过您的博客回复，提建议沟通，后来发现您那边没开通留言功能，就冒昧的使用了issues，而且没仔细阅读您设置的额格式要求，十分抱歉。
1. 对于footer_img，个人感觉没必要单独定义出这个变量，如果一个页面控制两张图的话，还要考虑图片配色风格的一直性，目前我是用的top_img变量的URL设置的footer区域的背景，然后使用bottom定位，这样图片的top和footer像是一张图，被中间文字内容截成了两部分。
2. 对于点击动画，目前我是自己使用的js加载的，学习到了配置文件这种修改方式，也很感谢
3. 自动摘录的实现，我目前使用的是您文档中提到的的`<!-- more -->`标签，手动控制的。我个人是做后端开发的，对前端技术了解的不够深，作为一个外行，我这边有个不成熟的想法`使用固定高度的div，设置自动摘录的显示高度，然后通过瀑布流懒加载的方式，只加载这个div大小的页面内容`，不知是否具有可行性。

最后再次感谢对于我个人不符合规范的使用issues页面的通融，考虑到该页面的统一要求，阅读完本次回复后，对于本页面的关闭和删除，都表示理解和支持！

**Comment by Molunerfinn** [comment]
其实是开了的，我用的disqus，所以你需要翻墙访问。

嗯，关于footer_img的问题我还会再调研，你的做法我觉得挺不错可以借鉴。

摘录这个我自己用的也是手动通过`<!-- more -->`标签实现的，主题也提供了两种方式，一种是自动的一种是手动的。手动的这种是hexo官方推荐的。自动的我也只能做到读原本的文本做截取。你说的那种可行性不高，因为渲染是在后端进行的，无法确认高度对应的文本量以及相应的懒加载。

**Comment by guyueshui** [comment]
冒昧提一句可以考虑一下自定义字体吗？我是个新手，不知道这样提意见合不合规矩，请见谅！

**Comment by Molunerfinn** [comment]
@guyueshui https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/source/css/var.styl#L23
字体设置在这里，自行修改。请顺便补充一些CSS字体相关知识。

**Comment by guyueshui** [comment]
非常感谢你的回复。还有个问题，主题的版权页的作者一项，有一个mailto的链接不知道在哪里设置？我到你的博客下发现也是undefined，所以问一下是否已经解决？冒昧打扰，还请见谅。
![2018-12-27-222630_853x130_scrot](https://user-images.githubusercontent.com/12670826/50483375-881abf00-0a26-11e9-9396-3b0040525a99.png)
