### ISSUE TITLE
wordcount 无法使用（已经正常安装了模块）

### ISSUE THREAD

**Issue by brick713** [Molunerfinn/hexo-theme-melody#162]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
dev 

**Platform:**
linux centos7

**Browser:**
chrome
## Expected behavior 
wordcount:
  enable: true
## Actual behavior 
ERROR /opt/Blog/themes/melody/layout/post.pug:33
    31|             .post-meta-wordcount
    32|               span= _p('post.wordcount') + ': '
  > 33|               span.word-count= wordcount(page.content)
    34|               span.post-meta__separator |
    35|               span= _p('post.min2read', min2read(page.content, {cn: 350, en: 160}))
    36|   else

wordcount is not a function
TypeError: /opt/Blog/themes/melody/layout/post.pug:33
    31|             .post-meta-wordcount
    32|               span= _p('post.wordcount') + ': '
  > 33|               span.word-count= wordcount(page.content)
    34|               span.post-meta__separator |
    35|               span= _p('post.min2read', min2read(page.content, {cn: 350, en: 160}))
    36|   else

wordcount is not a function
    at eval (eval at wrap (/opt/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:870:57)
    at template (eval at wrap (/opt/Blog/node_modules/pug-runtime/wrap.js:6:10), <anonymous>:2098:72)
    at _compiled.locals [as _compiled] (/opt/Blog/node_modules/hexo/lib/theme/view.js:125:48)
    at View.render (/opt/Blog/node_modules/hexo/lib/theme/view.js:30:15)
    at route.set (/opt/Blog/node_modules/hexo/lib/hexo/index.js:394:29)
    at tryCatcher (/opt/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /opt/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/opt/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:741:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

## Steps to reproduce the behavior 
![image](https://user-images.githubusercontent.com/5291873/49993363-6995dc00-ffc1-11e8-8ffa-c2dae7a559af.png)
正常安装了模块，但是还是报错，尝试 hexo clean 之后重新 generate，还是不行
## Feature Request

---

**Comment by brick713** [comment]
version 1.5.6

**Comment by Molunerfinn** [comment]
你`opt/Blog`目录下结构是啥？我这边测试是没问题的。

**Comment by Molunerfinn** [comment]
提供一下你的`opt/Blog`下的`package.json`

**Comment by Molunerfinn** [comment]
你这个报错是`hexo-wordcount`没有正确安装所以`wordcount`这个方法没有注入到hexo的generator里。查看一下你的`Blog`目录下的`package.json`里有没有`hexo-wordcount`。如果没有你可能需要手动加上。附上我测试的`package.json`：

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.4.0"
  },
  "scripts": {
    "dev": "hexo s -p 3600 -o"
  },
  "dependencies": {
    "hexo": "^3.3.9",
    "hexo-algoliasearch": "^0.2.1",
    "hexo-browsersync": "^0.2.0",
    "hexo-cli": "^1.0.4",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index-pin-top": "^0.2.2",
    "hexo-generator-search": "^2.2.5",
    "hexo-generator-tag": "^0.2.0",
    "hexo-inject": "^1.0.0",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-kramed": "^0.1.4",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0",
    "hexo-wordcount": "^6.0.1",
    "markdown-it-katex": "^2.0.3"
  }
}
```

**Comment by Molunerfinn** [comment]
我猜测是你用npm装的时候没有加上`--save`的标识，所以你安装的插件没有写入`package.json`。hexo的插件机制是先去`package.json`里读里面的依赖，把插件名先抽出来再一个个加载。所以如果你`package.json`里没有`hexo-wordcount`，哪怕你`node_modules`里有了也没用。

所以推荐还是用`yarn add hexo-wordcount`来装，会自动写入`package.json`。

官方的安装方式也是有加`--save`的：

![image](https://user-images.githubusercontent.com/12621342/49994503-a31c1680-ffc4-11e8-8697-5ce75928236e.png)

重新排查一下应该就没问题了。
