### ISSUE TITLE
addThis dosen't work

### ISSUE THREAD

**Issue by andyvoice** [Molunerfinn/hexo-theme-melody#17]
我配置好了addThis，但没看到分享的任何图标被显示，hexo server也没有报任何错误，请问怎么处理？

**Comment by Molunerfinn** [comment]
addThis 只在post文章页内出现。并且只在文章末尾，评论区上方出现
![image](https://user-images.githubusercontent.com/12621342/33792549-36a4c628-dcde-11e7-901c-509ec00538bb.png)
addThis的服务并不是很稳定，在国内有被墙的可能。
所以请检查如下：
1. 你的pub-id是否正确？通常的格式是`ra-xxxxxxxxxxxx`
2. 是否查看了非post文章页？那些页面是没有的
3. 推荐采用inline（横向模式）
4. 检查浏览器Network，看看addThis的JS请求是否被墙或者是否发送错误（如果发送错误很可能是你的pub-id输错了）
5. 修改了配置文件之后需要重新启动一遍hexo server。hexo server不支持动态监听配置文件

**Comment by andyvoice** [comment]
我单独写了一个html其中放了addthis提供的code，也没有显示分享图标。请问如果我用jiathis可以怎么做？

**Comment by Molunerfinn** [comment]
1.3版本暂不支持jiathis。1.4版本可以考虑加入。jiathis的代码和使用官方给的很全面了。只需要你自己加在addthis同样的位置就行。
如果你自己写了html放了addthis的代码还没有生效，请确认一下你的addthis自己定制的分享面板是否保存了。如果没有保存，就算有代码也没用。另外再次查看你的addthis的js请求是否被墙。
我这边无法复现你的问题，非常抱歉。
