### ISSUE TITLE
长文件显示空白页面

### ISSUE THREAD

**Issue by 40m41h42t** [Molunerfinn/hexo-theme-melody#171]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
master 和 dev 版本都尝试过了

**Platform:**
Windows

**Browser:**
Chrome

## Expected behavior 
长文章正常显示

## Actual behavior
长文章未正常显示，页面一片空白，左下角有不可点标志，`hexo g` 正常执行。

![](https://ws1.sinaimg.cn/large/79b6884ely1fzeo8pnez7j21hc0pc3yk.jpg)

## Steps to reproduce the behavior
本来以为是某些 js 的问题，仔细一想自己并没有改太多的东西，将文章中的部分内容删除之后显示正常，如图所示，我的文章有 3486 词，452 行，12851 字符的时候页面是空白，我删去部分内容，3242 词，440 行，12511 字符的时候就可以正常显示。
![](https://ws1.sinaimg.cn/large/79b6884ely1fzeoebdzqfj21ha0p9447.jpg)

## Feature Request
嗯。。这我就不懂了。。究竟是哪里出的问题呢？

---

**Comment by upupming** [comment]
https://github.com/Molunerfinn/hexo-theme-melody/issues/57

**Comment by 40m41h42t** [comment]
感谢，另外请问一下将 hexo 升级到最新版本会解决这个问题吗？

**Comment by Molunerfinn** [comment]
> 感谢，另外请问一下将 hexo 升级到最新版本会解决这个问题吗？

应该不会，这个是hexo-server的问题
