### ISSUE TITLE
The top of the article page code block does not display properly. (Looks like a bug)

### ISSUE THREAD

**Issue by JunzhouLiu** [Molunerfinn/hexo-theme-melody#174]
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
Branch：dev dd6e54f  

**Platform:**
Windows 10.0.17763.253

**Browser:**
Chrome 70

## Actual behavior 
The top of the article page code block does not display properly. (Looks like a bug)

![image](https://user-images.githubusercontent.com/17582066/51959703-a134e680-2490-11e9-9464-544ac15b2cd2.png)
 Original content
![image](https://user-images.githubusercontent.com/17582066/51959848-46e85580-2491-11e9-8426-418d932b8dde.png)
## Steps to reproduce the behavior 
No
## Feature Request
No

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/51962135-03461980-249a-11e9-8973-0a1c4e740407.png)

**Comment by JunzhouLiu** [comment]
There are still some minor problems，The text at the top left of the code block is located on line 1 of the code area. (I think this is a bug, not a new feature， waiting for your confirmation)

![image](https://user-images.githubusercontent.com/17582066/51978440-289c4d00-24c5-11e9-9a8d-f15c8e1a7075.png)

**Comment by Molunerfinn** [comment]
Hmmm... Although this is a bug, I don't recommend that you write too long after ```, which is a disaster for any theme. I will try to fix this bug.

**Comment by JunzhouLiu** [comment]
I just switched from the NexT theme to the melody theme. Some of the original article content has not changed (continuing the use of the NexT theme), so this error is displayed.

**Comment by JunzhouLiu** [comment]
I am sorry, I don't know much about the front end of the webpage, so I can't provide useful Pull Request for Melody.

**Comment by Molunerfinn** [comment]
@JunzhouLiu Now try again~ It's a bug, but still, I don't recommend that you write too long after ```. Because it will let the style of `figurecaption` in the code block out of control. For example, in your PC the style is OK while on the mobile it won't be nice.

For best practice you can write the information out of the code block:

```md
> 代码位置 ~xxx/xx/xx/xxx
// .... code block
```

**Comment by JunzhouLiu** [comment]
I'm trying now .
This is NexT theme code block style . For your reference （soory my English  not good）
![image](https://user-images.githubusercontent.com/17582066/51979953-7fa42100-24c9-11e9-852e-a1174da11ba4.png)

![image](https://user-images.githubusercontent.com/17582066/51979879-466bb100-24c9-11e9-9147-78b5996ba758.png)

**Comment by Molunerfinn** [comment]
@JunzhouLiu Yes, in Next's structure it's OK. but Next doesn't have the `code-bar` for displaying the type of language and the `copy` button :smile:

**Comment by JunzhouLiu** [comment]
OK It’s working now .:beers: :beers:
