### ISSUE TITLE
The main body of page is black in steam built-in browser.

### ISSUE THREAD

**Issue by Sheey11** [Molunerfinn/hexo-theme-melody#175]
- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.5.6.

**Platform:** Windows 10.

**Browser:** Steam built-in browser.

![op1 6 jw v96gqxqr14ezo](https://user-images.githubusercontent.com/13375959/52462045-704d6380-2bac-11e9-8232-e5c1d3fa1b7e.png)

All the main body of the page is black, it should be white.

Browser should be Chromium core, but since there's no dev tool, I have no idea why it goes wrong.

**Comment by Molunerfinn** [comment]
Default browser's background-color is white. So I didn't set background-color for body.
Steam's built-in browser's background-color is black.
I will fix this. You need to change to dev branch.
