### ISSUE TITLE
首页图片显示bugs?

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#176]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 
图片显示正常

## Feature Request

---

去了apple store测试了一下
发现首页图片在新ipad pro 11寸跟12.9寸两个版本显示有问题
如你的网页显示是这样的
![img_0480](https://user-images.githubusercontent.com/16351105/52652879-db3ec780-2f29-11e9-8372-97c9444b76f5.JPG)
图片显示不出（应该说不完整）
试了自己的blog 也是这种情况
不清楚是不是Bugs

在高分辨率下（用了apple store 出售的2款lg屏幕 4k 跟5k)
发现首页图片的高度很小
导致图片只显示一半

**Comment by Molunerfinn** [comment]
在iPad-Pro上显示的时候会有问题估计是一个CSS属性在safari上不支持的问题。这个我之后会看看跟进一下。
在4K\5K屏背景显示高度问题是因为分辨率太高了，背景图的高度有限，为了不让背景图变形，背景的宽度依然会跟随分辨率走，但是给背景图区域的高度是固定高度的所以就会感觉显示不全。建议是在4K\5K的情况下调整分辨率。目前来说并没有针对太高分辨率适配的计划。因为这个主题本身不是为了高分辨率设计和展示的，是为了个人博客使用的。如果你要在高分辨率下使用，一般也会调整缩放比例的。
