### ISSUE TITLE
与 hexo-tag-aplayer 样式的冲突

### ISSUE THREAD

**Issue by Sheey11** [Molunerfinn/hexo-theme-melody#179]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** v1.6.1 (lastest `master`)

**Platform:** Windows

**Browser:** Chrome

## Actual behavior 

好的又是我, 我又来了  
这次是和 [hexo-tag-aplayer](https://github.com/MoePlayer/hexo-tag-aplayer) `css`的冲突.  
`aplayer` 大概是这样子的:  
![](https://user-images.githubusercontent.com/13375959/53680784-06435c80-3d1b-11e9-8c3f-62890eea2cb7.png)
注意播放列表左边的粉红色竖条, 那个是 `aplayer` 自带的.  
但是圆圈序号123就是`melody`的`css`了.  
大佬修复 bug 超级辛苦, 我就把这部分的`html`放上来, 不麻烦大佬再装一遍 plugin 了.  
```
<li class="aplayer-list-light">
    <span class="aplayer-list-cur" style="background-color: #ff7a9e;"></span>
    <span class="aplayer-list-index">1</span>
    <span class="aplayer-list-title">ダーリン</span>
    <span class="aplayer-list-author">XX:me</span>
</li>
```
要是不清楚就只能麻烦大佬去试试插件了, 我的前端超级渣的QAQ.  
辛苦啦!

**Comment by Molunerfinn** [comment]
给个可访问的网址我看看

**Comment by Molunerfinn** [comment]
插件样式被melody的默认覆盖是不可避免的，只能手动自己再写样式来把插件的样式改回去。所以这个其实不能算是melody的bug。插件千千万，不可能做到兼顾一切插件的样式而不冲突的。所以需要理解。目前来说你要提供一个可访问的、可复现的页面，不然光看你的HTML结构也是没用的。

**Comment by Sheey11** [comment]
呀, 不好意思刚才出去了
在这里: 
https://sheey.moe/2019/03/02/%E6%94%AF%E6%8C%81HTTPS%E5%95%A6/

**Comment by Molunerfinn** [comment]
```styl
#content-inner .aplayer-list ol>li:before
  content none
```
把这部分代码加到你的这个文件的这个地方就行了。以后类似的问题将不再回答，你需要自己学习CSS相关知识，否则我也无法每次都有时间帮你解决定制化的问题。
https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/source/css/index.styl#L13

**Comment by Sheey11** [comment]
好吧, 不过还是谢谢
