### ISSUE TITLE
如何修改 top-img的高度？如何修改 站点又上角的那排文字的大小？

### ISSUE THREAD

**Issue by andyvoice** [Molunerfinn/hexo-theme-melody#18]

**Comment by Molunerfinn** [comment]
对应的CSS文件都在`source/css`文件夹里。找到对应的class或者id修改CSS即可。

**Comment by Molunerfinn** [comment]
修改样式请系统学习CSS。恕无法为你的每个样式修改都提供帮助。
[CSS 教程](http://www.runoob.com/css/css-tutorial.html)

**Comment by andyvoice** [comment]
我知道可以改CSS，只是变量太多了，不知道改哪个？：）

**Comment by Molunerfinn** [comment]
需要学会用浏览器查看元素来调试。
top_img 的高度是由`#site-info`的padding值撑开的。
![image](https://user-images.githubusercontent.com/12621342/33801659-e531b5c0-dd9c-11e7-8dfa-19391928481a.png)
右上角的字体大小修改`.site page`的`font-size`大小即可。
![image](https://user-images.githubusercontent.com/12621342/33801665-2fdd7fa0-dd9d-11e7-93b3-7054c92d5946.png)
以后这类问题概不回答~
