### ISSUE TITLE
The copy button of indented code blocks is not displayed properly

### ISSUE THREAD

**Issue by sqd** [Molunerfinn/hexo-theme-melody#180]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
melody: v1.6.1
hexo: 3.8.0

**Platform:**
macOS 10.14.3
node: v11.7.0

**Browser:**
Chrome 72.0.3626.119
## Expected behavior 
The icon stay within the code block's boundary.
## Actual behavior 
It goes outside of the code block.
![image](https://user-images.githubusercontent.com/4945180/53773850-49333a80-3ea9-11e9-8fb4-4b5fe01d0326.png)

## Steps to reproduce the behavior 
I can zip my hexo directory if that would help. [Here](https://sqd.github.io/2019/03/04/ghc-notes-1/#GHC-Core) is the post in the screenshot on my site.
Changing browser window size doesn't help. It happens on mobile as well.
Could be related to #100

**Comment by Molunerfinn** [comment]
I'll see and fix it soon

**Comment by Molunerfinn** [comment]
I would be very grateful if you could give a star! 😄

**Comment by sqd** [comment]
That was fast! Will star and thank you for your work.
