### ISSUE TITLE
代码复制bugs?

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#181]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
最新

**Platform:**
ALL

**Browser:**

## Feature Request

---

复制代码出现的“复制成功”提示，在代码过长时，出现滚动条，滚动条滚动，代码提示出现的位置会开始偏移，滚动条滑动越往右，提示越往左偏移。如图所示
![image](https://user-images.githubusercontent.com/16351105/53886860-f948a500-405b-11e9-8c62-4021f87002f9.png)
![image](https://user-images.githubusercontent.com/16351105/53886881-01084980-405c-11e9-9707-686ffb65f9fc.png)
![image](https://user-images.githubusercontent.com/16351105/53886930-167d7380-405c-11e9-94d0-a689d5f86094.png)

**Comment by JunzhouLiu** [comment]
@jerryc127 这个代码好眼熟。。。

**Comment by jerryc127** [comment]
> @jerryc127 这个代码好眼熟。。。

哈哈 你的網站截圖的

**Comment by JunzhouLiu** [comment]
> > @jerryc127 这个代码好眼熟。。。
> 
> 哈哈 你的網站截圖的

嗯嗯呢，早点睡哈，我要关机上床啦

**Comment by jerryc127** [comment]
原來前幾天的更新 已經解決這個問題啦
