### ISSUE TITLE
关于中文

### ISSUE THREAD

**Issue by andyvoice** [Molunerfinn/hexo-theme-melody#19]
我把hexo _config.yml中的语言设置为中文，又把melody.yml中的语言设置为中文，但站点右上角的Home、Achieves等都没有变成中文，zh-Hans.yml确实存在，请问可能是什么问题

**Comment by Molunerfinn** [comment]
主题配置文件里，把menu项下的属性改为中文：
```yml
menu:
  主页: /
  关于: /about
  归档: /archives
  ...
```

**Comment by andyvoice** [comment]
了解这种做法，不过不是应该自动翻译吗？

**Comment by Molunerfinn** [comment]
不是的，这个菜单项是自己定义的。不一定是固定的。所以没办法生成语言文件。

**Comment by ZhangYanTJU** [comment]
@Molunerfinn 你好，我使用的是中文，然后顶部的那些分类，归档之类的，都是正常显示中文（按照您在二楼的做法）。但有时候，部署之后，网站的侧边栏 sidebar?（即文章、标签、分类，并且右侧显示数量的那个）有一定概率变成英文的，有时候又是中文的。

**Comment by Molunerfinn** [comment]
@ZhangYanTJU 不会有概率的。侧边栏的显示是根据你的hexo配置的语言来的。不是melody的语言配置，而是hexo的语言配置。
![image](https://user-images.githubusercontent.com/12621342/40575041-127d6a78-6110-11e8-93f8-10dec13b5ba4.png)

**Comment by ZhangYanTJU** [comment]
@Molunerfinn 哦哦，多谢！我之前用的别的主题，设置的是 zh-CN，现在改成 zh-Hans 就好了。没注意到这个细节，打扰了。
