### ISSUE TITLE
markdown問題？

### ISSUE THREAD

**Issue by jerryc127** [Molunerfinn/hexo-theme-melody#191]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Feature Request

---

请问这种在markdown要怎么书写？
还是只是doc支持这种格式
![image](https://user-images.githubusercontent.com/16351105/55955703-a5e9f800-5c94-11e9-818b-a2a9c2159d80.png)
![image](https://user-images.githubusercontent.com/16351105/55955712-aaaeac00-5c94-11e9-9d1d-3d8689d88593.png)
![image](https://user-images.githubusercontent.com/16351105/55955725-b13d2380-5c94-11e9-8f0f-e576ac28180b.png)

**Comment by Molunerfinn** [comment]
这个不是hexo的，是vuepress的。
https://vuepress.vuejs.org/guide/markdown.html#custom-containers
