### ISSUE TITLE
关于algolia搜索插件的显示问题？

### ISSUE THREAD

**Issue by monkeyip** [Molunerfinn/hexo-theme-melody#193]
hi，我弄好了algolia的搜索插件系统，唯一不完美的地方就是，我在主菜单上全部都是设置的英文显示，比如Home、Archives、Tags、Categories、About，但是这个algolia直接显示的是 **“搜索”**，显得特别突兀，能不能改一些文件的配置去更改这个显示方式呢？

还有一个问题：
我在使用搜索功能的时候，结果出来之后点击文章，跳到别的404的网站
https://yoursite.com/2019/01/22/Oracle%E5%88%A0%E9%99%A4%E9%87%8D%E5%A4%8D%E6%95%B0%E6%8D%AE/
这是为何啊？

以上的问题解决了，主要是在集成了搜索功能时，站点配置文件里的url一定要改成自己的博客网址。

感谢解答，感激不尽！

**Comment by Molunerfinn** [comment]
站点的_config.yml语言设置成英文就行了。

https://github.com/Molunerfinn/Molunerfinn.github.io/blob/hexo/_config.yml#L10

**Comment by monkeyip** [comment]
> 站点的_config.yml语言设置成英文就行了。注意是hexo站点的配置文件不是hexo-theme-melody的配置文件。
> 
> https://github.com/Molunerfinn/Molunerfinn.github.io/blob/hexo/_config.yml#L10

谢谢，那我试试。

刚刚，我在改站点配置文件里的url之后，发现还是跳转不到正确的网址，还是https://yoursite.com/，我再试试看吧，谢谢了。

**Comment by nauya** [comment]
> > 站点的_config.yml语言设置成英文就行了。注意是hexo站点的配置文件不是hexo-theme-melody的配置文件。
> > https://github.com/Molunerfinn/Molunerfinn.github.io/blob/hexo/_config.yml#L10
> 
> 谢谢，那我试试。
> 
> 刚刚，我在改站点配置文件里的url之后，发现还是跳转不到正确的网址，还是[https://yoursite.com/，我再试试看吧，谢谢了。](https://yoursite.com/%EF%BC%8C%E6%88%91%E5%86%8D%E8%AF%95%E8%AF%95%E7%9C%8B%E5%90%A7%EF%BC%8C%E8%B0%A2%E8%B0%A2%E4%BA%86%E3%80%82)

你解决了吗‘？  怎么解决的  。我这和你一样的问题

**Comment by Neorah** [comment]
> hi，我弄好了algolia的搜索插件系统，唯一不完美的地方就是，我在主菜单上全部都是设置的英文显示，比如Home、Archives、Tags、Categories、About，但是这个algolia直接显示的是 **“搜索”**，显得特别突兀，能不能改一些文件的配置去更改这个显示方式呢？
> 
> 还有一个问题：
> 我在使用搜索功能的时候，结果出来之后点击文章，跳到别的404的网站
> https://yoursite.com/2019/01/22/Oracle%E5%88%A0%E9%99%A4%E9%87%8D%E5%A4%8D%E6%95%B0%E6%8D%AE/
> 这是为何啊？
> 
> 以上的问题解决了，主要是在集成了搜索功能时，站点配置文件里的url一定要改成自己的博客网址。
> 
> 感谢解答，感激不尽！

想问一下我搜索出来文章后，点击文章就跳转到/undefined/了，请问你有遇到过这个情况吗？
