### ISSUE TITLE
AsciiDoc support for blog content

### ISSUE THREAD

**Issue by zjcscut** [Molunerfinn/hexo-theme-melody#194]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 

All version.

**Platform:**

All platforms.

**Browser:**

Chrome.

## Feature Request
I hope blog content can be  writen by [AsciiDoc](https://asciidoctor.org/docs/asciidoc-syntax-quick-reference) and rendered by AsciiDoc. THX!

---

**Comment by Molunerfinn** [comment]
This is not a hexo-theme-melody thing, you should look to find some `hexo-renderer` to achieve this.
