### ISSUE TITLE
关于melody主题网络图片显示问题？

### ISSUE THREAD

**Issue by monkeyip** [Molunerfinn/hexo-theme-melody#195]
目前我在markdown中添加了网络图片的路径，hexo d之后，在浏览器打开博客，图片并不能立马显示出来，过了一会才会显示，而且文章插入的图片有的显示有的不显示。

我用手机登陆博客，图片全部不显示。

我的理解是不是用网络图片加载到缓存，这个速度会很慢啊，改成通过picgo把图片存储在github上会不会好一点？

谢谢！

**Comment by Sheey11** [comment]
picgo 只是帮助你往文章里加图片，图片加载速度由存放图片服务器的访问速度决定，如果扔 gitpages 上国内访问会巨慢。

**Comment by Molunerfinn** [comment]
图片显示慢跟你用什么主题都没关系，跟你的图片存储的服务商有关系。存在github上国内访问速度会慢点。推荐用一些CDN服务商的，比如七牛，阿里云OSS，又拍云，腾讯云COS等。一个月付几块钱而已。
