### ISSUE TITLE
关于新版图标显示的问题

### ISSUE THREAD

**Issue by yukunshang** [Molunerfinn/hexo-theme-melody#198]
您好，首先感谢您开发这么好用的theme。我在选择社交图标的时候出现了bug。
![image](https://user-images.githubusercontent.com/25716306/57776881-2946af80-7753-11e9-8e5f-c089bd58064f.png)
这是页面显示，可以看到没有社交图标。
![image](https://user-images.githubusercontent.com/25716306/57776952-51361300-7753-11e9-8a83-d8dfe35d26c6.png)
![image](https://user-images.githubusercontent.com/25716306/57776983-5d21d500-7753-11e9-846b-56bcc95a5c8d.png)
完全按照您的教程设置的，但是就是不生效。期望得到您的回复。

**Comment by Molunerfinn** [comment]
我想问一下，你这两张截图里配置的是在哪个文件里配置的？

是在hexo博客的目录下的`_config.yml`，还是melody主题目录下的`_config.yml`还是按照文档里说的，`source/_data/melody.yml`?

**Comment by Molunerfinn** [comment]
就我的判断，你应该是在hexo博客的目录下的_config.yml里写了这些配置了吧？那么你就没有按照文档来了。

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/57777569-c9510880-7754-11e9-8f35-4284d8088344.png)
![image](https://user-images.githubusercontent.com/12621342/57777604-da9a1500-7754-11e9-8904-abbcfc4e5af4.png)

**Comment by yukunshang** [comment]
额， 我完全按照官网的配置教程改的。目录如下：
![image](https://user-images.githubusercontent.com/25716306/57828762-2d201380-77df-11e9-8bba-e3375e7143e3.png)
主要设置是在melody.yml中的。
今天早上我又查了下问题，应该是浏览器缓存的问题。新版基于 Chromium的Microsoft Edge的问题。我用chrome 打开就没问题了。 
再次谢谢您的指导！

**Comment by yukunshang** [comment]
刚刚又试了一下，清除缓存也没用。看来基于 Chromium的Microsoft Edge是没办法显示这些图标了。

**Comment by Molunerfinn** [comment]
我的基于 Chromium的Microsoft Edge显示没问题

**Comment by yukunshang** [comment]
这是Edge浏览器：
![image](https://user-images.githubusercontent.com/25716306/57871349-b402d980-783b-11e9-982d-896c9be9fc3c.png)
这是chrome浏览器 
![image](https://user-images.githubusercontent.com/25716306/57871433-df85c400-783b-11e9-8a40-9bf0a0007fcf.png)

缓存也清过了。

**Comment by Molunerfinn** [comment]
我不知道你是什么原因，我下了最新的Microsoft Edge Insider版本，并不能复现。
![image](https://user-images.githubusercontent.com/12621342/57896562-e3d5cf80-7883-11e9-8afd-560959372632.png)

**Comment by Molunerfinn** [comment]
这是我的配置文件

https://github.com/Molunerfinn/Molunerfinn.github.io/blob/hexo/source/_data/melody.yml

**Comment by Sorryjjj** [comment]
您好，我遇到了同样的问题，已经按照上面的解释正确操作了，依然无效
![image](https://user-images.githubusercontent.com/29476225/69494997-d5383700-0efc-11ea-933f-4f9ea64fe54c.png)

**Comment by Molunerfinn** [comment]
> 您好，我遇到了同样的问题，已经按照上面的解释正确操作了，依然无效
> ![image](https://user-images.githubusercontent.com/29476225/69494997-d5383700-0efc-11ea-933f-4f9ea64fe54c.png)

```yaml
social:
  github fab:
```
注意github这些图标名前是有缩进的，表示social的列表

**Comment by Sorryjjj** [comment]
> > 您好，我遇到了同样的问题，已经按照上面的解释正确操作了，依然无效
> > ![image](https://user-images.githubusercontent.com/29476225/69494997-d5383700-0efc-11ea-933f-4f9ea64fe54c.png)
> 
> ```yaml
> social:
>   github fab:
> ```
> 
> 注意github这些图标名前是有缩进的，表示social的列表

感谢您的回复，已经解决，请允许我提另外一个问题，在设置top_img的时候想要底部不显示设置的图片，尝试修改这部分无效
![image](https://user-images.githubusercontent.com/29476225/69496164-2b5fa700-0f0a-11ea-875c-7d9577047a74.png)
![image](https://user-images.githubusercontent.com/29476225/69496177-5b0eaf00-0f0a-11ea-8c97-545a599c9263.png)
![image](https://user-images.githubusercontent.com/29476225/69496190-7ed1f500-0f0a-11ea-933f-d31233f5cfbb.png)

**Comment by wnxy** [comment]
您好，我的“下一页”图标出现问题，我已经按照官方文档检查了一遍，还是没能解决，希望您看一下！
![GwqMqg.png](https://s1.ax1x.com/2020/04/04/GwqMqg.png)

**Comment by Molunerfinn** [comment]
> 您好，我的“下一页”图标出现问题，我已经按照官方文档检查了一遍，还是没能解决，希望您看一下！
> ![GwqMqg.png](https://camo.githubusercontent.com/fb1366df1cbbe97caf0d81b81dff1b0bcb531ff0/68747470733a2f2f73312e617831782e636f6d2f323032302f30342f30342f4777714d71672e706e67)

升级版本到最新的master代码或者1.7.0版本就行。你的版本是1.6.1

**Comment by wnxy** [comment]
好的，谢谢您！
我想问一下不蒜子统计已开通，但是不显示图标，也是这个原因吗？
再次感谢！





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"PiEgg"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月4日(星期六) 下午5:42
收件人:&nbsp;"Molunerfinn/hexo-theme-melody"<hexo-theme-melody@noreply.github.com&gt;;
抄送:&nbsp;"　　　　"<3118824295@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [Molunerfinn/hexo-theme-melody] 关于新版图标显示的问题 (#198)





  
您好，我的“下一页”图标出现问题，我已经按照官方文档检查了一遍，还是没能解决，希望您看一下！
 
  
升级版本到最新的master代码或者1.7.0版本就行。你的版本是1.6.1
