### ISSUE TITLE
关于修改一些大小

### ISSUE THREAD

**Issue by andyvoice** [Molunerfinn/hexo-theme-melody#20]
我觉得top-img的高度太大，怎么能调小？
右上角home等字体太小，怎么能调整？
谢谢

**Comment by Molunerfinn** [comment]
。。请不要每个问题都开一个issue。对于样式相关的统一到一个issue里提。谢谢

**Comment by andyvoice** [comment]
明白了

**Comment by andyvoice** [comment]
我之前提过的问题没注意已经变成closed，所以又提了一遍，：）
