### ISSUE TITLE
when i use `hexo s` to preview

### ISSUE THREAD

**Issue by ahojcn** [Molunerfinn/hexo-theme-melody#200]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
master 1.6.1

**Platform:**
macOS

**Browser:**
Chrome
## Expected behavior 
well, i want to use this theme, but... `hexo s`, the preview show as follows:

## Actual behavior 
![](https://wx4.sinaimg.cn/mw690/006wR0dcly1g35t1mvogtj316v0abtdi.jpg)

## Steps to reproduce the behavior 
1. i clone this theme as the doc.
2. use `hexo s`
3. the problem see....

## Feature Request

---

**Comment by ahojcn** [comment]
sorry, i'll see F&Q

**Comment by Sheey11** [comment]
STICK TO THE DOCUMENT.
seems like you haven't installed the `hexo-renderer-jade`. see [Quick Strat - Setup](https://molunerfinn.com/hexo-theme-melody-doc/quick-start.html#setup).

**Comment by ahojcn** [comment]
oooooh! i'll try it.

**Comment by ahojcn** [comment]
thank you ~~~

**Comment by ahojcn** [comment]
nice theme, thanks!
![image](https://user-images.githubusercontent.com/43307215/57970902-b9862e00-79b9-11e9-8a9e-02e4e1ade5ad.png)

**Comment by Sheey11** [comment]
Hope you enjoy! :)
