### ISSUE TITLE
代码高亮问题

### ISSUE THREAD

**Issue by ahojcn** [Molunerfinn/hexo-theme-melody#202]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
master 1.6.1

**Platform:**
macOS

**Browser:**
Chrome

## Expected behavior 
代码高亮

## Actual behavior 
不高亮，复制按钮也木有

![image](https://user-images.githubusercontent.com/43307215/57979475-a07c8c00-7a50-11e9-9856-cd9da62bd162.png)

## Steps to reproduce the behavior 
1. 我按照文档修改了 `highlight_theme: default`
2. `hexo g & hexo d`
3. 代码中我标注了是什么语言的，但是没有高亮，也没有复制按钮。

## Feature Request

---

**Comment by ahojcn** [comment]
## 我的配置文件是这样的
### melody
![image](https://user-images.githubusercontent.com/43307215/57979499-09640400-7a51-11e9-998d-31bb903604ab.png)
### _config
![image](https://user-images.githubusercontent.com/43307215/57979507-1a147a00-7a51-11e9-8da2-31e843c70881.png)

**Comment by Molunerfinn** [comment]
把你的markdown文件贴上来

**Comment by Molunerfinn** [comment]
应该是你markdown文件的代码块格式写错了。

**Comment by ahojcn** [comment]
## 下面这个是我截图中的markdown文件
---
title: 【Nao机器人】BHuman中的类-MarkedLine
comment: false
date: 2019-04-20 08:44:13
tags:
	- Nao机器人
	- BHuman
categories:
	- Nao机器人

---

```cpp
Src/Representations/Perception/FieldFeatures/FieldMarker.h
```

在这个文件中表示了在 bhuman 中标记线的一些方法。
MarkedLine(线)、MarkedIntersection(交点)、MarkedPoint(点)。
线的相交分为 X、L、T 型，这个很形象。其中，`T includes L; X includes T and L `。

关于线的交叉点结构在下面这个文件中：

```cpp
Src/Representations/Perception/FieldPercepts/FieldLineIntersections.h
```



## MarkedLine

```cpp
  STREAMABLE(MarkedLine,
  {
    /*
      ___________3__________
     |      4|______|5      |
     |           6          |
     |2                     |
     |                      |
     |___________1__________|
  
     */
    ENUM(LineMarker,
    {,
      midLine, // --> 1
      sideLine, // --> 2
      groundLine, // --> 3
      sidePenaltyL, // --> 4
      sidePenaltyR, // --> 5
      groundPenalty, // --> 6
  
      firstLineMarkerOther,
      otherSideLine = firstLineMarkerOther,
      otherGroundLine,
      otherSidePenaltyL,
      otherSidePenaltyR,
      otherGroundPenalty,
    });
    static LineMarker mirror(const LineMarker marker);    // mirror 镜子
    LineMarker mirror() const;
  
    MarkedLine() = default;
    MarkedLine(unsigned line, LineMarker marker);
    void draw() const,
  
    (unsigned) lineIndex,
    (LineMarker)(numOfLineMarkers) marker,
  });
  
  inline MarkedLine::MarkedLine(unsigned line, LineMarker marker) : lineIndex(line), marker(marker) {}
```

## MarkedIntersection 交点处的标记方式

```cpp
STREAMABLE(MarkedIntersection,
{
  /*
           STL    STR
  BLL _______v______v_______ BLR
    |       |______|       |
    |    SLL        SLR    |
    |                      |
    |                      |
    |______________________|
  BT                         otherBT

   */
  /**
   * marker name components: (S/B)(L/T)(L/R)
   *  (Small/Big)(L-intersection, T-intersection)(Left/Right)
   */
  ENUM(IntersectionMarker,
  {,
    BT,
    STL,
    STR,
    BLL,
    SLL,
    SLR,
    BLR,

    firstIntersectionMarkerOther,
    otherBT = firstIntersectionMarkerOther,
    otherSTL,
    otherSTR,
    otherBLL,
    otherSLL,
    otherSLR,
    otherBLR,
  });
  static IntersectionMarker mirror(const IntersectionMarker& marker);
  IntersectionMarker mirror() const;

  MarkedIntersection() = default;
  MarkedIntersection(unsigned intersection, IntersectionMarker marker);

  void draw() const,

  (unsigned) intersectionIndex,
  (IntersectionMarker)(numOfIntersectionMarkers) marker,
});

inline MarkedIntersection::MarkedIntersection(unsigned intersection, IntersectionMarker marker)
  : intersectionIndex(intersection), marker(marker) {};
```

## MarkedPoint

```cpp
STREAMABLE(MarkedPoint,
{
  ENUM(PointMarker,
  {,
    midCircle, //Circle
    penaltyMark, //PenaltyMark
    goalPostL, //left goal post   左目标门柱
    goalPostR, //right goal post  右目标门柱

    firstPointMarkerOther,
    otherpenaltyMark = firstPointMarkerOther,
    othergoalPostL,
    othergoalPostR,
  });
  static PointMarker mirror(const PointMarker& marker);
  PointMarker mirror() const;

  MarkedPoint() = default;
  MarkedPoint(const Vector2f& p, PointMarker marker, bool outOfCurrentFrame = true);

  void draw() const,//TODO

  (Vector2f)(Vector2f()) point,
  (PointMarker)(numOfPointMarkers) marker,
  (bool)(false) outOfCurrentFrame,
});

inline MarkedPoint::MarkedPoint(const Vector2f& p, PointMarker marker, bool outOfCurrentFrame)
  : point(p), marker(marker), outOfCurrentFrame(outOfCurrentFrame) {}
```

**Comment by Molunerfinn** [comment]
我这边测试主题没问题：

![image](https://user-images.githubusercontent.com/12621342/57982414-dbde8100-7a77-11e9-9612-c9aa0bc181f3.png)

生成的HTML如下：

![image](https://user-images.githubusercontent.com/12621342/57982417-e862d980-7a77-11e9-8059-734ea45b40ae.png)

我发现你生成的HTML并非正常的格式。可能是你渲染器有问题。这个跟主题没有关系了。

可以参考我的hexo安装的渲染器等。

https://github.com/Molunerfinn/Molunerfinn.github.io/blob/hexo/package.json

**Comment by ahojcn** [comment]
thank you~

**Comment by Guang1234567** [comment]
@ahojcn 

你解决了吗?  好像我也遇到了 -_-||
