### ISSUE TITLE
侧栏目录

### ISSUE THREAD

**Issue by ronething** [Molunerfinn/hexo-theme-melody#203]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Feature Request

---

侧栏目录问题 

```
toc:
  enable: true
```

如果设置 enable 默认点开文章就会弹出目录  如果设置为 false 则文章没有目录

可否增加一个选项是 hide 之类的 默认点开文章是隐藏(即不弹出)目录的 （可以手动展开）

貌似 next 主题有这个功能 https://theme-next.iissnan.com/getting-started.html#sidebar-settings 

还望收到回复，谢谢。

**Comment by Molunerfinn** [comment]
会考虑加上，最近没时间

**Comment by jerryc127** [comment]
有空写了下
可参考这个
https://github.com/jerryc127/hexo-theme-melody/commit/b833c733976dfcad902c118bb4ff118be1144d41
https://github.com/jerryc127/hexo-theme-melody/commit/dcc11945951912d5bd0d2a452f5e74cd33fd0db7
https://github.com/jerryc127/hexo-theme-melody/commit/f231674fd1efd5e3aa95fac869046974ae03517a

**Comment by whypro** [comment]
首页的作者信息侧边栏能否也考虑这个问题？比如加一个通用的配置。
因为我是希望它可以默认显示。:)

**Comment by Molunerfinn** [comment]
@whypro 这会是个 `breaking change`，如果要发布会在1.7发布，届时要处理好跟旧版的兼容问题。

dev分支预计6月份会将这个feature更新上去。
