### ISSUE TITLE
top img not display

### ISSUE THREAD

**Issue by seniorcandy** [Molunerfinn/hexo-theme-melody#204]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**1.6.1

**Platform:**macOS, Android

**Browser:**chrome, safari

## Expected behavior 
top img is expercted to display img of given url
## Actual behavior 
top img not changes

![image](https://user-images.githubusercontent.com/11422477/58747471-61155d00-849e-11e9-9d07-030122fa47fd.png)
![image](https://user-images.githubusercontent.com/11422477/58747523-ce28f280-849e-11e9-9ace-65f13f36d779.png)

## Feature Request

---

**Comment by Sheey11** [comment]
try `hexo clean`.

**Comment by Molunerfinn** [comment]
you must set the wrong config file.Please set the config in theme melody's config file `melody.yml` as mentioned in docs.
