### ISSUE TITLE
I can't open my blog after use this theme

### ISSUE THREAD

**Issue by charon-cheung** [Molunerfinn/hexo-theme-melody#205]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: 1.6.1**

**Platform: windows 10**

**Browser: Chrome**

## Actual behavior 
only this on webpage

![image](https://user-images.githubusercontent.com/51428916/59145647-47819180-8a19-11e9-8787-6376ba6cd75d.png)

## Steps to reproduce the behavior 
I execute `npm install hexo-renderer-jade hexo-renderer-stylus --save`, use `theme: melody` in _config.yml in root hexo dir, I dont' have `_data` in dir `source` now, but I tried and got same problem.

my package.json:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.8.0"
  },
  "dependencies": {
    "hexo": "^3.8.0",
    "hexo-deployer-git": "^1.0.0",
    "hexo-generator-archive": "^0.1.5",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.1",
    "hexo-generator-tag": "^0.2.0",
    "hexo-renderer-ejs": "^0.3.1",
    "hexo-renderer-marked": "^1.0.1",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.3.3"
  }
}
```
[melody.zip](https://github.com/Molunerfinn/hexo-theme-melody/files/3268407/melody.zip)

**Comment by Molunerfinn** [comment]
Aha, maybe you don't find that `hexo-renderer-jade` is not in your `package.json`? Try `npm install hexo-renderer-jade --save` & make sure the `hexo-renderer-jade` is in the `package.json` just like mine:

![image](https://user-images.githubusercontent.com/12621342/59145908-e1970900-8a1c-11e9-8eda-49de29cb633c.png)
