### ISSUE TITLE
when i finished to copy the theme default config file _config.yml to the hexo work folder source/_data/melody.yml operation. there console happen 'Cannot read property 'css' of undefined'

### ISSUE THREAD

**Issue by ahang9524** [Molunerfinn/hexo-theme-melody#207]
`Unhandled rejection TypeError: F:\hexo\hexoblog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
    at eval (eval at wrap (F:\hexo\hexoblog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:80:25)
    at eval (eval at wrap (F:\hexo\hexoblog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:102:4)
    at template (eval at wrap (F:\hexo\hexoblog\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:1825:72)
    at Theme._View.View._compiled.locals [as _compiled] (F:\hexo\hexoblog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (F:\hexo\hexoblog\node_modules\hexo\lib\theme\view.js:30:15)
    at route.set (F:\hexo\hexoblog\node_modules\hexo\lib\hexo\index.js:394:29)
    at tryCatcher (F:\hexo\hexoblog\node_modules\bluebird\js\release\util.js:16:23)
    at F:\hexo\hexoblog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\hexo\hexoblog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:457:10)
    at resume_ (_stream_readable.js:933:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
Unhandled rejection TypeError: F:\hexo\hexoblog\themes\melody\layout\includes\layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url_for(url) + '?version=' + version())
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug
![{C7A0FAAC-2E9E-41D2-B939-6099693D639F} png](https://user-images.githubusercontent.com/25114920/59373096-8433ec80-8d7b-11e9-9e9c-93495d9a1cb1.jpg)
`

**Comment by Molunerfinn** [comment]
Show me your melody.yml

**Comment by ahang9524** [comment]
thank you for your reply.
use default hexo root _config.yml ：

# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: NoOneBlog
subtitle: Happiness is only real when shared!
description: Happiness is only real when shared!
keywords:
author: OnOne
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:

**Comment by ahang9524** [comment]
thank you for your reply.
i use default hexo root _config.yml config:

`# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: NoOneBlog
subtitle: Happiness is only real when shared!
description: Happiness is only real when shared!
keywords:
author: OnOne
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: melody

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type:`

**Comment by Sheey11** [comment]
Use ` ``` ` to wrap a multi-line code.
Besides, `themes/melody/_config.yml` instead of `hexo/_config.yml`.

---

`melody` support theme-separated config file, see [configuration](https://molunerfinn.com/hexo-theme-melody-doc/quick-start.html#configuration).

**Comment by Molunerfinn** [comment]
You copy the wrong `_config.yml`, just like the @Sheey11 said, you should use the `themes/melody/_config.yml` instead of `hexo/_config.yml`.

![image](https://user-images.githubusercontent.com/12621342/59438988-09c0a680-8e27-11e9-92de-c615a020476e.png)

![image](https://user-images.githubusercontent.com/12621342/59439079-2e1c8300-8e27-11e9-85c5-2e830248bd9c.png)

**Comment by ahang9524** [comment]
i got it.  thank you for your patient reply again.
