### ISSUE TITLE
The page views of single blog is only achieved by busuanzi ? 

### ISSUE THREAD

**Issue by charon-cheung** [Molunerfinn/hexo-theme-melody#208]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: 1.6**

**Platform: Windows**

**Browser: Chrome**

## Actual behavior 
Is `367` the views of the blog ?
![image](https://user-images.githubusercontent.com/51428916/59558276-085ace00-9021-11e9-8ede-95162b0d5de1.png)

## Feature Request

---

**Comment by Molunerfinn** [comment]
Yes. If you have other ways, welcome to submit a PR
