### ISSUE TITLE
Tips about theme

### ISSUE THREAD

**Issue by YePointer** [Molunerfinn/hexo-theme-melody#21]
Dear Molunerfinn
        Your theme is really great!
  However, I found that there was a code error in the topic development mentioned in your blog!

 Error:>hexo-jade-renderer hexo-stylus-renderer

Right:>hexo-renderer-jade hexo-renderer-stylus

Finally, I want to thank you. You make me feel like I can still hold on to the web, thank you for your theme

**Comment by Molunerfinn** [comment]
Hi YePointer,
Thanks you for choosing the theme-melody~I'll fix the error today! I wish to make the theme-meldoy become a popular theme of hexo~
