### ISSUE TITLE
Fireworks effect failed to open

### ISSUE THREAD

**Issue by Jacklin-Zhang** [Molunerfinn/hexo-theme-melody#210]
## Fireworks effect failed to open  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**
Linux

**Browser:**
Chrome
## Expected behavior 
Click to have fireworks effect
## Actual behavior 
Click no response

## Steps to reproduce the behavior 
Add **_fireworks: true_** to **_melody.yml_**
## Feature Request

---

**Comment by Molunerfinn** [comment]
I can't reproduce.

**Comment by Molunerfinn** [comment]
My blog works well.
https://molunerfinn.com/

**Comment by Jacklin-Zhang** [comment]
I don't know where the issue is.
https://jacklin-zhang.cn/

**Comment by Molunerfinn** [comment]
I'm sorry but you are not using hexo-theme-melody but [hexo-theme-butterfly](https://github.com/jerryc127/hexo-theme-butterfly), please go that repo to open an issue.

**Comment by Jacklin-Zhang** [comment]
But I think I should ask you, because  hexo-theme-butterfly is based on melody.
And I open a issue in that repo .
Thanks.

**Comment by Molunerfinn** [comment]
No, I don't know where the theme changed. Maybe it just removes the feature.

**Comment by Jacklin-Zhang** [comment]
ok,thanks.
