### ISSUE TITLE
How to avoid fancybox for inline images?

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#211]
## I want to create a new issue  

- [X] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [X] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [X] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.6.1

**Platform:** Windows

**Browser:** Chrome

## Expected behavior 

See this page: https://upupming.site/2019/06/17/weibo-emoji-dataset/#%E5%9F%BA%E6%9C%AC%E6%80%9D%E8%B7%AF

There is an inline image:

![20190629132227](https://i.loli.net/2019/06/29/5d16f59a2a1e458703.png)

The source code is:

```md
微博的表情有的是用图片表示的（比如 <img alt="[微笑]" src="https://h5.sinaimg.cn/m/emoticon/icon/default/d_hehe-039d0a6a8a.png" style="width:1em; height:1em;">），有的则是用 Unicode 表示的（比如 😀），有的则是直接用『[...]』表示的（比如 [黑桃]️）。
```

## Actual behavior 

I use VSCode to edit my md files, this is how it looks like in VSCode preview tab:

![20190629132410](https://i.loli.net/2019/06/29/5d16f5ffb623719152.png)

So, the question is, can melody detect inline images and don't put it in a fancy box (this will make the inline image super small and we cannot see the image until click it to zoom in.), and don't create the `img-alt` div? Or if it cannot, please at least support something like this to avoid it:

```md
<img class="no-fancybox" alt="[微笑]" src="https://h5.sinaimg.cn/m/emoticon/icon/default/d_hehe-039d0a6a8a.png" style="width:1em; height:1em;">
```

## Steps to reproduce the behavior 

Go to https://upupming.site/2019/06/17/weibo-emoji-dataset/#%E5%9F%BA%E6%9C%AC%E6%80%9D%E8%B7%AF

## Feature Request

Melody is awesome.

---

**Comment by Molunerfinn** [comment]
Sure, I'll add a `no-fancybox` className to avoid this behavior
