### ISSUE TITLE
有没有独立keywords功能？

### ISSUE THREAD

**Issue by Magolor** [Molunerfinn/hexo-theme-melody#213]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: v1.5.6**

**Platform: Windows**

**Browser: Chrome**

## Feature Request

不知道有没有独立keywords功能: 给网站添加keywords用于搜索引擎搜索，但这些keywords并不作为tags显示(同时保持tags的功能)。即希望将keywords和tags分离。在_post中可以直接写:

```
tags:
- xxx
- yyy
keywords:
- xxx
- zzz
```

---

**Comment by Molunerfinn** [comment]
目前还没有独立的keywords，是根据tags来的。可以考虑加一个这个功能

**Comment by Magolor** [comment]
> 目前还没有独立的keywords，是根据tags来的。可以考虑加一个这个功能

打扰了。非常感谢。

（P.S.：因为NexT等其他主题似乎都自带这种功能，我还以为可以呢，自己捣鼓了好长时间）

**Comment by Molunerfinn** [comment]
该功能已加到 `dev` 分支。注意 `keywords` 只支持数组格式。
![image](https://user-images.githubusercontent.com/12621342/61943388-de0c1100-afcd-11e9-8d66-aedd08607bde.png)

![image](https://user-images.githubusercontent.com/12621342/61943353-cf255e80-afcd-11e9-84a5-aaf67a59bea5.png)
