### ISSUE TITLE
[第三方支持]加入一个更多功能的live2d

### ISSUE THREAD

**Issue by NiTian1207** [Molunerfinn/hexo-theme-melody#214]
因为不太会用github,不知道hexo-theme-melody-doc应该怎么写,所以在这里写一下
这个修改的 live2d 能说话、能换装、能玩游戏、能拍照、还能自定义。
live2d的[项目地址](https://github.com/stevenjoezhang/live2d-widget)

下载后解压到 ```\themes\melody\source```
1.  将 文件夹名字改为 ```live2d-widget```
修改文件夹下 ```autoload.js```

2. 将
```const live2d_path = "https://cdn.jsdelivr.net/gh/stevenjoezhang/live2d-widget/";```
改为
```const live2d_path = "/live2d-widget/";```

3. 在 ```themes\melody\layout\includes\additional-js.pug``` 文件后添加一句 ```script(src=url_for('/live2d-widget/autoload.js'))```
4. 在 ```主题配置文件``` 里加入
 ```
live2d:
  enable: true
```

想修改看板娘大小、位置、格式、文本内容等，可查看并修改 ```waifu-tips.js``` 、 ```waifu-tips.json``` 和 ```waifu.css```。

**Comment by NiTian1207** [comment]
可以在我的blog里看看效果
https://www.nitian1207.top/
这个 live2d并不会出现在文章页面中, 我也不太清楚要怎么设置 (．．)

**Comment by Molunerfinn** [comment]
感谢，希望直接去文档仓库更新。这个不算melody本身的功能。

**Comment by NiTian1207** [comment]
> 
> 
> 感谢，希望直接去文档仓库更新。这个不算melody本身的功能。

请问,怎么样设置才能让文章页面也显示live2d
