### ISSUE TITLE
怎么给about页面nav换背景

### ISSUE THREAD

**Issue by ZhaoTim** [Molunerfinn/hexo-theme-melody#215]
想给关于我的页面换页面上面的图，但是现在是不支持吗？

**Comment by Molunerfinn** [comment]
更新到 `dev` 分支最新版，在 `about/index.md` 头部的 `top_img` 指定一下图片链接即可。
![image](https://user-images.githubusercontent.com/12621342/62413768-59606900-b645-11e9-84af-9483bbf406c6.png)
