### ISSUE TITLE
[]求助]文章末尾版权

### ISSUE THREAD

**Issue by NiTian1207** [Molunerfinn/hexo-theme-melody#216]
文章末尾的版权中第一项 "文章作者" 后面的超链接为"mailto:undefined"
我没有找到如何修改这一项

**Comment by Molunerfinn** [comment]
请按模板发issue。

**Comment by Molunerfinn** [comment]
去站点的（不是主题的） `_config.yml` 里配置 `email` 的属性即可。

**Comment by NiTian1207** [comment]
我在站点配置中 添加"email: 我的邮箱" 或是 "e-mail: 我的邮箱" 或是 "mail: 我的邮箱" 都不能改变这个值

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/62420446-0fb76300-b6c5-11e9-98ca-38188e3e5e7b.png)
![image](https://user-images.githubusercontent.com/12621342/62420449-1ba32500-b6c5-11e9-9685-8ebdb53af859.png)
我没问题。配置文件是站点的不是主题的。配置完重新生成博客才会生效

**Comment by NiTian1207** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/12621342/62420446-0fb76300-b6c5-11e9-98ca-38188e3e5e7b.png)
> ![image](https://user-images.githubusercontent.com/12621342/62420449-1ba32500-b6c5-11e9-9685-8ebdb53af859.png)
> 我没问题。配置文件是站点的不是主题的。配置完重新生成博客才会生效

是我弄错了,感谢 (・∀・)
