### ISSUE TITLE
Custom Excerpt and Top Avatar

### ISSUE THREAD

**Issue by Magolor** [Molunerfinn/hexo-theme-melody#217]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: v1.5.6**

**Platform: Windows**

**Browser: Chrome**

## Feature Request

建议添加自定义节选功能，而不是只能取自文章的前多少字，希望能自己添加一些对这篇文章的简介和描述。例如在文章中添加`excerpt: "xxxxxx"`，后面的内容会被当做节选放在首页上。

建议添加可选的自定义顶部头像，现在Melody只在侧栏中展示头像，顶部只有Title和Subtitle，希望可以添加顶部头像。当然，不想要这个头像的可以设置`false`之类的方式去掉。

谢谢！辛苦了！

Suggest adding custom excerpt besides auto excerpt in order to add arbitrary description about an article. In short, I would like a `excerpt: "xxxxxx"` option in post.

Suggest top avatar display feature while there are only Title and Subtitle displayed currently. Of course, it should be allowed to switch off by whatever something such as setting a `false`.

Thanks in advance.

---

**Comment by Molunerfinn** [comment]
节选一直可以手动指定，请参考hexo官方文档。顶部头像这个涉及界面改动，需要再设计。

**Comment by Molunerfinn** [comment]
另外如果是你说的自定义节选，这个功能不是主题能做的，而是generator做的。
