### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by zc95** [Molunerfinn/hexo-theme-melody#22]
老铁，为什么我的首页，没有文章的详情只有标题和readmore，标签页和分类页也不出现
[https://zc95.github.io](https://zc95.github.io)
[https://zc95.github.io/tags/](https://zc95.github.io/tags/)
[https://zc95.github.io/categories/](https://zc95.github.io/categories/)

**Comment by Molunerfinn** [comment]
第一个问题，readmore出现的地方是你markdwon里`<!-- more -->`出现的地方。挪挪位置就能看见文章其他部分。
标签页和分类页的问题请你查看你的操作是否如[这个issue](https://github.com/Molunerfinn/hexo-theme-melody/issues/11)一样。注意页面的type是`tags`和`categories`才能显示。我猜你应该是写成了tag和category。

**Comment by zc95** [comment]
都解决啦，谢谢。
请问有这个图的原图么 我想要。。。。
https://ws1.sinaimg.cn/large/8700af19ly1fjbf9wlz0qj21z20xy7wk.jpg

**Comment by Molunerfinn** [comment]
Here you are:

![bg1](https://user-images.githubusercontent.com/12621342/34256989-e5dad8ea-e692-11e7-8b41-018d5c9488bd.jpg)
