### ISSUE TITLE
[feedback]how to hid exact article from index

### ISSUE THREAD

**Issue by sino1641** [Molunerfinn/hexo-theme-melody#220]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:1.6.1

**Platform:Windows

**Browser:Chrome

## Expected behavior 
I want to hide exact article from index like About post.
## Actual behavior 
I'm a beginner of hexo and programming and I've tried searching all links above for solutions but nothing could help me. 
There is a para called ''notshow'' but it seems does not work on melody.

## Feature Request

---

Starred =w=

**Comment by Sheey11** [comment]
Create a folder in `source`, and put something you want to show in it (like `index.md`), then `hexo g`, BINGO! Now you can visit this page in `yoursite.com/foldername`.

**Comment by sino1641** [comment]
> Create a folder in `source`, and put something you want to show in it (like `index.md`), then `hexo g`, BINGO! Now you can visit this page in `yoursite.com/foldername`.
THX! I tried but it didn't work as well. Also, there is no toc catalog sidebar on that page. (⊙ˍ⊙)

**Comment by Sheey11** [comment]
According to [hexo docs](https://hexo.io/docs/writing.html), you can try put `something.md` right into `source` folder and set `layout` to `page`, I never tried this before, hope this would be helpful.

**Comment by Sheey11** [comment]
I realized there is a feature which allows you to enable toc, see [melody docs](https://molunerfinn.com/hexo-theme-melody-doc/theme-config.html#toc).

**Comment by Molunerfinn** [comment]
1. create `folder` in `source/`:
https://github.com/Molunerfinn/Molunerfinn.github.io/tree/hexo/source/about
2. create `index.md` in `folder`:
3. add `type` in front matter of `index.md`:
![image](https://user-images.githubusercontent.com/12621342/63414656-e15cb600-c42e-11e9-8843-dcd77c078ea6.png)

4. `hexo clean && hexo g`

5. open `yoursite.com/about/`

for example: https://molunerfinn.com/about/
