### ISSUE TITLE
One page generates many browsing histories

### ISSUE THREAD

**Issue by GregYuan** [Molunerfinn/hexo-theme-melody#225]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: *1.6.1*

**Platform: *macOS*

**Browser: *Chrome*

## Expected behavior 
One page generate a single browsing history
## Actual behavior 
page:
<img width="1277" alt="page" src="https://user-images.githubusercontent.com/22870372/66258539-de4c3800-e7d8-11e9-8d01-a3b5758af8cc.png">

history:
<img width="1280" alt="history" src="https://user-images.githubusercontent.com/22870372/66258543-f4f28f00-e7d8-11e9-988f-687cc1888cfd.png">

## Steps to reproduce the behavior 
Open this page [hexo持久化构建以及给自有域名github-page上HTTPS](https://molunerfinn.com/hexo-travisci-https/) and scroll to the bottom, check history recently visited.
## Feature Request

---

**Comment by Kiyo5hi** [comment]
If you check the table of contents on this page, you will find 11 sections. This issue is probably caused by the transition between different sections.

**Comment by Kiyo5hi** [comment]
> If you check the table of contents on this page, you will find 11 sections. This issue is probably caused by the transition between different sections.

After I reproduced the issue, I checked the URLs for each browsing history. They point to different sections on the page.

**Comment by Molunerfinn** [comment]
It's for the smooth scroll. And the histories you see were all hash-change:

![image](https://user-images.githubusercontent.com/12621342/66262061-c8a43600-e80b-11e9-9a25-2b00f5ab599b.png)

It's not a bug but a feature.

**Comment by Kiyo5hi** [comment]
> It's for the smooth scroll. And the histories you see were all hash-change:
> 
> ![image](https://user-images.githubusercontent.com/12621342/66262061-c8a43600-e80b-11e9-9a25-2b00f5ab599b.png)
> 
> It's not a bug but a feature.

which only makes it better lol
