### ISSUE TITLE
In the archive page, There is a uneven pixel width resulting in a jagged feeling.

### ISSUE THREAD

**Issue by xiao1272209235** [Molunerfinn/hexo-theme-melody#226]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** v1.6.1

**Platform:** Windows10

**Browser:**Chrome 版本 77.0.3865.90（正式版本） （64 位）

## Expected behavior 
![image](https://user-images.githubusercontent.com/29248764/66266349-818f6280-e856-11e9-9fa6-a2aa3bd82c02.png)

## Actual behavior 
![image](https://user-images.githubusercontent.com/29248764/66266355-8fdd7e80-e856-11e9-8b17-c56c5f1cca9a.png)

## Steps to reproduce the behavior 
There's no need to reproduce, it's always there.

## Feature Request

---

**Comment by Molunerfinn** [comment]
Can't reproduce.

https://molunerfinn.com/archives/

![image](https://user-images.githubusercontent.com/12621342/66266604-ce286d00-e859-11e9-8927-d04cc8b0a65b.png)

**Comment by Molunerfinn** [comment]
But I probably know the reason.

**Comment by xiao1272209235** [comment]
> But I probably know the reason.

Maybe it's the resolution of the monitor...
When I zoomed in at 110 percent on Chrome, the problem disappeared.

**Comment by Molunerfinn** [comment]
Try dev branch & the problem will be solved

**Comment by xiao1272209235** [comment]
> Try dev branch & the problem will be solved

Thanks, I go to try.
