### ISSUE TITLE
markdown 有序列表显示错误

### ISSUE THREAD

**Issue by GregYuan** [Molunerfinn/hexo-theme-melody#228]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: *1.6.1*

**Platform: *macOS*

**Browser: *Chrome*

## Expected behavior 
有序列表数字按1,2,3,...排列
## Actual behavior 
<img width="738" alt="Screen Shot 2019-10-11 at 6 03 31 PM" src="https://user-images.githubusercontent.com/22870372/66643527-7d49b780-ec51-11e9-9e69-c8d053c7f1c6.png">

## Steps to reproduce the behavior 
新建 hexo 页面，拷贝如下代码，hexo g && hexo s 在浏览器查看

```
1. 终端安装`anaconda-clean`
\```
conda install anaconda-clean
\```
2. 删除所有与 Anaconda 有关的文件与目录
\```
anaconda-clean --yes
\```
3. 第 2 步中的`Anaconda-Clean`会创建所有可能被删除的文件和目录的备份，该备份存放在根目录`/~`一个名为`.anaconda_backup`的文件夹中。删除该备份文件
\```
rm -rf ~/.anaconda_backup
\```
```

使用时删掉斜杠\\. 

备注：其他平台比如简书，VSCode 的 markdown 编辑器能正常显示有序列表。

## Feature Request

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/66653735-47b1c800-ec6b-11e9-82f6-3746b41dabf9.png)
测试没问题。列表如果显示有问题请检查markdown书写+渲染器的问题。

**Comment by GregYuan** [comment]
解决了，是 MarkDown 书写的问题。参考 [StackOverflow Markdown: continue numbered list](https://stackoverflow.com/questions/18088955/markdown-continue-numbered-list)  后，有序列表下的代码块要用四个空格缩进，并且阅读更多`<!-- more -->`前也要加四个空格。
