### ISSUE TITLE
手机端代码过长时，复制图标显示错位

### ISSUE THREAD

**Issue by GregYuan** [Molunerfinn/hexo-theme-melody#229]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: *1.6.1*

**Platform: *iOS*

**Browser: *Safari*

## Expected behavior 
![WechatIMG1](https://user-images.githubusercontent.com/22870372/66645043-057d8c00-ec55-11e9-8e35-8d99c5e2bb63.png)

## Actual behavior 
![WechatIMG2](https://user-images.githubusercontent.com/22870372/66645060-0dd5c700-ec55-11e9-99dc-3de6acd8124f.png)

## Steps to reproduce the behavior 
iPhone 用 Safari 打开这个[页面](https://yuangesheng.com/2019/10/09/mac-hexo-blog/)，滚动页面即可看到图标显示错位
## Feature Request

---

**Comment by Molunerfinn** [comment]
代码区这块的代码名 + 复制按钮会重构一遍

**Comment by Kiyo5hi** [comment]
iPhone SE + iOS 12.3.1 cannot reproduce the issue.

**Comment by Molunerfinn** [comment]
@Kiyo5hi iOS 13:
![image](https://user-images.githubusercontent.com/12621342/66692738-d35f3f00-ecd3-11e9-8545-f5d6bc3ca4ee.png)

**Comment by Kiyo5hi** [comment]
> @Kiyo5hi iOS 13:
> ![image](https://user-images.githubusercontent.com/12621342/66692738-d35f3f00-ecd3-11e9-8545-f5d6bc3ca4ee.png)

This might be an issue with the newest version of Safari.
I just upgraded my iPhone and got the same result.

**Comment by Molunerfinn** [comment]
@Kiyo5hi Yes. I think there is a problem with this place, and then I need to refactor the position and style.

**Comment by Kiyo5hi** [comment]
@Molunerfinn Got it; have any idea of solving the problem?
