### ISSUE TITLE
给图片加入注释

### ISSUE THREAD

**Issue by JasonRen23** [Molunerfinn/hexo-theme-melody#23]
![](http://pad.haroopress.com/assets/images/logo-small.png "haroopad") ，像这样插入haroopad图片标题，无法显示出来

**Comment by JasonRen23** [comment]
“ ![](http://pad.haroopress.com/assets/images/logo-small.png "haroopad")  ”

**Comment by JasonRen23** [comment]
![](http://pad.haroopress.com/assets/images/logo-smal.png "haroopad")

**Comment by Molunerfinn** [comment]
hexo的markdown渲染引擎并没有渲染title的dom元素。
不过可以通过js把标题抠出来。最近没啥时间维护，得等下个月1.4版本出来加上了。

**Comment by Molunerfinn** [comment]
已经加入1.4版本[开发计划](https://github.com/Molunerfinn/hexo-theme-melody/issues/15)

**Comment by JasonRen23** [comment]
Thx~

**Comment by Molunerfinn** [comment]
@JasonRen23 1.4.1版本已经支持。
详情可以查看release[更新日志](https://github.com/Molunerfinn/hexo-theme-melody/releases)
