### ISSUE TITLE
https://molunerfinn.com/hexo-theme-melody-doc/theme-pages.html#categories

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#233]
我主要是不知道每一个分类下面是跟博客的公网地址还是博客的md文件名

https://molunerfinn.com/hexo-theme-melody-doc/theme-pages.html#categories

_Originally posted by @Molunerfinn in https://github.com/Molunerfinn/hexo-theme-melody/issues/232#issuecomment-543224811_

**Comment by supersu097** [comment]
能给个示例么，你给的连接里面根本没有范例呀，我还是不知道怎么写呢

**Comment by Molunerfinn** [comment]
这个是hexo的问题并不是melody主题的问题。

**Comment by Molunerfinn** [comment]
https://github.com/Molunerfinn/Molunerfinn.github.io/tree/hexo
