### ISSUE TITLE
翻页的地方显示不正常，有html代码

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#234]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** master分支

**Platform:**windows

**Browser:**chrome77

## Actual behavior 
如题

## Steps to reproduce the behavior 
请访问http://sharpgan.com/
## Feature Request

---

**Comment by Molunerfinn** [comment]
请提供一下你的hexo博客目录下的`package.json`(不是主题的 `package.json`）

**Comment by supersu097** [comment]
> 请提供一下你的hexo博客目录下的`package.json`(不是主题的 `package.json`）

```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "4.0.0"
  },
  "dependencies": {
    "hexo": "^4.0.0",
    "hexo-algoliasearch": "^0.4.1",
    "hexo-asset-image": "^1.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^1.0.0",
    "hexo-generator-search": "^2.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^2.0.0",
    "hexo-renderer-stylus": "^1.1.0",
    "hexo-server": "^1.0.0",
    "hexo-wordcount": "^6.0.1"
  }
}
```

**Comment by Molunerfinn** [comment]
应该是Hexo升级到4.0.0的问题。如果影响比较大可以考虑先降回3.9.0

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/67093612-a7b4eb00-f1e4-11e9-9f04-e8188b421c41.png)

**Comment by supersu097** [comment]
> 应该是Hexo升级到4.0.0的问题。如果影响比较大可以考虑先降回3.9.0
还行，影响不是很大，等你修复哦~

**Comment by 4Aiur** [comment]
在hexo4.0环境下，不仅仅是melody翻页有html代码，Next主题里翻页时也有

**Comment by Molunerfinn** [comment]
@4Aiur 应该是Hexo的paginator函数问题。等官方修复了

**Comment by 4Aiur** [comment]
> 
> 
> @4Aiur 应该是Hexo的paginator函数问题。只能等官方修复了

[#3794](https://github.com/hexojs/hexo/issues/3794)4.0更新日志里有一句话，加一个 `escape: false `参数在`pagination.pug`这个文件里，就正常了。

**Comment by Molunerfinn** [comment]
@4Aiur 感谢

**Comment by supersu097** [comment]
> @4Aiur 感谢

@Molunerfinn 这个文件我用find找到了，可是打开后不知道怎么加这个参数，你能告诉我怎么加么，或者你修复后，我Git pull 一下

**Comment by Molunerfinn** [comment]
已经在dev分支修复了。
https://github.com/Molunerfinn/hexo-theme-melody/commit/c1d8ae9b5fd489beb2864bf0f2713f24b34c0a9f
