### ISSUE TITLE
建议相册页面增加位置标识符

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#235]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Feature Request
我根据已经关闭的一个issue里面的描述发现相册页面支持分类，这个很赞，不过后来却发现不支持位置标示符，如果支持的话就很方便我给别人分享照片的时候直接定位到我想让他看到的部分了

---

**Comment by Molunerfinn** [comment]
可以定位到标题处，跟文章里一样。

**Comment by supersu097** [comment]
> 可以定位到标题处，跟文章里一样。

可是经过我的测试并不能定位到标题呀，难道是浏览器的原因么，链接为
http://sharpgan.com/gallery/

**Comment by Molunerfinn** [comment]
在链接后加上#和标题名即可。

http://sharpgan.com/gallery/#华为溪村园区

**Comment by supersu097** [comment]
> 在链接后加上#和标题名即可。
> 
> [http://sharpgan.com/gallery/#华为溪村园区](http://sharpgan.com/gallery/#%E5%8D%8E%E4%B8%BA%E6%BA%AA%E6%9D%91%E5%9B%AD%E5%8C%BA)

果然可以，蟹蟹哦~
