### ISSUE TITLE
instant.page to accelerate page load

### ISSUE THREAD

**Issue by ZhangYanTJU** [Molunerfinn/hexo-theme-melody#236]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** the latest

**Platform:** Windows

**Browser:** Chrome

## Feature Request

 I found a service which is able to reducing the post loading time. Could you please consider adding this？
I want to do it by myself. But I'm not fimiliar about the HTML language.
---

**Comment by ZhangYanTJU** [comment]
https://instant.page

**Comment by Kiyo5hi** [comment]
I got ur point tho, but I don't know the point of adding this script because a static site is fast enough right?

**Comment by Molunerfinn** [comment]
No need to add this
