### ISSUE TITLE
top_img cannot display correctly

### ISSUE THREAD

**Issue by royalbluewa3** [Molunerfinn/hexo-theme-melody#24]
Thanks for the great theme~There might be a small bug.
top_img cannot display correctly on mobile phones when I simply set top_img: https://xxxxx.jpg
like this:
![2114243379](https://user-images.githubusercontent.com/17197502/34871358-4ff0486e-f7c8-11e7-8c6e-0526c1f9fc3c.jpg)

**Comment by Molunerfinn** [comment]
Got it, it will be fixed in the next patch version. : )
