### ISSUE TITLE
how to show sidebar by default on homepage

### ISSUE THREAD

**Issue by stekovinbranturry** [Molunerfinn/hexo-theme-melody#243]
![image](https://user-images.githubusercontent.com/33021960/67735753-0ded0980-fa40-11e9-9716-fa9859d22fd7.png)

any settings can do this?

**Comment by Kiyo5hi** [comment]
check the commit history on dev branch.
[Commit](https://github.com/Molunerfinn/hexo-theme-melody/commit/52f430bd26e2e682d12594524a19674fba319ccb)

**Comment by Molunerfinn** [comment]
The `sidebar display` option will be available in the v1.7

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/75085050-1e317300-5560-11ea-80e6-38fb89733342.png)
