### ISSUE TITLE
博客搭建过程中发现的一个小问题

### ISSUE THREAD

**Issue by linlinNB** [Molunerfinn/hexo-theme-melody#244]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
"1.6.1"

**Platform:**
macOS

**Browser:**
chrome、safari、fireFox

## Actual behavior 
每篇文章或者侧边栏中都有一个动态的分割线

## Feature Request

---

**Comment by Kiyo5hi** [comment]
Please attach pictures and how can I reproduce the behavior.

**Comment by linlinNB** [comment]
请问这个该如何去掉？我并没有找到可以配置的部分，需要修改pug模板吗？

**Comment by linlinNB** [comment]
![image](https://user-images.githubusercontent.com/22005231/67833493-c2aa2800-fb1f-11e9-92a0-60a8ba7e4fda.png)

**Comment by Kiyo5hi** [comment]
This is a feature. Stop using this theme or DIY.

**Comment by linlinNB** [comment]
。。。抱歉，刚才回复有点急，就是上面这个图片的分割线，我不想在侧边栏显示，我该如何去掉？？

**Comment by Kiyo5hi** [comment]
> This is a feature. Stop using this theme or DIY.

BTW you do have to modify pug templates.

**Comment by linlinNB** [comment]
@Kiyo5hi 好的，感谢
