### ISSUE TITLE
can I specify favicon: /melody-favicon.ico with a path outside the dir of theme/melody?

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#245]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Feature Request
Because the current way will break the process of git pull when I want to follow the update of the theme. Or I create a new file like melody-favicon-new.ico without git add, but this way will cause Untracked files while using git status that I really don't want to see this happening.

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/68370971-9f632680-0178-11ea-9599-59718f931ffe.png)

![image](https://user-images.githubusercontent.com/12621342/68370993-abe77f00-0178-11ea-839b-340062042e4a.png)
