### ISSUE TITLE
箭头图标（下一页）显示失败,the arrow icon (next page) doesn't show correctly.

### ISSUE THREAD

**Issue by wangzhongyu1997** [Molunerfinn/hexo-theme-melody#246]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**  1.6.1

**Platform:**  Linux Ubuntu

**Browser:**  Chrome

## Expected behavior 
I can't see the Font Awesome Icon of "next page" (the arrow) but the html source (\<i class="fa fa-chevron-right"\>\</i\>).
页面上不显示箭头图标（下一页），而是显示html代码（\<i class="fa fa-chevron-right"\>\</i\>）

## Actual behavior 

![issue](https://gitee.com/chuntiao/picture_bed/raw/master/issue.png)

## Feature Request

---

**Comment by Molunerfinn** [comment]
最新dev分支代码已修复。
