### ISSUE TITLE
I'm expecting the sidebar_display option so when do you release the v1.7?

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#248]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Feature Request

---

**Comment by Molunerfinn** [comment]
When I have time.

**Comment by Molunerfinn** [comment]
BTW, you can choose dev branch to use the feature

**Comment by Kiyo5hi** [comment]
try dev branch or try to implement the feature urself ty.

**Comment by supersu097** [comment]
> BTW, you can choose dev branch to use the feature

I've check out the branch to dev and set `sidebar_display: true`  in the source/_data/melody.yml,

but the sidebar on the homepage is still invisible by default, so what's wrong here?

**Comment by Molunerfinn** [comment]
why not read the comment?

**Comment by Molunerfinn** [comment]
![9AFA82C7-0143-4615-AB66-B1195378C31D](https://user-images.githubusercontent.com/12621342/68572496-84f2bb00-04a0-11ea-8f39-093b8b154fc0.jpeg)

**Comment by Kiyo5hi** [comment]
damn...

**Comment by supersu097** [comment]
@Molunerfinn it's weird that why i can't see the related comment of sidebar_display and itself.

**Comment by Kiyo5hi** [comment]
> @Molunerfinn it's weird that why i can't see the related comment of sidebar_display and itself.

reading the commit helps bruh

**Comment by supersu097** [comment]
@Molunerfinn Btw, I've donated a little bunch of money via Alipay, and hope you can keep developing and working on this theme.

**Comment by supersu097** [comment]
@Molunerfinn sorry that I forgot to ask am i the first guy to donate for this theme?

**Comment by supersu097** [comment]
@Molunerfinn I'm very glad to see it worked when I set `sidebar_display: index`, thank you very very much.

**Comment by supersu097** [comment]
> damn...

what's up, man?

**Comment by Kiyo5hi** [comment]
> > damn...
> 
> what's up, man?

nah take ur time playin wid this project broski
