### ISSUE TITLE
The toc is hidden after setting sidebar_display: index

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#250]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Steps to reproduce the behavior 
FYI: I've checked out to dev branch.
What I want are the sidebar shows on the index page and the toc shows on the article page at the same time, so waht should I do to fix this?
Any advice is welcome, thanks in advance.

## Feature Request

---

**Comment by Molunerfinn** [comment]
看注释啊，all
