### ISSUE TITLE
I suggest u post ur wechat&alipay qrcode onto README.md, so that others can easily donate for this theme.

### ISSUE THREAD

**Issue by supersu097** [Molunerfinn/hexo-theme-melody#251]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Feature Request
P.S. I've donated a little bunch of money for this theme,
and It's very highly recommended to donate for this theme in order to keep this theme going further and into next step!

---

**Comment by Sheey11** [comment]
don't just "i am looking forward", pr is the best way to support.

**Comment by Molunerfinn** [comment]
No need, due to time, I will no longer add more new features to hexo-theme-melody after v1.7, mainly to fix bugs. And this issue has nothing to do with the theme itself, I have to close it.
