### ISSUE TITLE
Feature Request: Encrypted Blog

### ISSUE THREAD

**Issue by Magolor** [Molunerfinn/hexo-theme-melody#255]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: v1.5.6**

**Platform:**

**Browser:**

## Feature Request

How about "Encrypted Blog" that only people with password can see?

BTW, Thank you so much for the theme.

---

**Comment by Molunerfinn** [comment]
It's a feature of hexo blog not theme.

https://github.com/MikeCoder/hexo-blog-encrypt
