### ISSUE TITLE
增加公安备案

### ISSUE THREAD

**Issue by wangsijie** [Molunerfinn/hexo-theme-melody#257]
由于这是中文用户才需要的需求，并且难以用英文表达清楚这个术语，所以用了中文。

有些地区（比如上海）已经要求公安备案了，建议配置中增加底部可以填写`公网安备3xxxx`的选项。避免直接修改主题文件造成更新的不方便

**Comment by Molunerfinn** [comment]
这不是有配置能加自定义的文字甚至是HTML么
https://molunerfinn.com/hexo-theme-melody-doc/theme-config.html#since

**Comment by licensor0** [comment]
谢谢您的主题，如果我想要博客备案和谚语共存的话应该怎么做呢

**Comment by licensor0** [comment]
通过footer.pug配置文件知道怎么用了
