### ISSUE TITLE
"You have read -4%" in Safari.

### ISSUE THREAD

**Issue by Sheey11** [Molunerfinn/hexo-theme-melody#258]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
current `master` branch version.

**Platform:**
macOS

**Browser:**
Safari
## Expected behavior 
Show "You have read 0%".
## Actual behavior 
<img width="790" src="https://user-images.githubusercontent.com/13375959/72133802-4ce2f800-33bd-11ea-8163-bfa490e93ee0.png">

## Steps to reproduce the behavior 

Just pull the page down.

---
Safari seems like to move the page position instead of page container when you pull the page out of its top, and the auto hiding feature of header also has a similar bug.

**Comment by Molunerfinn** [comment]
Thanks for finding the bug~
