### ISSUE TITLE
Which version should I set for bump-version?

### ISSUE THREAD

**Issue by Sheey11** [Molunerfinn/hexo-theme-melody#263]
I fixed a bug (img style can effect custom image on footer), then
```
yarn cz
yarn release
```
it ask me which version would I like to bump it, is it `1.7.1`? Or don't `yarn release`, just `git push`?
<img width="623" alt="Screen Shot 2020-02-15 at 1 42 54 PM" src="https://user-images.githubusercontent.com/13375959/74582704-1a4e9f80-4ffa-11ea-88ee-899bb9c54cd6.png">

**Comment by Molunerfinn** [comment]
No, you don't need to bump the version. Just push & open a PR.
