### ISSUE TITLE
对主题的一些建议

### ISSUE THREAD

**Issue by AyagawaSeirin** [Molunerfinn/hexo-theme-melody#266]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**1.7.0

**Platform:**Windows

**Browser:**Chrome

## Expected behavior 
对主题的一些功能建议：
图片Lazyload，加快页面加载效率，比如侧栏的logo，在不显示时就不会主动加载了。
全站PJAX，流畅的访问体验。
夜间模式，暗色模式。
## Feature Request

---

**Comment by Molunerfinn** [comment]
新feature将不再更新了，以修复bug为主。目前正在开发 [vuepress-theme-melody](https://github.com/Molunerfinn/vuepress-theme-melody)，新的特性以后都往那边加入。谢谢建议！
