### ISSUE TITLE
top_img: false is not useful when blog deploy to nginx

### ISSUE THREAD

**Issue by 82kg** [Molunerfinn/hexo-theme-melody#267]
i set top_img: false in melody.yml。
then hexo g & hexo  s
it is good。

but when i use nginx web sever to display this blog。"top_img: false" seems get  lose efficacy!

![TIM截图20200222102609](https://user-images.githubusercontent.com/31686230/75084818-db6e9b80-555d-11ea-80fc-55a10c1ad385.jpg)

![TIM截图20200222102914](https://user-images.githubusercontent.com/31686230/75084854-30121680-555e-11ea-9489-f50187215f56.jpg)

hexo: 4.2.0                                                                                                                      
hexo-cli: 3.1.0                                                                                                                  
os: Linux 4.4.59+ linux x64                                                                                                      
node: 13.8.0                                                                                                                     
melody 1.7
Chromium 74.0.3729.169

**Comment by Kiyo5hi** [comment]
Please follow the format for issues.
To be honest, I do not really it is the config file causing the problem.

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/75085020-ce52ac00-555f-11ea-98bc-37d10ffd4540.png)

**Comment by 82kg** [comment]
sorry , i tryed hexo clean && hexo g。it seems to be ok。
the problem may be cased by the cache。
