### ISSUE TITLE
如何显示网站和文章的访问量？

### ISSUE THREAD

**Issue by codepandy** [Molunerfinn/hexo-theme-melody#268]
看了文档，发现现在无法显示显示网站访问量和文章访问量，能否进行支持？

**Comment by Molunerfinn** [comment]
请好好看文档，是有的。
https://molunerfinn.com/hexo-theme-melody-doc/third-party-support.html#busuanzi
![image](https://user-images.githubusercontent.com/12621342/75431967-a1036500-5988-11ea-90d5-9f0abe6f98ed.png)
