### ISSUE TITLE
Suggention: write `if page.comments` in end

### ISSUE THREAD

**Issue by YunYouJun** [Molunerfinn/hexo-theme-melody#272]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** dev

**Platform:**

**Browser:**

## Feature Request

---

## Suggentions

https://github.com/Molunerfinn/hexo-theme-melody/blob/e7b2a0493f9453762b8112f80cd92d0085a9b438/layout/page.pug#L12-L34

I find `if page.comments` appeared many times.
Maybe we can just write it in end.

```pug
if page.comments !== false
      include includes/comments/index.pug
```

If you think it's right, I can create a PR.
If my opinion is wrong, can you tell me the reason?
Thanks.

**Comment by Molunerfinn** [comment]
The comment component is under different parent nodes. If just use one block in the end of file, will cause style bug. You can have a try :)

**Comment by Molunerfinn** [comment]
If it does not affect after the test, welcome to create a PR

**Comment by YunYouJun** [comment]
I tested it in melody and found no difference in my eyes.
In fact, I use this writng all the time in my custom theme.

**Comment by Molunerfinn** [comment]
> I tested it in melody and found no difference in my eyes.
> In fact, I use this writng all the time in my custom theme.

OK~PR Welcome!
