### ISSUE TITLE
Did melody support footnote syntax in markdown ?

### ISSUE THREAD

**Issue by ShawnWx2019** [Molunerfinn/hexo-theme-melody#274]
## I want to create a new issue  

- [√] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [√] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [√] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [√] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** v1.7.0

**Platform:** macOS

**Browser:** Chrome

## Expected behavior 
I want to add footnote with Markdown syntax like:
```markdown
This is a footnote[^footnote]

[^footnote]: [how to add footnote](https://www.jianshu.com/p/82e730892d42)
```
![In Mweb preview](https://blog-1257599720.cos.ap-shanghai.myqcloud.com/2020/03/10/footnote.png)
![In Mweb preview2](https://blog-1257599720.cos.ap-shanghai.myqcloud.com/2020/03/10/footnote2.png)
## Actual behavior 
Actually, it does not work, you can view my blog: [Shawn の Bioinfo Lab](https://shawnmagic.gitee.io/blog/2020/03/10/undefined.html)
or just like this：
![preview of my blog](https://blog-1257599720.cos.ap-shanghai.myqcloud.com/2020/03/10/footnote3.png)

## Feature Request
Thanks for your masterpiece, I'm enjoy with theme-melody.

Shawn.

---

**Comment by Molunerfinn** [comment]
it's the duty of markdown parser not theme
