### ISSUE TITLE
couldn't generate to .html page and how to input JSON, run it

### ISSUE THREAD

**Issue by tungdao-net** [Molunerfinn/hexo-theme-melody#275]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:last version

**Platform: windows 10 pro

**Browser: chrome

## Actual behavior 
I have two questions as
1. When I use hexo  generate, the page default .md. I tries may time to confirg it but impossible to change to html. So, I would like to know how to change format from .md to .html 
2. I have 3 json file, and would like to input it, that I run localhost it export tags; posts; categories. 
I based on markdown editor of this link https://github.com/zhuochun/md-writer/wiki/Settings-for-Front-Matters. 
Acctually, I tested it on localhost and it still collect tags, categories, posts. However, build on netlify, it unsuccess. 

## Feature Request

---

**Comment by Molunerfinn** [comment]
Ask for Hexo not theme.
