### ISSUE TITLE
 About the support of markdown gramar in text-highlight

### ISSUE THREAD

**Issue by James0608** [Molunerfinn/hexo-theme-melody#276]
## Melody Information
Melody Version: 1.7.0

Platform: Windows

Browser: Chrome

## Expected behavior 
What I confuse is **the support of markdown gramar in text-highlight**。I want to use "==" tag to highlight texts which are seems more important. 
## Actual behavior 
It did works in my *Typora*  Editor, but failed during render website.

It is the screenshot in Typora Editor
![mark](https://cdn.heyhwj.cn/blog/20200315/AF1hCTaf5rS7.png?imageslim)
And the next screenshot is in blog website:
![mark](https://cdn.heyhwj.cn/blog/20200315/jvTAo8EFuIRf.png?imageslim)
## Steps to reproduce the behavior 
Just write something like ==highlight== in .md file and render to melody theme.And view them in website to verify the highlight effect is useful. 
## Feature Request

In my opinion, it is very common needs for blogger to highlight some text when writing blog. So, I sincerely hope the melody theme can support the markdown gramar in test-highlight. Thank you.

**Comment by Molunerfinn** [comment]
It's renderer job not theme.

**Comment by James0608** [comment]
I check the document, then find that theme-melody is using *pug* and *stylus* renderer.Is it possible for me to customize the renderer?Does this mean that I may overwrite the entire architecture?

**Comment by James0608** [comment]
Anyway,thank you very mush to answering my question.

**Comment by Molunerfinn** [comment]
> I check the document, then find that theme-melody is using _pug_ and _stylus_ renderer.Is it possible for me to customize the renderer?Does this mean that I may overwrite the entire architecture?

no, it's the duty of the markdown renderer
