### ISSUE TITLE
script to judge 'ture' is a ture seems to not working

### ISSUE THREAD

**Issue by Sheey11** [Molunerfinn/hexo-theme-melody#277]
## I want to create a new issue
- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.7

**Platform:** macos

**Browser:** chrome

## Expected behavior 
Behave as it should.
## Feature Request

---
I found this in the script:
https://github.com/Molunerfinn/hexo-theme-melody/blob/778ed650200768a25bac3e950c7d1e787df20e07/layout/includes/comments/valine.pug#L7
And I set it to `true` but it's value is still false. Then I tried this:
<img width="141" alt="Screen Shot 2020-04-04 at 2 42 41 PM" src="https://user-images.githubusercontent.com/13375959/78420529-8d7fa400-7682-11ea-8972-346bd8aab9b9.png">
Is it my fault or the theme?

**Comment by Molunerfinn** [comment]
It's a bug of theme.
Need to fix:

```js
var verify = '#{ theme.valine.verify }' == 'true' ? true : false;
```

PR welcome~
