### ISSUE TITLE
可不可以把我的博客加到Demo-Site里面？名称：Flexiston 灵·石  网址：https://www.flexiston.com/

### ISSUE THREAD

**Issue by Flexiston** [Molunerfinn/hexo-theme-melody#279]
## I want to create a new issue  

- [] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Feature Request

---

**Comment by Flexiston** [comment]
[crystalwindz's blog](https://crystalwindz.com/)打不开了

**Comment by Molunerfinn** [comment]
OK, 后续会在文档里开辟一个区域用来放demo-sites.

**Comment by Flexiston** [comment]
对不起，因为某些原因，我不能使用你的主题了，可以把我的网站从 Demo-Sites 移除

**Comment by Molunerfinn** [comment]
> 对不起，因为某些原因，我不能使用你的主题了，可以把我的网站从 Demo-Sites 移除

👌
