### ISSUE TITLE
请教一下

### ISSUE THREAD

**Issue by WAFAU** [Molunerfinn/hexo-theme-melody#28]
**如何调手机端上的顶部图和其他手机端上的东西。还有，那个电脑上的顶部图用url的话怎么调大小。这是我的 `https://wafau.github.io`，谢谢！**

**Comment by Molunerfinn** [comment]
1. 请先阅读[说明文档](https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/theme-config?id=%e9%a1%b6%e9%83%a8%e5%9b%be)，文档里说得很清楚。
2. top_img这个大小是自适应的。如果想要自己改成具体值，自行修改`source/css/_layout/head.styl`下的相关css。
