### ISSUE TITLE
3个建议

### ISSUE THREAD

**Issue by GrapevineLin** [Molunerfinn/hexo-theme-melody#280]
感谢开发者给我们带来精美的主题，我有3个建议：
1. 希望增加文章的更新时间字段
2. 希望支持关闭主题的代码高亮
3. 希望主页的侧边栏支持直接显示出来而不用手动点击

**Comment by Molunerfinn** [comment]
1. 已经有配置 请看文档
2. 不想要高亮就不要包裹代码块
3. 已经有配置 请看文档

**Comment by GrapevineLin** [comment]
sorry

**Comment by GrapevineLin** [comment]
感谢回复。
1. 从配置来看是切换显示的，能否同时显示？
2. 我希望关闭主题的代码高亮而使用第三方的高亮主题(https://github.com/ele828/hexo-prism-plugin)
3. 这个我没看清楚，抱歉

**Comment by Molunerfinn** [comment]
> 感谢回复。
> 
> 1. 从配置来看是切换显示的，能否同时显示？
> 
> 2. 我希望关闭主题的代码高亮而使用第三方的高亮主题(https://github.com/ele828/hexo-prism-plugin)
> 
> 3. 这个我没看清楚，抱歉

1. 不考虑，每个主题有自己的特色
2. 改动会很大，暂不考虑

主题目前以维护bug为主 功能需求暂没时间实现请谅解哈

**Comment by GrapevineLin** [comment]
OK，谢谢
