### ISSUE TITLE
文章版权 -> 文章链接 里的中文显示 URL编码，如何解决？

### ISSUE THREAD

**Issue by AmelieNet** [Molunerfinn/hexo-theme-melody#283]
## 文章版权 -> 文章链接 里的中文显示 URL编码，如何解决？

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** master

**Platform:** Linux

**Browser:** Chrome

## Expected behavior

像这样显示 文章链接的中文  
<https://fridolph.github.io/2018/05/07/【小程序】mpvue开发小程序初体验/>

![1](https://user-images.githubusercontent.com/7888766/84140903-e73a8b00-aa84-11ea-9eef-cbcb1009f657.png)

## Actual behavior 

我的网站不显示中文，直接显示 URL编码  
<http://edwin.cf:8080/2019/12/06/CentOS-7安装最新LNMP/>
![2](https://user-images.githubusercontent.com/7888766/84141017-19e48380-aa85-11ea-9483-67a0dc4ad3e2.png)

## Steps to reproduce the behavior 

---

**我的网站地址：<http://edwin.cf:8080/>**

**Comment by Molunerfinn** [comment]
hexo自动生成的，不考虑解决。
https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/layout/post.pug#L87

**Comment by AmelieNet** [comment]
找到解决办法了，把

<https://github.com/Molunerfinn/hexo-theme-melody/blob/master/layout/post.pug#L87>

的

```
          a(href=url_for(page.permalink)) #[=page.permalink]
```

改为：

```
          a(href=url_for(decodeURI(page.permalink))) #[=decodeURI(page.permalink)]
```

就可以正常显示 URL 了。
