### ISSUE TITLE
图片不会自适应

### ISSUE THREAD

**Issue by Sheey11** [Molunerfinn/hexo-theme-melody#285]
## I want to create a new issue
- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information
**Melody Version:** dev 最新

**Platform:** macOS

**Browser:** Chrome

## Expected behavior 
正常显示。
<img width="976" alt="Screen Shot 2020-06-14 at 10 21 26 AM" src="https://user-images.githubusercontent.com/13375959/84583215-f0cb4680-ae28-11ea-81c1-e8258f1008f5.png">

## Actual behavior 
图片没有自适应。
<img width="967" alt="Screen Shot 2020-06-14 at 10 21 57 AM" src="https://user-images.githubusercontent.com/13375959/84583218-f4f76400-ae28-11ea-87c6-4931e37c9648.png">

## Steps to reproduce the behavior 

在反复试了几次 `git bisect` 之后，都显示是 [`0bafb49`](https://github.com/Molunerfinn/hexo-theme-melody/commit/0bafb49c5abbed35370020a28ed1182bb780161e)(v 1.7.0 推出)的问题。  
我也觉得很奇怪，但是 `git reset --hard` 前后试了下，确实就是这个 commit 的问题。
<img width="946" alt="Screen Shot 2020-06-14 at 10 25 43 AM" src="https://user-images.githubusercontent.com/13375959/84583279-6df6bb80-ae29-11ea-97ba-4f629332906c.png">
这也太玄学了，这两个文件应该不会对 css 有影响。

**Comment by Molunerfinn** [comment]
回头会看看是什么原因，这段时间比较忙

**Comment by plain-dev** [comment]
我也遇到了这个问题，暂时通过修改 **CSS** 解决了

在这里加入了以下代码

https://github.com/Molunerfinn/hexo-theme-melody/blob/3f68b823abeeb4b0c6c916691a3475b91b7f63d7/source/css/_layout/post.styl#L237

```css
img
  max-width: 100%
```

**Comment by Sheey11** [comment]
这条 css 规则是有的
https://github.com/Molunerfinn/hexo-theme-melody/blob/3f68b823abeeb4b0c6c916691a3475b91b7f63d7/source/css/_layout/post.styl#L264
而且实际上最后一次修改的人是我XD
找了下原因，以为是 `.content` 类名改了，导致不生效，结果压根就没有过这个类
不知道为啥当时哈哈哈哈哈，我开个 pr 修了吧

**Comment by Molunerfinn** [comment]
@Sheey11 @plain-dev 赞

**Comment by guoshicheng** [comment]
除了post页面，page页面的图片也不能自适应 @Sheey11

**Comment by qianguyihao** [comment]
是的，文章里的图片没有自适应，麻烦博主抽空解决下。
