### ISSUE TITLE
How to import icons from Alibaba Iconfont 

### ISSUE THREAD

**Issue by Kukmoon** [Molunerfinn/hexo-theme-melody#289]
## I want to create a new issue  

- [X] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [X] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [X] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [X] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**1.8.1

**Platform:**Windows/Android

**Browser:**Firefox

## Expected behavior 

In order to display the bilibili icon in the homepage of my blog, I tried to import a icon library from Alibaba iconfont, according to this page: https://www.antmoe.com/posts/80c43671/

I filled the CSS style sheet file at the [cdn] section in melody.yaml. 
![Snipaste_2020-08-13_15-01-46](https://user-images.githubusercontent.com/16938012/90103944-f932f580-dd75-11ea-9ebb-c66b40bf38cc.png)

Then I tried to quote the bilibili icon at the [social] section in melody.yaml.
![Snipaste_2020-08-13_15-01-46](https://user-images.githubusercontent.com/16938012/90104179-634b9a80-dd76-11ea-85af-f3031e6e6875.png)

I wished the bilibili icon should be displayed as follows:
![Snipaste_2020-08-13_15-06-59](https://user-images.githubusercontent.com/16938012/90104355-b3c2f800-dd76-11ea-8ee7-e1c52ead232b.png)

## Actual behavior 

But it displayed an empty box on my homepage.
![Snipaste_2020-08-13_15-09-18](https://user-images.githubusercontent.com/16938012/90104577-1b794300-dd77-11ea-9bc5-3e3917359957.png)

## Steps to reproduce the behavior 
Just as "Expected Behavior"

## Feature Request

I request that Melody could support Alibaba Iconfont via importing the CSS file it generates. I could display more social icons on my homepage, e.g. bilibili, zhihu, QZone, and etc.

Thanks :-)

---

**Comment by Kukmoon** [comment]
OMG. I mistakenly inserted a wrong picture.

The correct picture and corresponding text is:

Then I tried to quote the bilibili icon at the [social] section in melody.yaml.
![Snipaste_2020-08-13_15-04-06](https://user-images.githubusercontent.com/16938012/90105097-eb7e6f80-dd77-11ea-95aa-1ed0e955e10e.png)

**Comment by Molunerfinn** [comment]
AHA
