### ISSUE TITLE
关于表格的问题

### ISSUE THREAD

**Issue by WAFAU** [Molunerfinn/hexo-theme-melody#29]
无法用markdown语法写表格，然后使用html之后会出现一条很长的空白。
我是这么写的
|命令|官方描述|我的描述|
| :-----  | -----:  | -----:  |
| hexo g  | 部署之前预先生成静态文件  | 在本地保存之前更改的文件配置  |
| hexo d  | 文件生成后立即部署网站  | 把现在已保存的配置文件部署到Github仓库里面  |
| hexo s  | 启动服务器  | 使用服务器预览本地的已被保存的文件  |

**Comment by Molunerfinn** [comment]
这个不是hexo-theme-meldoy的问题，是你markdown写法的问题。表格的前后需要留空行。比如这样

|命令|官方描述|我的描述|
| :----- | -----: | -----: |
| hexo g | 部署之前预先生成静态文件 | 在本地保存之前更改的文件配置 |
| hexo d | 文件生成后立即部署网站 | 把现在已保存的配置文件部署到Github仓库里面 |
| hexo s | 启动服务器 | 使用服务器预览本地的已被保存的文件 |
