### ISSUE TITLE
My hexo-theme-melody pic does not automatically scale

### ISSUE THREAD

**Issue by qingchenldl** [Molunerfinn/hexo-theme-melody#293]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** v1.8.2

**Platform:** macOS 10.15.5

**Browser:** Chrome

## Expected behavior 
If the Picture is too big,like 2048*1284, the hexo-theme-melody should scale the pic,make the page more reasonable, like this:
![](http://image.v0w.top/Blog/2020-09-02-101206.jpg)

You could catch the page in [my firend's Blog](http://j0k3r.top/2020/08/11/java-jndi-inject/)

## Actual behavior 
but now my melody couldn't automatically scale pic like this.
![](http://image.v0w.top/Blog/2020-09-02-100943.jpg)

You could catch the page in [my Blog](https://v0w.top/2020/08/26/CodeAudit-php/)

## Steps to reproduce the behavior 
First, my env is like this:
```
hexo: 5.1.1
hexo-cli: 4.1.0
os: Darwin 19.5.0 darwin x64
node: 12.18.3
v8: 7.8.279.23-node.39
uv: 1.38.0
zlib: 1.2.11
brotli: 1.0.7
ares: 1.16.0
modules: 72
nghttp2: 1.41.0
napi: 6
llhttp: 2.0.4
http_parser: 2.9.3
openssl: 1.1.1g
cldr: 37.0
icu: 67.1
tz: 2019c
unicode: 13.0
```

I through editing `$font-size = 18px` in `melody/source/css/var.styl` change fonts size, but now my melody couldn't automatically scale pic like this.
![](http://image.v0w.top/Blog/2020-09-02-100943.jpg)
To be honest, I dont know if my operation makes this result. However, now my blog is very unattractive and I didn't get some help or find reasons through Internet.

## Feature Request

---
Finally, i like hexo-theme-melody and starred it. Thanks for Author.

**Comment by Molunerfinn** [comment]
try dev branch

**Comment by qingchenldl** [comment]
> try dev branch

Actually, I tried the dev branch and it **change nothing**.After this, I tried my melody version back to 1.6.1 which is my friend used. Now, My blog is running well.

So, because of this issue, I suspect the version 1.8.2(lastest version) **MAY EXIST BUGS**.
Please Check it.Hope the theme gets better and better.

**Comment by Molunerfinn** [comment]
@Sheey11 check check~

**Comment by Sheey11** [comment]
Please `hexo clean` before `hexo g`.

**Comment by qingchenldl** [comment]
> Please `hexo clean` before `hexo g`.

Of course I knowed and did that.

**Comment by Sheey11** [comment]
Can you inspect the page and see did `max-width: 100%;` have affecting the `img` elements?  
I am using the `dev` and it's working properly.

**Comment by qingchenldl** [comment]
When I catched the inssue, i inspected the page and compared the CSS with my friend's, but everything seemed proper. I didn't know why,and front-end isn't my area. I also suspect **MAY My early Archer Theme and git cache cause issue**. If devlopers inspect code and confirm that it's not a bug, I think this issue can close.

**Comment by qingchenldl** [comment]
> Can you inspect the page and see did `max-width: 100%;` have affecting the `img` elements?
> I am using the `dev` and it's working properly.

Frankly,  when i catched the issue, i inspected the page and compared CSS with my friend's, but everything seemed proper, including `max-width: 100%;`. Because Font-end isn't my area, I couldn't make sense whether it run properly or not. I also suspected this issue caused by my early theme--archer and git cache. If Devlopers checks code and find it not caused by code bugs, I think this issue could be closed.

**Comment by Molunerfinn** [comment]
try 1.9.0
