### ISSUE TITLE
{Feature Request] Add full screen API

### ISSUE THREAD

**Issue by LocTran016** [Molunerfinn/hexo-theme-melody#295]
## Feature Request

Hello there, thanks a lot for your theme. Would you mind adding a new feature: When you click on a image/post, that image/post, it will become full screen.

## Why?

Well, this will extremely useful for who want to use the `slides`. Beside this, for those who doesn't have a plan to make a presentation on their blog, it's still good to make the blog fit entire  screen 

## Other relevant information
I have found a small javascript on GitHub for doing that [here](https://github.com/sindresorhus/screenfull.js). May be you can take a look at this. Thanks

**Comment by Molunerfinn** [comment]
This feature you can just do it by yourself with a fork version.
