### ISSUE TITLE
[Feature Request] Add Vssue

### ISSUE THREAD

**Issue by LocTran016** [Molunerfinn/hexo-theme-melody#297]
# Feature Request

Hi, there. Thanks for your wonderful theme. Would you mind adding [Vssue](https://vssue.js.org/guide/#comparison-with-similar-projects)

## Why

1. Hexo has been serving the Vue docs well and Vssue is Vue-powered application
2. Vssue supports Github, Gitlab, Bitbucket, Gitee and Gitea, and can be extended to other platform easily. Gitment and Gitalk only support Github.
3. Vssue is free (no ads) as well

## Other relevant information

Here is my site with a working vssue comment system:

* [The blog](https://loctran016.gitlab.io)
* [The source code](https://gitlab.com/LocTran016/loctran016.gitlab.io)

**Comment by Molunerfinn** [comment]
It will be a default comment plugin in [vuepress-theme-melody](https://github.com/Molunerfinn/vuepress-theme-melody).

If I have time I can add this feature to hexo-theme-melody.

**Comment by LocTran016** [comment]
I have successfully inject the plug-in but there is a small problem:
The comment box is just below the footer_img. Hope that this will be fixed if you add this feature to hexo-theme-melody
