### ISSUE TITLE
Problem with auto-Slide configuarion

### ISSUE THREAD

**Issue by LocTran016** [Molunerfinn/hexo-theme-melody#298]
## I want to create a new issue

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** version 1.8.2

**System:**
    OS: OS X El Capitan 10.11.6
**Binaries:**
    Node: 14.8.0 - /var/folders/0y/f7c873891kz5d_s7qr95vj740000gn/T/yarn--1601029197092-0.1531156558919038/node
    Yarn: 1.22.5 - /var/folders/0y/f7c873891kz5d_s7qr95vj740000gn/T/yarn--1601029197092-0.1531156558919038/yarn
    npm: 6.14.7 - /usr/local/bin/npm
**Browser:** Opera Desktop for Mac

## Expected behavior

The presentation will step through slides automatically

## Actual behavior

![image](https://user-images.githubusercontent.com/64778285/94256662-52d13700-ff54-11ea-963e-6621883737fa.png)

My presentation doesn't step through slides automatically

## Steps to reproduce the behavior
```md
---
title: Biology
date: 2020-09-10 19:57:52
tags: Biology
layout: slides
slide:
  loop: true
  autoSlide: 5000
---

<!-- .slide: data-background="#49B1F5" -->

My content
```

## Other information

* [My blog](https://loctran016.gitlab.io)
* [My source code](https://gitlab.com/LocTran016/loctran016.gitlab.io)

**Comment by Molunerfinn** [comment]
currently don't support this two options.
https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/layout/includes/slide/script.pug

PR Welcome
