### ISSUE TITLE
建议加入valine的评论系统

### ISSUE THREAD

**Issue by sunhailin-Leo** [Molunerfinn/hexo-theme-melody#30]
建议加入valine的评论系统

**Comment by Molunerfinn** [comment]
之后可以考虑支持，也欢迎贡献代码！

**Comment by zouyaoji** [comment]
@Molunerfinn 
嗨，你好。不好意思打扰你拉，我觉得你这主题好看，你的博客评论我都没有号。。（建议可以用Github的号评论，就像这种：https://fedemo.top/2017/12/26/blog_add-https）

不好微信私聊你。就在这儿请教你了。
我也是最近才学习这个博客，我之前都是fork别人的，然后改改就直接能用了。
你这个主题是不是我要自己构建一个hexo的项目，然后用你这个主题？

**Comment by Molunerfinn** [comment]
@zouyaoji melody主题支持`gitment`[评论系统](https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=gitment)，可以用github账号登录。只不过我不是用的gitment罢了。

是的。它把我hexo分支的文件在云端构建，然后推送到master分支。也就是把原本需要在自己本地构建并推送到github的步骤都通过CI帮你完成了。

**Comment by zouyaoji** [comment]
@Molunerfinn 
感谢，我先折腾一下，有不懂的再行请教。

**Comment by zouyaoji** [comment]
@Molunerfinn 
嗨，感谢哈，参考你的博客，用你的主题也做了一个样子出来，
还有些细节我慢慢改。
想请教一下。
1、我是在阿里云注册的域名，修改了dns他提示这个：
![image](https://user-images.githubusercontent.com/24430116/35600355-6d353160-0668-11e8-89c7-56e0acc440d1.png)
不知道有没有影响。
2、像这样指向*.github.io的域名我们需要备案吗？top或者com的域名。

**Comment by Molunerfinn** [comment]
@zouyaoji dns换成别家的时候阿里云都这样，没事。
只要你的域名不是挂在了国内的云服务器上都不需要备案。我的域名也是阿里云的，指向的是github。但是我也没备案。

**Comment by zouyaoji** [comment]
@Molunerfinn 
好的，谢谢。
感觉这样好省事，那我要是把一个小型企业网站（目前没啥功能，纯展示，跟博客差不多）也这样弄，github，不知道有没有不合规合法的地方。

**Comment by Molunerfinn** [comment]
@zouyaoji 除了大家能看到你的源码之外没啥问题。其他有关的问题可以去我的[博客的仓库](https://github.com/Molunerfinn/Molunerfinn.github.io)问，这个是主题的仓库，就不再回答不相关的问题了。

**Comment by sunhailin-Leo** [comment]
@Molunerfinn 我提了PR了 [PR is here](https://github.com/Molunerfinn/hexo-theme-melody/pull/36)

**Comment by Molunerfinn** [comment]
@sunhailin-Leo 感谢！这两天比较忙，还涉及到另外一个bug，我会合并进来的。再次感谢贡献！

**Comment by Molunerfinn** [comment]
@sunhailin-Leo 感谢贡献！bug已经修复完毕，合并入1.4.3版本了~
