### ISSUE TITLE
[Bug] Issue with site put in a subdirectory

### ISSUE THREAD

**Issue by LocTran016** [Molunerfinn/hexo-theme-melody#303]
Although I have set in _config.yml like this:
```yml
url: 'https://loctran016.gitlab.io/chemist'
root: '/chemist/'
```
* [The source code](https://gitlab.com/LocTran016/chemist)
* [My site](https://loctran016.gitlab.io/chemist/)

The site just keep point (direct) to https://loctran016.gitlab.io/... instead of https://gitlab.com/LocTran016/chemist/... which lead to lot's of 404. Can you have a view at this thanks

**Comment by Molunerfinn** [comment]
it's hexo's problem please open an issue on
hexo's repo

**Comment by LocTran016** [comment]
> it's hexo's problem please open an issue on
> hexo's repo
Oh, sorry I forgot to tell you that this issue happen to _config.melody.yml:
![image](https://user-images.githubusercontent.com/64778285/95321286-0aefcf80-08c5-11eb-9324-fd7877d31944.png)
