### ISSUE TITLE
[BUG] It's seemed some css don't load

### ISSUE THREAD

**Issue by QingxuMo** [Molunerfinn/hexo-theme-melody#307]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version: the lastest version installed by npm**

**Platform: Android**

**Browser: Chrome**

## Expected behavior 
Normal
## Actual behavior 
 The results are as follows
![Screenshot](https://one.qingxu.ga/pictures/Pictures/f4061cc754ae7892797f8cd5bc4eb1e4.jpg)
## Steps to reproduce the behavior 
I just configure Melody for the first time and try `hexo s`, then find something seemed don't works (maybe because of css).

I try `hexo s --debug`, but no error with.

**Comment by Molunerfinn** [comment]
Can't reproduce.

![image](https://user-images.githubusercontent.com/12621342/97070073-e6eff600-1607-11eb-94c9-1b8fb67c3c18.png)

Please provide an online site.

**Comment by Molunerfinn** [comment]
And it seems your network's problem. try to find a new CDN link to load the font resource:

![Uploading image.png…]()

**Comment by QingxuMo** [comment]
> And it seems your network's problem. try to find a new CDN link to load the font resource:
> ![image](https://user-images.githubusercontent.com/12621342/97070113-5d8cf380-1608-11eb-990e-b1c87fc3fbce.png)

Sorry, I replaced https://cdn.jsdelivr.net/npm/font-awesome@latest/css/font-awesome.min.css  with https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free/css/all.min.css. I guess it can also work well but not 😂😂

**Comment by sumshare** [comment]
jsdelivr现在被墙了咋办

**Comment by Molunerfinn** [comment]
> jsdelivr现在被墙了咋办

你换个cdn提供的就好了
