### ISSUE TITLE
文章列表的图片是怎么弄出来的呀？

### ISSUE THREAD

**Issue by sunhailin-Leo** [Molunerfinn/hexo-theme-melody#31]
我markdown里面加了图片,但是外面没有图.

就像你的例子那个《无问西东》那一个是怎么做出来的？

**Comment by Molunerfinn** [comment]
如果是文章里的图片无法显示，用markdown的图片语法，`![](http://xxxxxx.jpg)`圆括号里的是图片的url。
如果是首页，文章只显示了`阅读更多`的按钮话，你需要在你的文章里加入`<!-- more -->`标记来标记`阅读更多`这个按钮所在的位置。
你可以参考我那篇文章的写法：
地址是https://raw.githubusercontent.com/Molunerfinn/Molunerfinn.github.io/hexo/source/_posts/PerfectMoviePerWeek5.md
