### ISSUE TITLE
Render error

### ISSUE THREAD

**Issue by flier268** [Molunerfinn/hexo-theme-melody#310]
## Melody Information

**Melody Version:**
1.9

**Platform:**
Windows

**Browser:**
Firefox and Chrome

![圖片](https://user-images.githubusercontent.com/19989232/99344672-8cc31780-28cb-11eb-925b-a08febc0f465.png)

It should have 4 points but 2 in the center of picture

**Comment by Molunerfinn** [comment]
it's renderer's problem not melody

**Comment by flier268** [comment]
But other theme does not has this problem
