### ISSUE TITLE
[Issues] hljs is not defined, Reveal.initialize({dependencies:[]}) will deprecated (4.*).

### ISSUE THREAD

**Issue by mrluffya** [Molunerfinn/hexo-theme-melody#320]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:**
1.9.0

**Platform:**
macOS 10.13.6 (High Sierra)

**Browser:**
Firefox

## Expected behavior 
运行hexo服务后，使用幻灯片插件显示正确内容。

translator love u
>After running the hexo service, use the slideshow plugin to display the correct content.

## Actual behavior 
运行hexo服务后，使用幻灯片插件未显示内容。
Firefox -> Web控制台，显示 `Uncaught ReferenceError: hljs is not defined`

translator love u
>After running the hexo service, the content is not displayed using the slideshow plugin.
Firefox -> Web console, display `Uncaught ReferenceError: hljs is not defined`.

#### Screenshots
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/23006292/103194298-2c87b280-491a-11eb-8262-6b99eeec6800.png">

## Steps to reproduce the behavior 
```sh
$ cd src/hexo
$ hexo init
$ hexo new draft hello-slides
$ vi source/__drafts/hello-slides
---
title: hello-slides
tags: 默认标签
categories: 默认分类
date: 2020-12-28 12:15:41
layout: slides
---

### 这是一份草稿

### hexo-theme-melody <small>v1.5</small>
<!-- .slide: data-background="#49B1F5" -->

Supports iframe & slides. You can use a layout called `slides` to enabled the slides layout.

Also you can add a `iframe` front-matter with the `slides` layout in your `md` file to enable the iframe page.

### Steps
<!-- .slide: data-transition="concave" data-background="#C7916B" -->

#### 1. Add a slides page

// ......

==

// ......

===

#### 2. Add the layout type
<!-- .slide: data-transition="fade" data-background="#00C4B6" -->

// ......

$ # [hexo-theme-melody#218](https://github.com/Molunerfinn/hexo-theme-melody/issues/218)
$ # 尝试修改timeout为10000，依然报错。
$ # translator love u
$ # >attempt to modify the timeout of 10,000, is still an error.
$ hexo clean && hexo s --draft
```

## Feature Request

参考 [Docs: reveal plugins](https://revealjs.com/plugins/#dependencies) 进行如下修改后`内容正常显示：`

translator love u
>Refer to Docs: reveal plugins and make the following modifications to `display the content normally:`

`node_modules/hexo-theme-melody/layout/includes/slide/script.pug`
```nodejs
......
script(src=url_for("https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/markdown/markdown.js"))
script(src=url_for("https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/highlight/highlight.js"))
......
    plugins: [
......
    // Markdown
    RevealMarkdown,
    // Highlight
    RevealHighlight,
    ],
    dependencies: [
      //- { src: 'https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/markdown/markdown.js', condition: function() { return !!document.querySelector( '[data-markdown]' ); } },
      // Syntax highlight for <code> elements
      //- { src: 'https://cdn.jsdelivr.net/npm/reveal.js@latest/plugin/highlight/highlight.js', async: true, callback: function() {
      //-   // issue #218
      //-   setTimeout(function () {
      //-     hljs.initHighlighting();
      //-   }, 0)
      //- } },
    ]
  });

script.
  console.log(
    "plugins search: ", Reveal.hasPlugin( 'search' ),
    ", plugins markdown: ", Reveal.hasPlugin( 'markdown' ),
    ", plugins highlight: ", Reveal.hasPlugin( 'highlight' ),
  );
```

#### Screenshots
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/23006292/103195283-ec75ff00-491c-11eb-8002-bb93c4c37b95.png">

**Comment by Molunerfinn** [comment]
has already fix by this commit: https://github.com/Molunerfinn/hexo-theme-melody/commit/7b4993f2525a2e8e9494d6402c89c1a10f51a5a1

I'll release a subversion ASAP

**Comment by mrluffya** [comment]
thank's for reply @Molunerfinn :)
