### ISSUE TITLE
Can the updated information be displayed in the future？

### ISSUE THREAD

**Issue by ImAmelie** [Molunerfinn/hexo-theme-melody#326]
## I want to create a new issue
- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** 1.9.0

**Platform:** Windows and Linux

**Browser:** Chrome

## Feature Request

Can the article show the updated time(not create time) ?

```markdown
---
title: article
date: 2021-04-01 00:00:00
tags:
categories:
  - [Others]
updated: 2021-04-24 20:24:00
---
```
Can the `updated` information be displayed in the future？

**Comment by Molunerfinn** [comment]
https://molunerfinn.com/hexo-theme-melody-doc/theme-config.html#post-meta

![image](https://user-images.githubusercontent.com/12621342/115962263-121eb800-a54d-11eb-99c5-0adf06fba4bc.png)
