### ISSUE TITLE
关于分类的问题

### ISSUE THREAD

**Issue by ZhangYuAFA** [Molunerfinn/hexo-theme-melody#33]
如何进行子分类，在你的主题配置文章中没有找到相关提示，谢谢

**Comment by Molunerfinn** [comment]
不知道你说的子分类值得是什么。
如果是指主题右上角的那几个比如`tags`、`categories`页面，我在说明文档里已经说得很清楚了：[导航菜单](https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/theme-config?id=%e5%af%bc%e8%88%aa%e8%8f%9c%e5%8d%95)
如果你说的是文章的分类，那么这个是Hexo的基本知识，跟主题本身无关。
比如：
```
title: 全栈开发实战：用Vue2+Koa1开发完整的前后端项目（更新Koa2）
tags: 
  - 前端
  - Nodejs
categories:
  - Web
  - 开发
  - Nodejs
date: 2017-05-03 14:09:00
---
```
上面的categories下面的三个就是文章的分类，而且是有层级关系的。不谢。
