### ISSUE TITLE
Want Waline support

### ISSUE THREAD

**Issue by zhullyb** [Molunerfinn/hexo-theme-melody#330]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:** latest

**Platform:** Linux

**Browser:** Firefox

## Feature Request

Waline is a simple comment system inspired by Valine.
With a backend, we can manage the comment more conveniently.
![图片](https://user-images.githubusercontent.com/43305366/134159072-315f7995-0036-4df8-9bbd-dc71e494b6ac.png)

---

**Comment by Molunerfinn** [comment]
Thanks for contribution!
