### ISSUE TITLE
求助，博客首页没有文章的预览

### ISSUE THREAD

**Issue by G-BlueSummer** [Molunerfinn/hexo-theme-melody#34]
现在博客配置的差不多了，感觉这个主题挺漂亮的，但是博客首页的文章没有预览，只剩个标题，求解

**Comment by Molunerfinn** [comment]
参考这个[issue](https://github.com/Molunerfinn/hexo-theme-melody/issues/31)
你需要手动在需要预览的部分后加`<!-- more -->`标记。
