### ISSUE TITLE
1.9.1版本下中文目录无法跟随问题

### ISSUE THREAD

**Issue by chris3687994** [Molunerfinn/hexo-theme-melody#343]
## I want to create a new issue  

- [x] Yes, I have read [FAQ](https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/FAQ.md).
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this did not help me.

## Melody Information

**Melody Version:1.9.1**

**Platform:Windows**

**Browser:Chrome**

## Expected behavior 
阅读文章时章节自动跟随，点击目录可以正常跳转。
## Actual behavior 
阅读文章时目录未跟随，点击目录未发生跳转

![image](https://user-images.githubusercontent.com/31602785/208292297-4ebb2c4f-6ee0-4634-83c3-7defb81b9942.png)
我查阅了以往的issues，发现在说是这个问题在1.8.2之后修复，我是9月29日安装1.9.1版本，在使用目录功能时发现这个问题依然存在
![image](https://user-images.githubusercontent.com/31602785/208292272-af3ae2a9-6dc7-4b75-a432-6c844908770d.png)
## Steps to reproduce the behavior 
请访问https://flag.life/2022/12/16/Migrate-And-Update-Hexo-Blog-From-Travis-Cl-to-Github-Action  这篇文章

---

**Comment by Molunerfinn** [comment]
你的版本依然是1.6.1而不是1.9.1，请确保升级。

![image](https://user-images.githubusercontent.com/12621342/208295561-e6400faf-6834-43b9-8d16-a00d8d8ecede.png)


注意看你的仓库里的这个文件跟 melody 的这个文件的区别：

https://github.com/chris3687994/chris3687994.github.io/blob/master/js/scroll.js

https://github.com/Molunerfinn/hexo-theme-melody/blob/master/source/js/scroll.js

**Comment by chris3687994** [comment]
谢谢作者，最后发现是hexo工作目录下有旧的/theme目录，造成最新版本的主题没有生效，删除后恢复正常。
