### ISSUE TITLE
sharejs与目录列表冲突

### ISSUE THREAD

**Issue by jenkey2011** [Molunerfinn/hexo-theme-melody#37]
如题，如果设置sharejs为true，则右侧目录无法跟随，也无法展开~
```
sharejs:
  enable: true
```
重现： http://wangqizheng.win

**Comment by Molunerfinn** [comment]
收到，正在排查问题~

**Comment by Molunerfinn** [comment]
@jenkey2011 另外我发现你深度修改的melody主题有些地方挺值得我借鉴的哈哈。下一版估计有些地方我要做些微调~

**Comment by jenkey2011** [comment]
@Molunerfinn  大神抬爱啊  哈哈
最近想跳槽，临时搬迁博客。
准备自己做主题了，到时候不会的再请教大神您~
