### ISSUE TITLE
我的代码高亮效果有问题，背景有了但是字母没有

### ISSUE THREAD

**Issue by WinstonJie** [Molunerfinn/hexo-theme-melody#42]
我的代码高亮效果有问题，背景有了但是字母没有

**Comment by Molunerfinn** [comment]
代码需要手动指定你的语言是什么。在```后加上你的语言信息。
比如
![image](https://user-images.githubusercontent.com/12621342/37251533-c3cd5d7e-254c-11e8-9327-fbe80c710cb3.png)
