### ISSUE TITLE
Unhandled rejection TypeError

### ISSUE THREAD

**Issue by zaicoffee** [Molunerfinn/hexo-theme-melody#43]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**v1.5.0

**Platform:** macOS 10.11.6

**Browser:**Chrome

## Expected behavior 
when I run`$ hexo s`
I expected the website can run smoothly on http://localhost:4000/

## Actual behavior 
but the error appears that:
```
Unhandled rejection TypeError: .../hexo-files/themes/melody/layout/includes/layout.pug:31
    29|       each url in theme.stylesheets
    30|         link(rel='stylesheet', href=url)
  > 31|     each item in theme.cdn.css
    32|       if item !== undefined
    33|         link(rel='stylesheet', href=item + '?version=' + version())
    34|     include ./head.pug

Cannot read property 'css' of undefined
```

![image](https://user-images.githubusercontent.com/37335884/37355886-ba7f4604-271f-11e8-8b66-a0580e7c81af.png)

and I don't know how to deal with this situation, plz help

**Comment by Molunerfinn** [comment]
What's your config file of theme-melody? Is `_config.yml` or `melody.yml` ？Please put your config file detail here.

**Comment by Molunerfinn** [comment]
Closed. If you support more detail info then I will reopen it.
