### ISSUE TITLE
搜索以及一些疑问

### ISSUE THREAD

**Issue by WinstonJie** [Molunerfinn/hexo-theme-melody#46]
感谢您美丽的主题，
我的搜索引擎algolia比较奇怪，输入什么都没有反应
以及如果我想在如图的地方设置分类和标签，您能教我改一下吗？
http://img-blog.csdn.net/20180317205603657?watermark/2/text/Ly9ibG9nLmNzZG4ubmV0L2Zlbmd5aW5namllMg==/font/5a6L5L2T/fontsize/400/fill/I0JBQkFCMA==/dissolve/70
以及在上面怎么设置描述，即主页面中标题下面的文字描述。如果方便，能索要你的qq吗

**Comment by WinstonJie** [comment]
抱歉我不会怎么使用那个i什么的，请原谅

**Comment by Molunerfinn** [comment]
请按issue模板提交issue。不按issue模板提交的issue会被关闭。
