### ISSUE TITLE
一些问题

### ISSUE THREAD

**Issue by WinstonJie** [Molunerfinn/hexo-theme-melody#47]
## I want to create a new issue  

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

最新的

**Platform:**

Windows

**Chrome:**

## Expected behavior 
感谢您美丽的主题，
我的搜索引擎algolia比较奇怪，输入什么都没有反应
以及如果我想在如图的地方设置分类和标签，您能教我改一下吗？
以及在上面怎么设置描述，即主页面中标题下面的文字描述。如果方便，能索要你的qq吗
## Actual behavior 

这里有张图片，就是上图
http://blog.csdn.net/fengyingjie2/article/details/79595625

## Feature Request

---

给star了

**Comment by Molunerfinn** [comment]
请问您是不会看模板么。文档您都看了么？你的图我也根本打不开:)
![image](https://user-images.githubusercontent.com/12621342/37556254-44cea1f4-2a2e-11e8-86b4-9b25d82fdb2b.png)

**Comment by Molunerfinn** [comment]
1. algolia 的问题不属于Melody主题的范畴。主题只负责配置api对接。如果实在不行推荐用localsearch，简单省事。
2. 没有那么多时间去教每个用户自定义什么东西。想自定义主题就自己fork主题自己去修改。
3. 你所说的这个`文字描述`，我在文档里已经给出，请阅读：
https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/theme-config?id=%E8%87%AA%E5%8A%A8%E8%8A%82%E9%80%89
如果不是最新的请ctrl+f5刷新页面。
![image](https://user-images.githubusercontent.com/12621342/37556376-12520048-2a30-11e8-9a2d-5d82f71fc771.png)
