### ISSUE TITLE
hexo g的时候报错

### ISSUE THREAD

**Issue by AmazingMoon** [Molunerfinn/hexo-theme-melody#5]
![image](https://user-images.githubusercontent.com/23205097/32591889-f89c347e-c4e6-11e7-9f9b-8d16054dc442.png)

**Comment by Molunerfinn** [comment]
尝试更新一下你的pug和hexo-renderer-jade的版本。贴上你的node以及pug版本。我这边node7.6以上都是没问题的

**Comment by AmazingMoon** [comment]
@Molunerfinn 谢谢！ 依赖全部删除，重新装了一下好了

**Comment by Molunerfinn** [comment]
:+1:  :）
