### ISSUE TITLE
安装好你的主题后path报错

### ISSUE THREAD

**Issue by wudiansi** [Molunerfinn/hexo-theme-melody#54]
## I want to create a new issue  

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**
1.5.1

**Platform:**
windows

**Browser:**
chrome 63.0.3239.108
## Expected behavior 
Cannot read property 'path' of undefined
TypeError: D:\hexo\themes\melody\layout\includes\config.pug:1
  > 1| -
    2|   var algolia;
    3|   var env = process.env;
    4|   if (theme.algolia_search.enable) {

## Steps to reproduce the behavior 
1.hexo init
2.npm install
3.git clone -b master https://github.com/Molunerfinn/hexo-theme-melody themes/melody
4.npm install hexo-renderer-jade hexo-renderer-stylus
5.hexo clean
6.hexo g
报错
这是我的主题配置文件
`# html lang
# ---------------
language: en

# Main menu navigation
# ---------------
menu:
  Home: /
  Archives: /archives
  Tags: /tags
  Categories: /categories
  #XXX: /xxx

# Favicon
# ---------------
favicon: /favicon.ico

# PWA
# ---------------
pwa:
  enable: false
  manifest: 

# Highlight theme
# ---------------
highlight_theme: default

# Nav settings
# ---------------
social:
  github: https://github.com/wudiansi
  weibo: http://weibo.com/

# Algolia search
# ---------------
algolia_search:
  enable: false
  hits:
    per_page: 10
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"
    hits_stats: "${hits} results found in ${time} ms"

# Local search
# ---------------
local_search:
  enable: true
  labels:
    input_placeholder: Search for Posts
    hits_empty: "We didn't find any results for the search: ${query}"

# MathJax
# ---------------
mathjax:
  enable: false
  cdn: https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-AMS-MML_HTMLorMML

# Toggle fireworks (IE >= 10)
# ---------------
fireworks: true

# Analysis
# ---------------
baidu_analytics: ae5927bb06d24dba44171a1f86c5a788

google_analytics: UA-116838574-1

# stylesheets loaded in the <head>
# ---------------
stylesheets:
- /css/index.css

# scripts loaded in the end of the body
# ---------------
scripts:
- /js/utils.js
- /js/fancybox.js
- /js/sidebar.js
- /js/copy.js
- /js/fireworks.js
- /js/transition.js
- /js/scroll.js
- /js/head.js

# cdn for third-party library
# ---------------
cdn:
  css:
    fontawesome: https://cdn.staticfile.org/font-awesome/4.7.0/css/font-awesome.min.css
  js:
    anime: /js/third-party/anime.min.js
    jquery: /js/third-party/jquery.min.js
    fancybox: /js/third-party/jquery.fancybox.min.js
    velocity: /js/third-party/velocity.min.js 
    velocity-ui: /js/third-party/velocity.ui.min.js 

# Post info settings
# ---------------
avatar: http://wyxj.cume.cc/command/WeiPhoto/public/img/102.img

top_img: /img/wallhaven.jpg # false or url of img 

post_meta:
  date_type: created # created or updated 
  categories: true
  tags: true

wordcount:
  enable: true

toc:
  enable: true

post_copyright:
  enable: true
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

auto_excerpt:
  enable: true
  length: 150

# slide
# For reveal.js config, see https://github.com/hakimel/reveal.js#configuration
slide:
  separator: ---
  separator_vertical: --
  charset: utf-8
  theme: black
  # optional
  mouseWheel: false
  transition: slide
  transitionSpeed: default
  parallaxBackgroundImage: ''
  parallaxBackgroundSize: ''
  parallaxBackgroundHorizontal: null
  parallaxBackgroundVertical: null

QR_code:
  - itemlist:
      img: /img/alipay.jpg
      text: 支付宝打赏
  - itemlist:
      img: /img/wechat.jpg
      text: 微信打赏      

# adv:
  # enable: false
  # info: 

# Share System
# ---------------
addThis:
  enable: true
  pubid: ra-5ac1cdb672a640e8

# sharejs:
  # enable: false
  # disabled_sites: 

# Comments System
# ---------------
disqus:
  enable: true
  shortname: disqus_hWLNnarbNk
  count: true

# laibili:
  # enable: false
  # uid:

# gitment
  # enable: false
  # owner: 
  # repo: 
  # client_id: 
  # client_secret: 

# gitalk:
#   enable: false
#   client_id: 
#   client_secret: 
#   repo:
#   owner:
#   admin:

# valine comment system. https://valine.js.org
# valine:
#   enable: false # if you want use valine,please set this value is ture
#   appId:  # leancloud application app id
#   appKey:  # leancloud application app key
#   notify: false # valine mail notify (true/false) https://github.com/xCss/Valine/wiki
#   verify: false # valine verify code (true/false)
#   pageSize: 10 # comment list page size
#   avatar: mm # gravatar style https://valine.js.org/#/avatar
#   lang: zh-cn # i18n: zh-cn/en
#   placeholder: Just go go # valine comment input placeholder(like: Please leave your footprints )
#   guest_info: nick,mail,link #valine comment header inf

# Footer Settings
# ---------------
since: 2016

ICP:
  enable: false
  #text: 

# busuanzi count for PV / UV in site
busuanzi:
  # count values only if the other configs are false
  enable: true
  # custom uv span for the whole site
  site_uv: true
  site_uv_header: <i class="fa fa-user"></i>
  site_uv_footer:
  # custom pv span for the whole site
  site_pv: true
  site_pv_header: <i class="fa fa-eye"></i>
  site_pv_footer:
  # custom pv span for one page only
  page_pv: true
  page_pv_header: <i class="fa fa-file-o"></i>
  page_pv_footer:

# Sidebar Settings
# ---------------
links_title: Links
links:
  前端情报局: https://news.awesomes.cn/
  merrier说: http://merrier.wang/
  邱庆羽: http://www.qiuqingyu.cn
`

## Feature Request

按照你的文档引入了你的主题，也安装了jade stylus ，但是无论我如何实现安装，都会有上面的错误提示。
---

**Comment by Molunerfinn** [comment]
我注意到你开启了`localSearch`这个功能，但是你是否没有注意到，localSearch也是需要额外安装东西的呢？
![image](https://user-images.githubusercontent.com/12621342/38242062-63ce5438-3766-11e8-9375-256d87d0adfc.png)
文档里写得很清楚，你需要相应的配置。开启任何功能都需要看看是否需要安装额外的插件。
https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/third-party-support?id=%E6%9C%AC%E5%9C%B0%E6%90%9C%E7%B4%A2
装完应该就没问题了。

**Comment by wudiansi** [comment]
感谢 解决了，确实是这个问题。自己太粗心了。
其他很多普通的主题用的人太多了，然后作者的主题很心水。
支持作者

还有一个问题 跳转详情页面的时候 会有count的报错 但是这个不是没有依赖吗 还是说这个目录格式要修改什么
   30|             .post-meta-wordcount
    31|               span= _p('post.wordcount') + ': '
  > 32|               span.word-count= wordcount(page.content)
    33|               span.post-meta__separator |
    34|               span= _p('post.min2read', min2read(page.content, {cn: 350, en: 160}))
    35|   else

这是跳转的目录
http://localhost:4000/2018/04/03/hello-world/

**Comment by Molunerfinn** [comment]
@wudiansi 你启用了word_count的功能也需要额外安装东西...
https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/additional-package-support?id=%E5%AD%97%E6%95%B0%E7%BB%9F%E8%AE%A1
![image](https://user-images.githubusercontent.com/12621342/38250031-4071ff8e-3780-11e8-92d4-02f368749dda.png)
