### ISSUE TITLE
highlight_theme: default

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#55]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.1

**Platform:**  Ubuntu 17.10

**Browser:** Chrome Version 65.0.3325.181 (Official Build) (64-bit)

## Expected behavior  & Actual behavior 
文档中 [Theme Config](https://molunerfinn.com/hexo-theme-melody-doc/#/theme-config?id=highlight-theme)部分`highlight: default`在`melody.yml`中变为了`highlight_theme: default`

是否应该修改一下文档？

**Comment by Molunerfinn** [comment]
My fault! Thank you very much! I've fixed it~
