### ISSUE TITLE
Long post  preview problem

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#57]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.1

**Platform:** Ubuntu 17.10

**Browser:** Chrome

## Expected behavior && Actual behavior 

I have **a long post** [here](http://paste.upupming.site/2018-03-12-the-nature-of-research.md). When I run 
```
$ hexo s
```
The page is blank(I tested on both chrome and firefox): 
![screenshot from 2018-04-05 18-24-12](https://user-images.githubusercontent.com/24741764/38361070-bb397d94-38fe-11e8-8156-462b28d8bbf8.png)

There is no error/warning in the chrome console. After I run `hexo g; hexo d`, the page is ok on github pages:
![screenshot from 2018-04-05 18-29-23](https://user-images.githubusercontent.com/24741764/38361237-4f554634-38ff-11e8-89c9-1e5e355353d5.png)

After I made the post shorter, it can be previewed(`hexo s`) as normal:
![screenshot from 2018-04-05 18-36-25](https://user-images.githubusercontent.com/24741764/38361524-4b0372c6-3900-11e8-8584-c7a6f8a3837e.png)

## Personal option

I think this is a bug of melody, since I didn't encounter this kind of thing when I use the default landscape theme. 
![screenshot from 2018-04-05 18-39-13](https://user-images.githubusercontent.com/24741764/38361625-aa296f4e-3900-11e8-9727-8664f0a6ae37.png)

However, I am new to hexo and frontend, perhaps I leave out some nodejs packages? This is my `package.json` file:
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.7.0"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-algoliasearch": "^0.3.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-git": "^0.3.1",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.2",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-sitemap": "^1.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-offline": "^0.2.3",
    "hexo-render-pug": "^2.0.0",
    "hexo-renderer-ejs": "^0.3.0",
    "hexo-renderer-jade": "^0.4.1",
    "hexo-renderer-marked": "^0.3.0",
    "hexo-renderer-stylus": "^0.3.3",
    "hexo-server": "^0.2.2",
    "hexo-wordcount": "^3.0.2"
  }
}
```

@Molunerfinn Thank you for your fast reply, I learnt a lot from you.!:kissing:

Best wishes!

**Comment by Molunerfinn** [comment]
No, it's not the problem of melody. It's the hexo server [problem](https://github.com/hexojs/hexo-server/issues/23).

Solution:

In your hexo site `_config.yml`：

```yaml
server:
  compress: true
```
