### ISSUE TITLE
你好，能否移植farbox-theme-cais

### ISSUE THREAD

**Issue by jerry011235** [Molunerfinn/hexo-theme-melody#6]
你好，发现一个主题挺好看的，能否移植到hexo？也是用`jade`写的。
https://github.com/hi-caicai/farbox-theme-cais

**Comment by Molunerfinn** [comment]
没有精力维护两份主题，如果你有想法当然可以移植过来。可以参考我这篇[文章](https://molunerfinn.com/make-a-hexo-theme/)
