### ISSUE TITLE
 search icon trigger Algolia immediately

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#60]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.1

**Platform:** Ubuntu 17.10

**Browser:** Chrome

## Expected behavior  && Actual behavior 
Like you, I use Algolia for search in [my blog](https://blog.upupming.site/). I found that after I click the magnifying glass icon:
![in real open source you have the right to control your own destiny upupming](https://user-images.githubusercontent.com/24741764/38453298-cadbcc38-3a85-11e8-9232-4e99bf7239be.png)
The search bar isn't focused: 
![2](https://user-images.githubusercontent.com/24741764/38453303-ee90d84e-3a85-11e8-8d0b-4960aa3e5155.png)
It means that I have to click the search bar once more before I can input words for search, it's not convenient, can you focus cursor on the search bar immediately after I click the magnifying glass icon?

Thanks!

**Comment by Molunerfinn** [comment]
Done.
