### ISSUE TITLE
第2页后，slider iframe地址错误

### ISSUE THREAD

**Issue by Fridolph** [Molunerfinn/hexo-theme-melody#63]
## 已找到了具体原因  

出错的页面 https://fridolph.github.io/page/2/

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.2

**Platform:** all

**Browser:** all

## Expected behavior 

希望能正常加载数据

## Actual behavior 

![](http://p7469686a.bkt.clouddn.com/2.png)

![](http://p7469686a.bkt.clouddn.com/1.png)

## Steps to reproduce the behavior 

出现原因 

```pug
mixin slideIframe(url)
  .content
    iframe(src=url frameborder="0")

mixin postSlideIframe(url)  
  .post-iframe
    iframe(src=url frameborder="0")
```

首页path是 /2018/4/13/文章名

当到了第2页，url 路径会带上 /page/2 这样的前缀  -> 导致 加载的地址变成了上图 带上了page的url
当翻到后面几页时，去掉page的就好了

---
pug里 不知怎么改这个逻辑 我考虑的是写个正则

```js
let url = 'http://fridolph.wang/page/2/2018/4/03/你的名字.html'
if(url.match(/\/page\/\d+/g)) {
  url.replace(/(\/page\/\d+)/g, '')
  // url = 'http://fridolph.wang/2018/4/03/你的名字.html'
}
```

## Feature Request

很喜欢这个主题，一直关注着，希望melody会更好~ 

---

**Comment by Molunerfinn** [comment]
收到反馈，这个问题我会尽快修复。
