### ISSUE TITLE
Language configuration does not take effect

### ISSUE THREAD

**Issue by TechOtaku2233** [Molunerfinn/hexo-theme-melody#64]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version: master 1.5.2 and dev 1.5.2**

**Platform: Windows**

**Browser: Chrome**

## Expected behavior 
Change language to Chinese
```
# html lang
# ---------------
language: zh-Hans
```
## Actual behavior 
Language configuration does not take effect
![](http://p72fe522l.bkt.clouddn.com/18-4-13/85856810.jpg)
![](http://p72fe522l.bkt.clouddn.com/18-4-13/65903705.jpg)
My solution is to rename the language file zh-Hans.yml to default.yml, This method can solve the problem, but it is not perfect

## Feature Request

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/38731390-98dc443a-3f4c-11e8-8390-765d5cd18f09.png)
language setting is in the hexo site `_config.yml` not the melody config file.

**Comment by TechOtaku2233** [comment]
Thank you, I was too careless
________________________________
Sent from YoMail<http://www.yomail.com/?utm_source=signature>

发件人： PiEgg<mailto:notifications@github.com>
发送时间： 2018-04-13 18:58:32
收件人：  Molunerfinn/hexo-theme-melody<mailto:hexo-theme-melody@noreply.github.com>
抄送：  徒然<mailto:pengjunting@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [Molunerfinn/hexo-theme-melody] Language configuration does nottake effect (#64)

Closed #64<https://github.com/Molunerfinn/hexo-theme-melody/issues/64>.
