### ISSUE TITLE
提一个关于生成网页标题逻辑的建议

### ISSUE THREAD

**Issue by imhanjie** [Molunerfinn/hexo-theme-melody#65]
根据在 `melody/layout/includes` 下的 `layout.pug` 文件内生成的网页标题的逻辑，在博客首页时，标题应为 Hexo 的 `subtitle | title ` ，但如果没有配置 Hexo 的 subtitle 而配置了 title 的情况下，首页会显示为 ` | title `，觉得显示不美观，所以建议判断下 | 的前面是否为空，如果为空就不要显示 | 了。
贴下代码：
```
if (pageTitle == '') { pageTitle = config.title } else { pageTitle += ' | ' + config.title }
```

**Comment by Molunerfinn** [comment]
感谢建议，已经修复。下次提issue的时候请按issue模板来~
