### ISSUE TITLE
Would it be possible for theme-melody to support hexo-renderer-pug instead of jade?

### ISSUE THREAD

**Issue by hesongtao96** [Molunerfinn/hexo-theme-melody#66]
When I tried to install hexo-renderer-jade, the npm said it was deprecated since _jade_ had been renamed as _pug_ due to the copyright issue. Then, I tried to install pug install of jade and ran _hexo server_ , it reported many errors and I didn't know how to deal with it. Therefore, would it be possible for melody to support hexo-renderer-pug instead of _jade_ so that we could use the latest features of pug? Anyway, thanks for your wonderful job~

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information
**Melody Version:1.5.3
**Platform:Windows 10
**Browser:Chrome

**Comment by Molunerfinn** [comment]
`hexo-renderer-jade` is a jade & pug renderer supported by official Hexo group. It supports both jade & pug. Theme-melody uses pug as the template lang. So you don't need to worry about that.
