### ISSUE TITLE
提交了，创建了分支,删除了.git文件。git push Everything up-to-date

### ISSUE THREAD

**Issue by xcsweb** [Molunerfinn/hexo-theme-melody#69]
![image](https://user-images.githubusercontent.com/20693737/39047474-911611ce-44cc-11e8-86f6-d83d32aa5ef7.png)
![image](https://user-images.githubusercontent.com/20693737/39047491-9f149a2a-44cc-11e8-93e1-41416ee570b5.png)
![image](https://user-images.githubusercontent.com/20693737/39047499-a814bd94-44cc-11e8-97a0-780dbc51fbc9.png)
![image](https://user-images.githubusercontent.com/20693737/39047644-32cc848a-44cd-11e8-8a0a-d24e24d16717.png)
![image](https://user-images.githubusercontent.com/20693737/39047663-44cc9eae-44cd-11e8-90b1-2303713ce860.png)

就是空文件夹，.git文件也删掉了

**Comment by Molunerfinn** [comment]
这个说明你一开始提交有问题。

我只说流程，这个是你git操作问题不属于hexo-theme-melody的问题，不要重复开issue。

1. 先删除你的melody文件夹，然后git commit 这个删除的修改。然后git push。
2. 重新clone melody主题，然后删除（或者剪切）.git文件夹到别处。然后git add这堆melody这个主题的所有文件，commit这个修改。
4. push你的所有文件到github。
3. 把.git文件夹放回melody文件夹即可。

总之，一开始的时候如果有.git文件夹，你必须先删除或者剪切到其他地方，否则在hexo目录下提交github会认为melody是个子模块。当你把melody的所有文件都提交到仓库中后再把.git文件夹放回来即可。
