### ISSUE TITLE
升级主题

### ISSUE THREAD

**Issue by WinstonJie** [Molunerfinn/hexo-theme-melody#70]
## I want to create a new issue  

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 

我开始并没有严格按照文档一样建立_data存放melody主题配置文件，如今想升级到1.5，应该有哪些步骤

## Feature Request

---

**Comment by Molunerfinn** [comment]
一定要注意看文档，_data文件夹是新建在你hexo博客的source路径下而不是主题的source路径下。
1. 按文档建立_data文件夹并存放主题配置文件。
2. 如果嫌麻烦就直接先删掉melody主题文件夹，然后重新clone最新的master分支的版本下来即可完成升级。
3. 之后所有的新配置都去_data里的melody.yml里改即可。就不会改变melody主题本身的代码了，以后直接pull即可。

**Comment by WinstonJie** [comment]
@Molunerfinn 在哪里pull，我还改了别的文件的一些代码，请问更新之后还是我更新的状态吗

**Comment by Molunerfinn** [comment]
@WinstonJie 在melody主题文件夹里pull- -。你改配置只需要去`source/_data/melody.yml`里改就行了。更新主题之后依然读取的是你的`source/_data/melody.yml`的配置。你如果改了别的文件代码，需要自己解决git pull后的冲突和合并。这个是git的相关操作内容，请不要继续提问了，去补习一下git吧。
