### ISSUE TITLE
升级主题

### ISSUE THREAD

**Issue by WinstonJie** [Molunerfinn/hexo-theme-melody#71]
## I want to create a new issue  

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

**Platform:不

**Browser:**

## Expected behavior 
= 不知道在哪里pull，pull完以后修改是在source里面的配置文件修改吗？》之前的主题配置会改变吗。我修改了一点文件也会变化吗

## Actual behavior 

![le2bz l _5gfpt2 zmmm32](https://user-images.githubusercontent.com/36364264/39091293-afe965b2-4623-11e8-8ec2-51385b53ed12.png)

## Feature Request

---

**Comment by Molunerfinn** [comment]
在melody主题文件夹里pull啊。。这个是git的操作，不应该我来教你。

**Comment by WinstonJie** [comment]
但是pull时有个error

**Comment by Molunerfinn** [comment]
@WinstonJie 这个需要你自行解决。这个是git操作相关的内容了。如果你改动了其他文件，你需要自己解决git pull合并的冲突。

**Comment by WinstonJie** [comment]
![kc 3ijrjhvg mszp5 cr k](https://user-images.githubusercontent.com/36364264/39091685-56f9bad4-462c-11e8-89fa-77f580d2128b.png)

**Comment by Molunerfinn** [comment]
提示说的很清楚了，你改动了本地文件，请你先commit或者stash他们: )然后再pull。如果pull有冲突请你自行解决冲突。
git 相关操作你需要自行去补习: )
