### ISSUE TITLE
有没有热更新的解决方案

### ISSUE THREAD

**Issue by xcsweb** [Molunerfinn/hexo-theme-melody#73]
**Melody Version:**

**Platform:*windows*

**Browser:*chrome*

请问作者有没有热更新的解决方案，不用每次编辑后保存，重新执行hexo s,才能看到页面，能不能实时预览

**Comment by Molunerfinn** [comment]
1. 修改配置文件后必须重启，无法热更新。
2. 修改具体页面代码如果是修改pug文件的无法热更新的话请参考这个[issue](https://github.com/hexojs/hexo-renderer-jade/issues/6)里我的回答，要修改一下`hexo-renderer-jade`的源码。修改完后hexo s可以保证pug、stylus、js文件改动能自动加载页面。

这个是与主题开发相关的问题，不是主题本身的问题，以后不要发issue。如果是主题开发相关的，可以参考我之前写的一篇文章：https://molunerfinn.com/make-a-hexo-theme/
