### ISSUE TITLE
关于Archives 分页的建议

### ISSUE THREAD

**Issue by Fridolph** [Molunerfinn/hexo-theme-melody#74]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.3

**Platform:** win / macOS

**Browser:** Chrome

## Feature Request

Archives 页 能否自定义分页数 ~ 一次显示10篇感觉页数很多，也不便于统计
可否自定义 ？ 或者实现按年度 来分页 （1年1页）

<img src="https://pic.sopili.net/pub/emoji/twitter/2/72x72/1f600.png" width=20 height=20>

**Comment by Molunerfinn** [comment]
这个分页是用的跟主页一样的分页器，每页显示的条数是在hexo的_config.yml（而不是melody的配置文件）里配置的。主页显示几条一页，这个也是显示几条一页，暂时无法修改。

**Comment by deamwork** [comment]
@Fridolph 
这个你可以通过装插件实现，https://github.com/hexojs/hexo-generator-archive
```bash
npm install hexo-generator-archive
# or 
# yarn add hexo-generator-archive
```
然后去hexo配置（不是主题配置）添加下面这段：

```
archive_generator:
  per_page: 7 # 这里设置你要的页数，0为不分页
  yearly: true
  monthly: true
  daily: false
  order_by: -date
```
但是如果设置0的话，页面最下面依旧会出现分页并显示`1`，这个还没解决
