### ISSUE TITLE
hexo generate error:join is not a function

### ISSUE THREAD

**Issue by kcomking1** [Molunerfinn/hexo-theme-melody#75]
![z_ 4mo6fmz6m an1tu 60](https://user-images.githubusercontent.com/12249755/39302547-98b5281c-4985-11e8-8f5f-87c9a533743e.png)

我在生成的时候出错 join is not a function
请指导下。

**Comment by Molunerfinn** [comment]
参考这个[issue](https://github.com/Molunerfinn/hexo-theme-melody/issues/58)的解决办法。
下次不按issue模板提交issue将会被直接关闭。
