### ISSUE TITLE
I want to be added to demo site

### ISSUE THREAD

**Issue by Limuyang1013** [Molunerfinn/hexo-theme-melody#76]
Hey作者好，几天前我还在用这Litten的Yillia主题，昨天看到你的主题感觉很漂亮花了一晚上的时间转移过来了的~希望能够被添加到Demo站点，后续的时间我会继续完善的，顺便提个优化点，我发现切换不同的category得时候头部的背景图有时候会一闪默认的纯蓝背景，不知道你那边是否可以复现
我的站点：https://www.limuyang.cc/

**Comment by Limuyang1013** [comment]
顺便感谢一下作者提供这么优秀的主题~thanks

**Comment by Molunerfinn** [comment]
请移步https://github.com/Molunerfinn/hexo-theme-melody/issues/1

**Comment by Molunerfinn** [comment]
切换会有纯蓝背景是正常的，因为图片加载需要时间，没图的情况下默认是蓝色背景。不过一旦浏览器缓存了背景图之后，切换将不会再有闪动。

**Comment by Limuyang1013** [comment]
那么是否可以将图片放在本地解析来避免这种情况呢

**Comment by Molunerfinn** [comment]
@Limuyang1013 图片都是以url的形式，无法本地解析。你可以换更快的cdn以及把图片体积压缩地更小来优化这个问题。

**Comment by Limuyang1013** [comment]
OK，了解了，再次表示感谢

**Comment by Molunerfinn** [comment]
不客气~

**Comment by upupming** [comment]
路过 :+1:
