### ISSUE TITLE
翻译文件zh-Hans.yml有点问题

### ISSUE THREAD

**Issue by Waitung** [Molunerfinn/hexo-theme-melody#78]
## Melody Information

**Melody Version:** v1.5.3

**Platform:** Windows

**Browser:** FireFox,Chrome

    page:
      Articles: 文章总览
      Tag: 标签
      Category: 分类
这里应该改为

    page:
      articles: 文章总览
      tag: 标签
      category: 分类

测试了一下，大写字母开头的是en.yml翻译后的内容，会导致http:../archives/等几个页面里的内容不能正确被翻译。
第一次使用hexo,希望不是我搞错了。

**Comment by Molunerfinn** [comment]
感谢指出bug，已经修复~
