### ISSUE TITLE
wordcount一开就不行了

### ISSUE THREAD

**Issue by WinstonJie** [Molunerfinn/hexo-theme-melody#80]
## I want to create a new issue  

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 
wordcount一开就不行了
## Actual behavior 
![c 1 ard b e sye 1 m52q](https://user-images.githubusercontent.com/36364264/39466855-8e2ad488-4d5d-11e8-921a-f92fa6f88432.png)

## Feature Request

---

**Comment by Molunerfinn** [comment]
请发issue之前，看看主题的文档：
https://molunerfinn.com/hexo-theme-melody-doc/#/zh-Hans/additional-package-support
![image](https://user-images.githubusercontent.com/12621342/39472068-845afe58-4d79-11e8-922c-6e2aab177f1f.png)
