### ISSUE TITLE
how to adjust Valine font size ?

### ISSUE THREAD

**Issue by Zeecoders** [Molunerfinn/hexo-theme-melody#84]
## Melody Information

**Melody Version:** lastest

**Platform:** macos

**Browser:** chrome

## Actual behavior 
how to adjust Valine font size ?

![image](https://user-images.githubusercontent.com/11804958/39907206-bb2a8e38-5519-11e8-8610-0e4e552894ff.png)

## Steps to reproduce the behavior 
zcheng.ren

## Feature Request

---

**Comment by Molunerfinn** [comment]
OK, I can't help you to modify anything you want. If you want to modify theme-melody, I think you need to learn CSS by yourself. By the way, the Valine comment system is a third-party lib for theme-melody, I didn't change it at all. So how to adjust it , you need to ask for [Valine](https://github.com/xCss/Valine)
