### ISSUE TITLE
How could I deploy Adobe Typekit on theme-melody?

### ISSUE THREAD

**Issue by hesongtao96** [Molunerfinn/hexo-theme-melody#85]
Hi there, thanks for your wonderful job. Recently I begin to get interested in substituting the default `Microsoft Yahei` into `source-han-serif` through Adobe Typekit. There are several tutorials on Internet instructing us the steps specifically. Like this: [Hexo Maupassant 主题更换 Source Han Serif 思源宋体](http://z.arlmy.me/posts/Hexo/Hexo_ChangeMainFont2SourceHanSerif/)
But I failed to find the exact files to modify because of the difference of the theme framework between  these two themes. I wonder if you could write a tutorial on how to deploy Adobe Typekit on `theme-melody`. That would be so helpful when users want to change the fonts they like. Thanks a lot for your help.

Sincerely,
Songtao

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information
**Melody Version:1.5.3
**Platform:Windows 10
**Browser:Chrome

**Comment by Molunerfinn** [comment]
Hi, I can help you to do this one time but I can't do this all the time. I spend time creating & maintaining the theme & the docs for it. So I do not have time to teach you how to modify it. You should learn some CSS or HTML knowledge by yourself. For this time I can tell you how to change it, but next time I won't.

Change this line & write down your favorite font.

https://github.com/Molunerfinn/hexo-theme-melody/blob/dev/source/css/var.styl#L12

![image](https://user-images.githubusercontent.com/12621342/39954923-3683bed4-55fa-11e8-85d3-8051aabe56ff.png)
