### ISSUE TITLE
用IP访问时PV UV统计正常，用域名访问则不显示PV UV

### ISSUE THREAD

**Issue by Buce21** [Molunerfinn/hexo-theme-melody#86]
用IP访问时PV UV统计正常，用域名访问则不显示PV UV

http://910406.com/

**Comment by Molunerfinn** [comment]
这个你应该去向busuanzi提问，melody只是用了它的服务。
http://ibruce.info/2015/04/04/busuanzi/
![image](https://user-images.githubusercontent.com/12621342/40161262-cdea3316-59e2-11e8-8db1-5b1c58037c87.png)
