### ISSUE TITLE
code in Gitalk comment doesn't show properly

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#87]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** 1.5.2

**Platform:** Ubuntu 18.10

**Browser:** Chrome

## Expected behavior 

The gitlk demo site display code pretty well.
![screenshot from 2018-05-19 21-40-59](https://user-images.githubusercontent.com/24741764/40269199-6151424a-5bad-11e8-84ff-85e2903f7e4e.png)

## Actual behavior 

When I added [a new comment](https://upupming.site/2018/04/03/gradle-travis/#gitalk-container) with some code blocks, some words cannot be displayed properly. I had to select them before I could see them.
![screenshot from 2018-05-19 21-38-48](https://user-images.githubusercontent.com/24741764/40269178-0cc23c48-5bad-11e8-850f-043f6506fe88.png)

I also tested on your blog(a fork from your repo), but [the result](http://marksz.upupming.site/koa2-wechatpay/#gitalk-container) is the same.

I think this is caused by the Material Theme code highlight.

**Comment by Molunerfinn** [comment]
They use the same CSS, so some of the color may not be right for the comment.
I will find a way to fix it.

**Comment by upupming** [comment]
I think gitment will also be affected, so the best solution may be ignoring melody's CSS in the comment container, what do you think, is it possible?

**Comment by Molunerfinn** [comment]
@upupming Yes, I have done.
