### ISSUE TITLE
a problem about melody add Valine comment plugin

### ISSUE THREAD

**Issue by Folgerjun** [Molunerfinn/hexo-theme-melody#88]
## I want to create a new issue  

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version: 1.5.4**

**Platform: Windows**

**Browser: Chrome**

## Expected behavior 
only Article page should show the comment

## Actual behavior 
all page show ,E.g:
![image](https://user-images.githubusercontent.com/24917694/40341010-2b5ced60-5db5-11e8-8f30-ebf1c7baba79.png)

## Steps to reproduce the behavior 
I just  `hexo new page about`

what I should do?

---

**Comment by upupming** [comment]
See this commit for more information.
https://github.com/Molunerfinn/hexo-theme-melody/commit/97a054db46f5e09e9a7682742175d9ee9d5d3767

**Comment by Molunerfinn** [comment]
In your page folder, you can find an `index.md`, set the `comments` option to false can solve your problem.
![image](https://user-images.githubusercontent.com/12621342/40341284-d2ccc5d8-5db6-11e8-9a23-b8a6ee0f8592.png)
By the way, see the [commit](https://github.com/Molunerfinn/hexo-theme-melody/commit/97a054db46f5e09e9a7682742175d9ee9d5d3767) and you will know why. Thanks to @upupming .

**Comment by Folgerjun** [comment]
@upupming @Molunerfinn Thank you two , 原谅我4级没过的English..
