### ISSUE TITLE
I want to put a piece of code in the footer area.

### ISSUE THREAD

**Issue by ZhangYanTJU** [Molunerfinn/hexo-theme-melody#89]
- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:** latest

**Platform:** Windows

**Browser:** Chrome

## Feature Request
I am using Coding pages to support my blog. And it requires a flag in my blog.
Like this
`<p>Hosted by <a href="https://pages.coding.me" style="font-weight: bold">Coding Pages</a></p>`

Then I must modify 'footer.pug' for this feature. But I know this will prevent my updating this theme smoothly.
So, can you please add this feature in this theme?

**Comment by Molunerfinn** [comment]
No, it's not my duty to do this.
You can commit it. And you can update the theme by `git pull --rebase`.
