### ISSUE TITLE
Mathjax render conflits

### ISSUE THREAD

**Issue by upupming** [Molunerfinn/hexo-theme-melody#93]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

**Platform:** Ubuntu 18.04

**Browser:** Chrome

## Expected behavior 

I'm writng with mathjax on [another website](https://writing.upupming.site/), and this is two pieces of code I write:
```mathjax
$\{0^n1^n\,|\,n \ge 1 \}$
```
```mathjax
$$\begin{align}
S &\to \epsilon\, \\
S &\to 001A\,|\,00A1\,|0A01\,|\,A001 \\ 
S &\to 010A\,|\,01A0\,|0A10\,|\,A010 \\ 
S &\to 100A\,|\,10A0\,|1A00\,|\,A100 \\ 
\end{align}$$
```
They are rendered as:
![screenshot from 2018-06-06 09-42-16](https://user-images.githubusercontent.com/24741764/41011127-f0374f36-696d-11e8-8477-132a4911a7c6.png)
![screenshot from 2018-06-06 09-43-59](https://user-images.githubusercontent.com/24741764/41011174-2fb03772-696e-11e8-809e-2fd79b337aee.png)

This is my expected behavior, but not the case in melody.
## Actual behavior 

![screenshot from 2018-06-06 09-45-55](https://user-images.githubusercontent.com/24741764/41011231-71010efe-696e-11e8-8258-ca14a6e85fa1.png)

![screenshot from 2018-06-06 09-46-27](https://user-images.githubusercontent.com/24741764/41011245-814c0728-696e-11e8-9e95-897ec5ccbfd8.png)

I found that I have to change all `\{` to `\\{`, and all `\\` to `\\\\` to make melody works, which is believed to be a confilct between mathjax and markdown engine melody  is using now.

Could you please fix this bug or give some advice? Thanks in advance!

**Comment by Molunerfinn** [comment]
Find a solution:
https://www.npmjs.com/package/hexo-renderer-kramed
![image](https://user-images.githubusercontent.com/12621342/41012862-49cd9ed0-6976-11e8-8ef2-28c6b4208aa8.png)
And this is my test result:
![image](https://user-images.githubusercontent.com/12621342/41013182-63936da8-6977-11e8-8b3c-55719324d993.png)
I think may be I need to update the docs.

**Comment by upupming** [comment]
This still not works(expected `{` wasn't rendered):
```tex
$\{a = 0\}$
```
![screenshot from 2018-06-06 22-03-55](https://user-images.githubusercontent.com/24741764/41042989-8c349724-69d5-11e8-8d83-c138759f7818.png)

But this is okay:
```tex
$$\{a = 0\}$$
```
![screenshot from 2018-06-06 22-03-15](https://user-images.githubusercontent.com/24741764/41042942-7a96a214-69d5-11e8-9fce-a2d80cfd7838.png)
<hr>

kramed render suggests inline equations using this format, which is difficult to be compatible with the usual tex syntax:
```tex
`$\{a = 0\}$`
```
I cannot find any better solution, so I will use  
```
`$$`
```
 tag for inline equation.

**Comment by Molunerfinn** [comment]
@upupming To have `MathJax` on hexo is a hard work. Not only should the theme do some work to fit it, but also the hexo and the plugin of it need to fit it. Since I didn't write mathJax in my blog, may be I won't meet problem. May be someone has solve this problem, and I will appreciate it if he can give the project a PR~
