### ISSUE TITLE
在站点预览中加入全局搜索框

### ISSUE THREAD

**Issue by jzoe** [Molunerfinn/hexo-theme-melody#97]
## I want to create a new issue  

- [x] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [x] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [x] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

**Platform:** windows

**Browser:** chrome

## Feature Request

搜索和标签分类是博客中最重要的两个功能，能否在站点预览的侧边栏中加入搜索框？

![image](https://user-images.githubusercontent.com/11612990/41583583-8e3814cc-73d7-11e8-89c9-872ae559ee6f.png)

---

**Comment by Molunerfinn** [comment]
搜索功能已在主页顶部提供：
![image](https://user-images.githubusercontent.com/12621342/41584515-04eb410a-73da-11e8-9fea-16afa67cb605.png)

并提供两种方式全站搜索：algolia或者local-search。详见文档：https://molunerfinn.com/hexo-theme-melody-doc/#/third-party-support?id=search

侧边栏不准备放置搜索框。

**Comment by jzoe** [comment]
主页上的我看到了，但是只在主页有搜索框的话，就要求用户每次需要搜索的时候都需要进入主页。这样搜索功能会不会隐藏的太深了？

通常搜索框一般设计在顶部导航栏会比较合理点吧？
![image](https://user-images.githubusercontent.com/11612990/41584804-d3d0e9fc-73da-11e8-980a-9bcefa46fc31.png)

但现在顶部导航栏是没有锚定在顶部的，所有放侧边栏上会方便点。

**Comment by Molunerfinn** [comment]
侧边栏空间已经很狭窄了，不足以放下搜索框和搜索内容区。另外在手机上是看不到侧边栏的。

**Comment by jzoe** [comment]
可以在鼠标上滚的header上加啊，类似知乎的处理

![image](https://user-images.githubusercontent.com/11612990/41585331-530c84dc-73dc-11e8-9080-ba9be1f5faf2.png)

例如这个
https://www.zhihu.com/question/24422335/answers/created

上滚的时候显示搜索框，下滚的时候的显示标题等

![image](https://user-images.githubusercontent.com/11612990/41585382-7723fb66-73dc-11e8-898a-cddc955dad3a.png)

![image](https://user-images.githubusercontent.com/11612990/41585391-80b5d80c-73dc-11e8-99ad-51fa3f22e6d4.png)

**Comment by Molunerfinn** [comment]
知乎的顶部并非是透明或者半透明的，他加入搜索框和背景色能贴合。
但是melody主题的顶部栏是透明/半透明的。搜索框加入在应对深色背景时会非常突兀。

**Comment by Molunerfinn** [comment]
不过你的想法也是有合理性的。需要一个醒目的位置给予搜索的标识。我会考虑在下一版在合适的位置加入搜索功能又不丢失当前主题的特性。

**Comment by jzoe** [comment]
可以考虑把顶部的导航栏修改为非透明的。期待下一个版本！

**Comment by Molunerfinn** [comment]
@upupming 有没有什么想法？

**Comment by upupming** [comment]
谢谢，很乐意发表看法！

## 1. 放在左边侧边栏不太方便：

1. 空间狭窄
2. 手机不可见
3. 电脑端也不太容易发现这个功能



## 2. 放在导航栏是一个好想法：

### 2.1 如何解决**透明导航栏上搜索文字**和**背景**冲突？

我的想法是在用户**点击搜索之后把背景变为不透明**，因为用户想搜索时就可能不再关注文章内容了，可以把注意力提到搜索文字上。

### 2.2 如何布局呢？

  看了一下 [Google Blog](https://www.blog.google/products/google-play/imakeapps-meet-faith-ringgold-88-year-old-artist-and-game-maker/) 的布局方案，我觉得可以借鉴。


#### 2.2.1 电脑端

<img src="https://user-images.githubusercontent.com/24741764/41656423-770a9d24-74c2-11e8-8f1d-77e6277d52b6.png">

|搜索前|搜索中|
|:-:|:-:|
|<img src=https://user-images.githubusercontent.com/24741764/41656800-c3ef9882-74c3-11e8-87b6-d4d67483ac28.png>|<img src=https://user-images.githubusercontent.com/24741764/41656238-e7ceb640-74c1-11e8-9ee2-105d11fc055f.png>|

另外**搜索中**，可以加一个 Esc 键退出搜索的功能。


#### 2.2.2 手机端

可以在用户点击展开菜单之后出现一个搜索框，也是在点击之后把背景变为不透明，个人感觉这个变化过程也许可以做的很好。

|melody|Google Blog|知乎（没有搜索框）|
|:--:|:--:|:--:|
|<img src="https://user-images.githubusercontent.com/24741764/41654986-c47fd7d6-74bd-11e8-9bbc-f8e6c420da01.png" height="200">|<img src=https://user-images.githubusercontent.com/24741764/41655560-d040a06c-74bf-11e8-8e09-4788137dd672.png height=200>|<img src="https://user-images.githubusercontent.com/24741764/41655257-f08f281c-74be-11e8-8ee7-24438497dcde.png" height=200>|
|<img src=https://user-images.githubusercontent.com/24741764/41655484-9b7cc5c2-74bf-11e8-9049-caa95056deb2.png height=200>|<img src="https://user-images.githubusercontent.com/24741764/41655132-7062c270-74be-11e8-98a1-b02adf3a1daf.png" height="200">||

希望 melody 越来越好！

**Comment by Molunerfinn** [comment]
@upupming 我的想法是搜索功能并不用拘泥于搜索框。甚至给一个放大镜即可。点击放大镜，调用的依然是目前的搜索对话框。

主要有如下几点考虑。

- 如果要用搜索框，那么搜索结果的存放只有两个去处：1.搜索结果页；2.在搜索框下拉放置内容。
第一点，搜索结果页并非melody能控制，甚至需要用户手动创建一个页面来存放这个结果，所以第一点不能考虑。
第二点在搜索框下拉存放搜索结果，那么就会遇到电脑端显示合格，而手机端有可能不够放的问题。因为这个严重依赖当前搜索框的位置以及宽度。

- 下拉型搜索框能显示的条数有限而且不宜做分页。

- 相对的只用搜索按钮的话有如下几个方面的好处：

1. 搜索按钮触发的依然是目前的搜索对话框，操作逻辑与当前一致。
2. 搜索结果的存放区域也比较合理。
3. 占用空间小，也可以不用考虑顶部栏透明度问题。

**Comment by upupming** [comment]
很有道理，那就可以只增加**搜索按钮**(图标、文字都可以，感觉文字更加匹配其他的“主页”、“标签”)，现有的**搜索对话框**保持不变。

**Comment by Molunerfinn** [comment]
@upupming 嗯。纯文本也许不够显眼。我可以考虑在「搜索」二字前放一个放大镜图标

**Comment by Molunerfinn** [comment]
在这个提交里实现了这个功能：https://github.com/Molunerfinn/hexo-theme-melody/commit/082fed0fca95cda63af0a4c454abe3a9ba948fbc
![image](https://user-images.githubusercontent.com/12621342/41663525-3a014f0e-74d6-11e8-8d7f-92ecb412a628.png)
![image](https://user-images.githubusercontent.com/12621342/41663544-455d8200-74d6-11e8-8429-6e92f5f44201.png)
「搜索」二字是根据当前选择的语言而决定的。如果选择`zh-Hans`显示「搜索」。如果是选择`en`或者`default`显示「Searh」

**Comment by upupming** [comment]
@Molunerfinn 你是在主页测试的吗？我这边主页里面点击可以打开 alogia 搜索，在文章里点击没反应。

**Comment by Molunerfinn** [comment]
@upupming 哦对。文章页里没有搜索的元素。我给加一下

**Comment by upupming** [comment]
这儿吗？
https://github.com/Molunerfinn/hexo-theme-melody/blob/082fed0fca95cda63af0a4c454abe3a9ba948fbc/layout/includes/additional-js.pug#L1

**Comment by Molunerfinn** [comment]
@upupming Done
