### ISSUE TITLE
文章列表预览中，如果预览的内容包含代码块会导致乱码

### ISSUE THREAD

**Issue by jzoe** [Molunerfinn/hexo-theme-melody#99]
## I want to create a new issue  

- [] Yes, I have read [Hexo Docs page](https://hexo.io/docs/), especially [Templates](https://hexo.io/docs/templates.html), [Variables](https://hexo.io/docs/variables.html), [Helpers](https://hexo.io/docs/helpers.html) and [Troubleshooting](https://hexo.io/docs/troubleshooting.html).
- [] Yes, I have read [Hexo-theme-melody Documentation](https://molunerfinn.com/hexo-theme-melody-doc/).
- [] And yes, I already searched for current [issues](https://github.com/Molunerfinn/hexo-theme-melody/issues?utf8=%E2%9C%93&q=is%3Aissue) and this is not help to me.

## Melody Information

**Melody Version:**

**Platform:**

**Browser:**

## Expected behavior 
预览的代码块应该正常显示

## Actual behavior 
预览的代码块显示为数字乱码

文章是这样的
![image](https://user-images.githubusercontent.com/11612990/41595801-ad4e85f8-73fa-11e8-8a17-60ac5f172291.png)

预览是这样的
![image](https://user-images.githubusercontent.com/11612990/41595865-ea6d6ae4-73fa-11e8-964d-70231f7c09d3.png)

## Feature Request

---

**Comment by Molunerfinn** [comment]
![image](https://user-images.githubusercontent.com/12621342/41595948-3ba333a8-73fb-11e8-9a72-1b217f9b5e6b.png)
你用的是master的代码么，能否多提供一些你的信息呢？你这样的issue提交是很不合规范的，按理说我应该关闭的。如果你用的是dev的代码，我已经在文档里说了dev的代码不稳定，如果有问题需要自己解决。

**Comment by jzoe** [comment]
我用的是master分支，按照文档中说明下载的

![image](https://user-images.githubusercontent.com/11612990/41632920-cbfdeab0-746e-11e8-8b98-3b89fa481360.png)

**Comment by Molunerfinn** [comment]
如果你采用的是auto_excerpt的功能，会自动截取指定字符数的文本。所以如果想要代码正确显示，请关闭这个功能，并自己手动用`<!-- more -->`的方式插入「更多」的按钮。

**Comment by jzoe** [comment]
我用的是 auto_excerpt 的功能，但自动截取的时候，为啥会把 ` ``` ` 代码分隔符转为 `0123456789` 这种的数字呢？

**Comment by Molunerfinn** [comment]
前面那堆是生成的行号

**Comment by jzoe** [comment]
好的，看来只能自己手动避免了！非常感谢 @Molunerfinn

**Comment by Molunerfinn** [comment]
回头我会在文档里标注一下这点

**Comment by jzoe** [comment]
另外，对于头像 avatar和favicon.ico 两个项能否支持 `Smoothly update (Use the Hexo data files feature)` 呢?现在我是直接替换主题中的 source 文件夹下的两个文件，但这样的话，每次`git pull` 后都需要手动替换。是否支持呢，不支持的话能否添加新功能，支持的话能否在文档中说明一下？

**Comment by Molunerfinn** [comment]
你可以放在站点的source目录下而不是主题的source下这样就不会影响了

**Comment by jzoe** [comment]
测试了一下，站点下的 source/img/avatar.png 是成功替换了的，但 站点下的 source/faviconico 没有替换成功。

**Comment by Molunerfinn** [comment]
有可能只是缓存问题

**Comment by jzoe** [comment]
我是直接看生成的 public 文件夹下的文件来确认是否替换，而不是浏览器中查看的。

**Comment by Molunerfinn** [comment]
你可以先hexo clean然后再hexo g生成一遍试试

**Comment by Molunerfinn** [comment]
@jzoe 发现这个问题，source目录下的favicon.ico在生成的时候不会被站点的favicon.ico覆盖。这个应该是hexo的一个bug。目前解决方式如下：

1. 改名你的`favicon.ico`为其他名字。比如`my-favicon.ico`
2. 去`melody.yml`里配置一下`favicon`字段比如：

![image](https://user-images.githubusercontent.com/12621342/41636686-861a68ca-7482-11e8-803e-f4219cfb7640.png)

实际上favicon和avatar都可以在`melody.yml`里配置。可以配置成url的形式。文档里只给出了avatar，后续我会把favicon也加上。

![image](https://user-images.githubusercontent.com/12621342/41636714-b4d94014-7482-11e8-97f9-33aa7e969c3d.png)

**Comment by upupming** [comment]
关于代码行号的这个还有一个小问题，就是在 RSS 订阅中会显示成一段代前面有很多行号，这是因为 hexo 生成的行号是很多在一起的 `<span>`
![screenshot from 2018-06-20 20-15-55](https://user-images.githubusercontent.com/24741764/41657696-c69a3c92-74c6-11e8-8fdc-11af424c0df0.png)
最近 dev 分支增加的[代码自动换行](https://github.com/Molunerfinn/hexo-theme-melody/pull/95)可以解决它了。
